<?php
/**
 * @file
 * Holds functions that utilize the Braintree PHP library.
 */

/**
 * Look up Braintree customer object by customer ID.
 *
 * @param int $customer_id
 *   The customer ID.
 *
 * @return bool|\Braintree\Customer
 *   The Braintree\Customer object or FALSE if not found.
 */
function braintree_vault_customer_load($customer_id) {
  try {
    $customer = Braintree_Customer::find($customer_id);
    $context['result']->result = $customer;
    return $customer;
  }
  catch (Braintree_Exception_NotFound $e) {
    $error_message = braintree_report_error($e);
    $context['result']->message = $error_message;
    return array(FALSE, $context['result']);
  }
}

/**
 * Save customer record to Braintree vault.
 *
 * @param array $customer_data
 *   The customer data used to create the customer.
 *
 * @return bool|\Braintree_Customer
 */
function braintree_vault_customer_save($customer_data) {
  drupal_alter('braintree_vault_customer_data', $customer_data);

  try {
    $result = Braintree_Customer::create($customer_data);
  }
  catch (Exception $e) {
    braintree_report_error($e);
    return FALSE;
  }

  if ($result->success) {
    // Invoke post hook when sale is completed successfully.
    foreach (module_implements('braintree_vault_customer_saved') as $module) {
      $function = $module . '_braintree_vault_customer_saved';
      $function($result, $context);
    }

    return $result;
  }

  braintree_report_error($result);
  return FALSE;
}

/**
 * Save payment method to Braintree vault.
 *
 * @param array $payment_method
 *   The payment method to create or update.
 * @param array $context
 *   An array of contextual information for other code.
 * @param array $settings
 *   An optional array of settings to initialize the braintree library with.
 *
 * @return array
 *   An array structure where the first element is whether the payment method
 *   was saved successfully, and the second element is a contextual array of
 *   related information like error messages.
 */
function braintree_vault_payment_method_save($payment_method, $context = array(), $settings = array()) {
  // Prevent duplicate cards from being created.
  $payment_method['options']['failOnDuplicatePaymentMethod'] = TRUE;

  dpm($payment_method);
  braintree_initialize($settings);

  drupal_alter('braintree_payment_method', $payment_method, $context);

  $params = array();
  $edit = FALSE;
  if (isset($context['options'])) {
    $params['options'] = $context['options'];
  }
  if ($context['op'] == 'edit') {
    $params['paymentMethodNonce'] = $payment_method['paymentMethodNonce'];
    $edit = TRUE;
  }

  try {
    if ($edit) {
      $context['result'] = Braintree_PaymentMethod::update($payment_method['paymentMethodToken'], $params);
    }
    else {
      $context['result'] = Braintree_PaymentMethod::create($payment_method);
    }
  }
  catch (Exception $e) {
    $error_message = braintree_report_error($e);
    $context['error'] = $error_message;
    return array(FALSE, $context);
  }

  if ($context['result']->success) {
    global $user;
    braintree_vault_customer_cache_reset($user->uid);

    // Invoke post hook when sale is completed successfully.
    foreach (module_implements('braintree_vault_payment_method_saved') as $module) {
      $function = $module . '_braintree_vault_payment_method_saved';
      $function($context);
    }

    return array(TRUE, $context);
  }

  $error_message = braintree_report_result($context['result']);
  return array(FALSE, $context);
}

/**
 * Delete payment method from Braintree vault.
 *
 * @param array $payment_method
 *   The payment method to delete.
 * @param array $context
 *   An array of contextual information for other code.
 * @param array $settings
 *   An optional array of settings to initialize the braintree library with.
 *
 * @return array
 *   An array structure where the first element is whether the payment method
 *   was saved successfully, and the second element is a contextual array of
 *   related information like error messages.
 */
function braintree_vault_payment_method_delete($payment_method, $context = array(), $settings = array()) {
  try {
    $context['result'] = Braintree_PaymentMethod::delete($payment_method->token);
  }
  catch (Exception $e) {
    $context['error'] = braintree_report_error($e);
    return array(FALSE, $context);
  }

  if ($context['result']->success) {
    global $user;
    braintree_vault_customer_cache_reset($user->uid);

    // Invoke post hook when sale is completed successfully.
    foreach (module_implements('braintree_vault_payment_method_delete') as $module) {
      $function = $module . '_braintree_vault_payment_method_delete';
      $function($context);
    }

    return array(TRUE, $context);
  }

  $context['error'] = braintree_report_error($context['result']);
  return array(FALSE, $context);
}

/**
 * Change default payment method from Brantree vault.
 *
 * @param \Braintree\PayPalAccount|\Braintree\CreditCard $payment_method
 *   An object of Braintree payment method.
 * @param array $context
 *   An array of contextual information for other code.
 *
 * @return array
 *   An array structure where the first element is whether the payment method
 *   was saved successfully, and the second element is a contextual array of
 *   related information like error messages.
 */
function braintree_vault_payment_method_make_default($payment_method, $context = array()) {
  if (braintree_payment_method_is_paypal($payment_method)) {
    $class = 'Braintree_PayPalAccount';
  }
  else {
    $class = 'Braintree_PaymentMethod';
  }

  try {
    $context['result'] = $class::update($payment_method->token, array(
      'options' => array('makeDefault' => TRUE),
    ));
  }
  catch (Exception $e) {
    $context['error'] = braintree_report_error($e);
    return array(FALSE, $context);
  }

  if ($context['result']->success) {
    // Invoke post hook when sale is completed successfully.
    foreach (module_implements('braintree_vault_payment_method_make_default') as $module) {
      $function = $module . '_braintree_vault_payment_method_make_default';
      $function($context);
    }

    return array(TRUE, $context);
  }

  $context['error'] = braintree_report_error($context['result']);
  return array(FALSE, $context);
}

/**
 * Update customer record with Braintree vault.
 *
 * @param int $customer_id
 *   The customer's Braintree ID.
 * @param array $customer_data
 *   The customer data used to update the customer.
 *
 * @return bool|\Braintree_Customer
 */
function braintree_vault_customer_update($customer_id, $customer_data) {
  drupal_alter('braintree_vault_customer_data', $customer_data);

  try {
    $result = Braintree_Customer::update($customer_id, $customer_data);
  }
  catch (Exception $e) {
    braintree_report_error($e);
    return FALSE;
  }

  if ($result->success) {
    // Invoke post hook when sale is completed successfully.
    foreach (module_implements('braintree_vault_customer_updated') as $module) {
      $function = $module . '_braintree_vault_customer_updated';
      $function($result, $context);
    }

    return $result;
  }

  braintree_report_error($result);
  return FALSE;
}
