<?php

// Include the commerce payment method functions file
module_load_include('inc', 'fundraiser_commerce_payflow', 'includes/fundraiser_commerce_payflow.payflow_cc');

/**
 * Implements hook_fundraiser_gateway_info().
 */
function fundraiser_commerce_payflow_fundraiser_gateway_info() {
  // Load all the methods available.
  $methods = new stdClass();
  $methods->payment_methods = array();
  rules_invoke_all('commerce_payment_methods', $methods);
  $fundraiser_gateways = array();

  // Loop through the configured payment rules and look for payflow rules
  foreach ($methods->payment_methods as $id => $info) {
    $this_gateway = array();
    $method_instance = commerce_payment_method_instance_load($id);
    list($method_id, $rule_name) = explode('|', $method_instance['instance_id']);

    $payflow_link_types = array('payflow_link', 'paypal_ppa');
    // Add gateway information for a commerce payflow rule
    if (!empty($method_id) && !empty($rule_name) && in_array($method_instance['method_id'], $payflow_link_types)) {
      // Add the standard info for a payflow gateway
      $this_gateway = _fundraiser_commerce_payflow_standard_gateway_settings($rule_name, $method_instance);

      // Add the specific callbacks to support the payflow link processing
      $this_gateway['form callback'] = '_fundraiser_commerce_payflow_submit_form';
      $this_gateway['charge callback'] = '_fundraiser_commerce_payflow_charge';
      $this_gateway['redirect callback'] = '_fundraiser_commerce_payflow_redirect';
      $this_gateway['validate callback'] = '_fundraiser_commerce_payflow_validate';

      // Add this to the main gateway
      $fundraiser_gateways[$this_gateway['id']] = $this_gateway;
    }
    // Add gateway information for a fundriaser commerce payflow rule
    elseif (!empty($method_id) && !empty($rule_name) && $method_instance['method_id'] == 'fundraiser_commerce_payflow_cc') {
      // Add the standard info for a payflow gateway
      $this_gateway = _fundraiser_commerce_payflow_standard_gateway_settings($rule_name, $method_instance);

      // Add the specific callbacks to support the direct cc processing
      $this_gateway['form callback'] = '_fundraiser_commerce_payflow_cc_submit_form';
      $this_gateway['charge callback'] = '_fundraiser_commerce_payflow_cc_charge';
      $this_gateway['validate callback'] = '_fundraiser_commerce_payflow_cc_validate';
      $this_gateway['cleanup callback'] = '_fundraiser_commerce_payflow_cc_cleanup';
      $this_gateway['scrub callback'] = '_fundraiser_commerce_payflow_cc_scrub';

      // Add this to the main gateway
      $fundraiser_gateways[$this_gateway['id']] = $this_gateway;
    }
  }

  return $fundraiser_gateways;
}

/**
 * Assembles the standard gateway config for the payflow gateway settings
 */
function _fundraiser_commerce_payflow_standard_gateway_settings($rule_name, $method_instance) {
  $rule_config = rules_config_load($rule_name);
  return array(
    'id' => $method_instance['instance_id'],
    'module' => 'fundraiser_commerce_payflow',
    'module_name' => t('Fundraiser Commerce Payflow'),
    'title' => $rule_config->label,
    'description' => $method_instance['description'],
    'payment_method' => array('credit'),
    'allow_recurring' => array('credit'),
    // Important note: While payflow_link is an offsite processor, reference charges are handled onsite
    // We handle that switch in the charge callback
    'offsite_processing' => array(),
    'offsite_recurring' => array(),
    'expire callback' => '_fundraiser_commerce_payflow_expire',
    'refund callback' => '_fundraiser_commerce_payflow_refund',
    'allow_refund' => array('credit'),
    'gateway_details' => $method_instance,
  );
}

/**
 * Implements hook_commerce_payment_method_info
 */
function fundraiser_commerce_payflow_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['fundraiser_commerce_payflow_cc'] = array(
    'base' => 'fundraiser_commerce_payflow_cc',
    'title' => t('Fundraiser Payflow Credit Card'),
    'short_title' => t('Fundraiser Payflow'),
    'display_title' => t('Credit card'),
    'description' => t('Integrates Litle for credit card transactions.'),
    'file' => 'includes/fundraiser_commerce_payflow.payflow_cc.inc'
  );

  return $payment_methods;
}

/**
 * Implements hook_preprocess_webform_confirmation
 */
function fundraiser_commerce_payflow_preprocess_webform_confirmation(&$vars) {
  $donation = _fundraiser_webform_get_donation_by_sid($vars['sid']);

  // If this donation was handled by commerce payflow add the redirect script
  if (!empty($donation->gateway['gateway_details']['module'])
   && $donation->gateway['gateway_details']['module'] == 'commerce_payflow') {
    // Use the payflow modules redirect script
    drupal_add_js(drupal_get_path('module', 'commerce_payflow') . '/commerce_payflow.js');
  }
}

/**
 * Callback
 */
function _fundraiser_commerce_payflow_submit_form($payment_method, $config = NULL) {
  $form = array();
  if (!empty($config)) {
    $method_instance = commerce_payment_method_instance_load($config['id']);
  }

  // Show instructions if thats configured
  if (!empty($method_instance['settings']['show_payment_instructions'])) {
    $form['payflow_information'] = array(
      '#markup' => '<span class="commerce-paypal-wps-info">' . t('After submitting this form you will be taken to another form to enter your payment details.') . '</span>',
    );
  }

  // On the recurring update form let users know payflow doesn't support updating card data
  if (arg(2) == 'recurring_overview') {
    $form['payflow_no_update'] = array(
      '#markup' => '<span class="commerce-payflow-info">' . t('Please contact customer support to make changes to your card data.') . '</span>',
    );
  }

  // To avoid errors on form validation return a value
  $form['payflow_flag'] = array(
    '#type' => 'hidden',
    '#value' => 1,
  );

  return $form;
}

/**
 * Donation form validate callback
 *
 * Nothing to validate since payflow data isn't submitted on the form
 */
function _fundraiser_commerce_payflow_validate() {
  return;
}

/**
 * Callback charge function for the payflow link processer
 */
function _fundraiser_commerce_payflow_charge($payment_method, $donation) {
  // If this is not a refernce charge use fundraiser's redirect functionality
  if (empty($donation->reference_charge)) {
    _fundraiser_commerce_fundraiser_donation_process_external($donation, $donation->gateway);
  }
  // For reference charges use our custom function
  elseif ($donation->reference_charge == TRUE) {
    return _fundraiser_commerce_payflow_reference_charge($donation);
  }
}

/**
 * Redirect form callback
 *
 * Returns a form for sending the user to payflow or an iframed cc form
 */
function _fundraiser_commerce_payflow_redirect($method_instance, $donation, $order, $settings) {
  $form = array();
  $form_state = array();
  $pane_form = array();
  $pane_values = array();
  $charge = NULL;

  commerce_payflow_link_submit_form_submit($method_instance, $pane_form, $pane_values, $order, $charge);
  // Save the order to store the redirect key
  commerce_order_save($order);

  // Build the form
  return commerce_payflow_link_redirect_form($form, $form_state, $order, $method_instance);
}

/**
 * Redirect submit callback
 */
function _fundraiser_commerce_payflow_redirect_submit($method_instance, $donation, $order) {
  // Let the module complete the transaction
  commerce_payflow_link_redirect_form_submit($order, $method_instance);

  // Returns true for a successful order
  if (commerce_checkout_complete_access($order)) {
    // Sustainers will not know if this is a recurring donation at this point so we need to reset that
    $submission =  fundraiser_webform_get_submission($donation->sid);

    if (empty($donation->donation['recurs_monthly'])
     && !empty($submission['recurs_monthly']['value'][0])
     && $submission['recurs_monthly']['value'][0] == 'recurs') {
      $donation->donation['recurs_monthly'] = TRUE;
    }

    // Since the processing happens off site we set the payment fields here
    $dates = str_split($_POST['EXPDATE'], 2);
    $year = date_create_from_format('y', $dates[1]);
    $donation->donation['payment_fields']['credit']['card_expiration_month'] = $dates[0];
    $donation->donation['payment_fields']['credit']['card_expiration_year'] = $year->format('Y');
    $donation->donation['payment_fields']['credit']['card_number'] = $_POST['ACCT'];

    // Set the pnref value to support reference transactions
    $donation->data['payflow_pnref'] = _fundraiser_commerce_payflow_transaction_pnref($donation->did);

    return TRUE;
  }
}

/**
 * Return the fields for the donation form
 */
function _fundraiser_commerce_payflow_cc_submit_form($payment_method, $config = NULL) {
  module_load_include('inc', 'fundraiser_commerce', 'includes/fundraiser_commerce.credit_card');
  return _fundraiser_commerce_credit_card_form();
}

/**
 * Charge the donation
 */
function _fundraiser_commerce_payflow_cc_charge($method_instance, $donation) {
  // For reference charges use our custom function
  if ($donation->reference_charge == TRUE) {
    return _fundraiser_commerce_payflow_reference_charge($donation);
  }

  module_load_include('inc', 'fundraiser_commerce', 'includes/fundraiser_commerce.credit_card');

  $order = commerce_order_load($donation->did);
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $charge = $order_wrapper->commerce_order_total->value();

  $pane_form = array(); // Not actually used anywhere in this system, so ignore it.

  $pane_values = _fundraiser_commerce_credit_card_pane_values($donation);

  // Add fundraiser commerce data to the pane values array
  _fundraiser_commerce_submit_handler_pane_values($pane_values, $donation);

  // Execute the payflow cc submit handler
  $result = fundraiser_commerce_payflow_cc_submit_form_submit($method_instance, $pane_form, $pane_values, $order, $charge);
  $success = FALSE;
  if ($result !== FALSE) {
    $success = TRUE;
  }

  // Payflow doesn't currently integrate with card on file so unset this
  unset($pane_values['credit_card']['cardonfile_store']);

  // Set the pnref value to support reference transactions
  $donation->data['payflow_pnref'] = _fundraiser_commerce_payflow_transaction_pnref($donation->did);

  // Perform post processing functions
  _fundraiser_commerce_charge_submit_form_process($success, $method_instance, $pane_values, $donation);

  return $success;
}

/**
 * Clean up the submission results after submission before they are returned to fundraiser.
 */
function _fundraiser_commerce_payflow_cc_cleanup($submission_fields) {
  module_load_include('inc', 'fundraiser_commerce', 'includes/fundraiser_commerce.credit_card');
  return _fundraiser_commerce_credit_card_cleanup($submission_fields);
}

/**
 * Scrub the data before saving.
 */
function _fundraiser_commerce_payflow_cc_scrub($submission_fields) {
  module_load_include('inc', 'fundraiser_commerce', 'includes/fundraiser_commerce.credit_card');
  return _fundraiser_commerce_credit_card_scrub($submission_fields);
}

/**
 * Validate the submitted values with the fundriaser commerce validate function
 */
function _fundraiser_commerce_payflow_cc_validate($submission_fields, $payment_fields) {
  module_load_include('inc', 'fundraiser_commerce', 'includes/fundraiser_commerce.credit_card');
  $form_parents = array_merge($payment_fields['#parents'], array('credit'));
  _fundraiser_commerce_credit_card_validate($submission_fields, $form_parents);
  return $submission_fields;
}

/**
 * Implements hook_commerce_payflow_api_request_alter
 */
function fundraiser_commerce_payflow_commerce_payflow_api_request_alter(&$nvp, $order, $payment_method) {
  // If this request is for a form and is a fundraiser donation then change some of the values
  if (!empty($nvp['RETURNURL']) && $donation = fundraiser_donation_get_donation($order->order_id)) {
    $node = $donation->node;
    $redirect_key = $order->data['payment_redirect_key'];
    $options = array('absolute' => TRUE);
    $nvp['RETURNURL'] = url('node/' . $donation->nid . '/fundraiser-return/' . $donation->did . '/' . $redirect_key, $options);
    $nvp['CANCELURL'] = url('node/' . $donation->nid . '/fundraiser-cancel/' . $donation->did . '/' . $redirect_key, $options);
    $nvp['ERRORURL'] = url('node/' . $donation->nid, $options);
  }
}

/**
 * Callback function, scrub the data before saving.
 */
function _fundraiser_commerce_payflow_expire($submission_fields) {
  module_load_include('inc', 'fundraiser_commerce', 'includes/fundraiser_commerce.credit_card');
  return _fundraiser_commerce_credit_card_expire($submission_fields);
}

/**
 * Process a reference transaction via Payflow Pro.
 */
function _fundraiser_commerce_payflow_reference_charge($donation) {
  $master = fundraiser_donation_get_donation($donation->recurring->master_did);
  $method_instance = $donation->gateway['gateway_details'];
  $order = commerce_order_load($donation->did);

  // Pull the pnref from the master donation
  if (!empty($master->data['payflow_pnref'])) {
    $orig_id = $master->data['payflow_pnref'];
  }
  else {
    // If the PNREF is empty try the remote id
    $orig_id = $master->data['remote_id'];
  }

  // Prepare a name-value pair array to capture the requested amount.
  $nvp = array(
    'BUTTONSOURCE' => !empty($method_instance['buttonsource']) ? $method_instance['buttonsource'] : '',
    'TRXTYPE' => 'S',
    'ORIGID' => $orig_id,
    'AMT' => $donation->amount,
    'TENDER' => 'C',
  );

  // Submit the reference transaction request to Payflow Pro.
  $response = commerce_payflow_api_request($method_instance, 'pro', $nvp, $order);

  // Create a new transaction to represent the reference transaction.
  $transaction = commerce_payment_transaction_new($method_instance['method_id'], $order->order_id);
  $transaction->instance_id = $method_instance['instance_id'];
  $transaction->amount = commerce_currency_decimal_to_amount($donation->amount, $donation->currency);
  $transaction->currency_code = $donation->currency;
  $transaction->payload[REQUEST_TIME] = $response;
  $transaction->remote_id = $response['PNREF'];
  $transaction->data['commerce_payflow']['pnref'] = $response['PNREF'];

  if (!empty($response['PAYMENTSTATUS'])) {
    $transaction->remote_status = commerce_payflow_paypal_remote_status($response['PAYMENTSTATUS']);
  }

  // Build the response message.
  $message = array(
    '<b>Response: @response</b>',
  );

  $transaction->message_variables = array(
    '@response' => $response['RESPMSG'],
    '@origid' => $orig_id,
  );

  if (isset($response['RESULT']) && intval($response['RESULT']) === 0) {
    $message[] = 'Reference transaction ID: @origid';
    $message[] = 'Authcode: @authcode';
    $transaction->message_variables['@authcode'] = $response['AUTHCODE'];

    // Add the PayPal billing agreement ID and fees if given.
    if (!empty($response['BAID'])) {
      $message[] = 'Billing agreement ID: @baid';
      $transaction->message_variables['@baid'] = $response['BAID'];
    }

    if (!empty($response['FEEAMT'])) {
      $message[] = 'PayPal fees: @feeamt';
      $transaction->message_variables['@feeamt'] = $response['FEEAMT'];
    }

    //Save this transactions PNREF back to the master donation
    $master->data['payflow_pnref'] = $response['PNREF'];
    fundraiser_donation_update($master);

    $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
    $success = TRUE;
  }
  else {
    // Display an error message but leave the transaction pending.
    $message[] = 'Failed reference transaction from @origid.';
    $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
    $success = FALSE;
  }

  // Save the transaction and return the success value
  $transaction->message = implode('<br />', $message);
  commerce_payment_transaction_save($transaction);
  return $success;
}

/**
 * Submit handler: process a refund via Payflow Pro.
 */
function _fundraiser_commerce_payflow_refund($method_instance, $refund) {
  $donation = fundraiser_donation_get_donation($refund->did);
  $method_instance = $donation->gateway['gateway_details'];
  $order = commerce_order_load($donation->did);

  // Prepare a name-value pair array to capture the requested amount.
  $nvp = array(
    'TRXTYPE' => 'C',
    'ORIGID' => $donation->data['remote_id'],
    'AMT' => $refund->amount,
  );

  // Submit the refund request to Payflow Pro.
  $response = commerce_payflow_api_request($method_instance, 'pro', $nvp, $order);

  // If the credit succeeded...
  if (intval($response['RESULT']) === 0) {
    $credit_amount = commerce_currency_decimal_to_amount($refund->amount, $donation->currency);
    drupal_set_message(t('Refund for @amount issued successfully.', array('@amount' => commerce_currency_format($credit_amount, $donation->currency))));

    // Create a new transaction to record the credit.
    $credit_transaction = commerce_payment_transaction_new($method_instance['method_id'], $order->order_id);
    $credit_transaction->instance_id = $method_instance['instance_id'];
    $credit_transaction->remote_id = $response['PNREF'];
    $credit_transaction->amount = $credit_amount * -1;
    $credit_transaction->currency_code = $donation->currency;
    $credit_transaction->payload[REQUEST_TIME] = $response;
    $credit_transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
    $credit_transaction->remote_status = 'C';
    $credit_transaction->message = t('Refunded to @remote_id.', array('@remote_id' => $donation->data['remote_id']));

    // Save the credit transaction.
    commerce_payment_transaction_save($credit_transaction);
    return TRUE;
  }
  else {
    // Display a failure message and response reason from Payflow.
    drupal_set_message(t('Refund failed: @reason', array('@reason' => $response['RESPMSG'])), 'error');
    return FALSE;
  }
}

/**
 * Retrieve the pnref value from the order's transaction
 *
 * @param $order_id Numeric
 *    The commerce order id to load the transaction
 */
function _fundraiser_commerce_payflow_transaction_pnref($order_id) {
  // Query the db the latest transaction for the order id
  $data = db_select('commerce_payment_transaction', 't')
    ->fields('t', array('data'))
    ->condition('t.order_id', $order_id, '=')
    ->orderBy('transaction_id', 'DESC')
    ->range(0, 1)
    ->execute()
    ->fetchField();

  if (!empty($data)) {
    $data = unserialize($data);
    return !empty($data['commerce_payflow']['pnref']) ? $data['commerce_payflow']['pnref'] : FALSE;
  }
}
