<?php

/**
 * @file
 * Module file for fundraiser_quick_donate_autopopulate.
 */

/**
 * Implements hook_permission().
 */
function fundraiser_quick_donate_autopopulate_permission() {
  return array(
    'autopopulate quickdonation' => array(
      'title' => t('Autopopulate quick donation test data'),
      'description' => t('Allows for automatically populating donation fields with test data to speed up testing time'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function fundraiser_quick_donate_autopopulate_form_alter(&$form, &$form_state, $form_id) {
  if (!isset($form['#node']) || !user_access('autopopulate quickdonation') || strpos($form_id, 'webform_client_form') === FALSE) {
    return;
  }

  $node = $form['#node'];
  if (fundraiser_is_donation_type($node->type)) {
    $autocomplete = array(
      '#type' => 'button',
      '#value' => t('Automatically populate fields with test information.'),
      '#weight' => -1000,
      '#id' => 'fundraiser_quick_donate_autopopulate',
    );
    $autocomplete = drupal_render($autocomplete);
    if (isset($form['#prefix'])) {
      $form['#prefix'] = $autocomplete + $form['#prefix'];
    }
    else {
      $form['#prefix'] = $autocomplete;
    }
    $form['#attached']['js'][] = drupal_get_path('module', 'fundraiser_quick_donate_autopopulate') . '/js/fundraiser_quick_donate_autopopulate.js';
  }
}
