filter:
    paths:
        - '*.php'
        - '*.module'
        - '*.install'
        - '*.inc'
        - '*.profile'
        - '*.test'
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'
tools:
    js_hint: true
    php_mess_detector:
        extensions:
            - php
            - module
            - install
            - inc
            - profile
            - test
        filter:
            excluded_paths: ['vendor/*', 'app/*', 'web/*']
        config:
            code_size_rules:
                cyclomatic_complexity:  true
                npath_complexity:     true
                excessive_method_length:  true
                excessive_class_length:  true
                excessive_parameter_list:  true
                excessive_public_count:  true
                too_many_fields:      true
                too_many_methods:     true
                excessive_class_complexity:  true
            design_rules:
                exit_expression:      true
                eval_expression:      true
                goto_statement:       true
                number_of_class_children:  true
                depth_of_inheritance:  true
                coupling_between_objects:  true
            unused_code_rules:
                unused_private_field:  true
                unused_local_variable:  true
                unused_private_method:  true
                unused_formal_parameter:  false
            naming_rules:
                short_variable:
                    minimum:              3
                long_variable:
                    maximum:              30
                short_method:
                    minimum:              3
                constructor_conflict:  true
                constant_naming:      true
                boolean_method_name:  true
            controversial_rules:
                superglobals:         false
                camel_case_class_name:  false
                camel_case_property_name:  false
                camel_case_method_name:  false
                camel_case_parameter_name:  false
                camel_case_variable_name:  false
    php_code_sniffer:
        enabled: true
        extensions:
            - php
            - module
            - install
            - inc
            - profile
            - test
        filter:
            excluded_paths: ['vendor/*', 'app/*', 'web/*']
        config:
            tab_width: '2'
            encoding: utf8
            standard: Drupal

    php_loc:
        names:
            - '*.php'
            - '*.module'
            - '*.install'
            - '*.inc'
            - '*.profile'
            - '*.test'
    php_pdepend:
        suffixes:
            - php
            - module
            - install
            - inc
            - profile
            - test
    php_sim: true
    php_changetracking: true
    php_analyzer:
        enabled: true
        extensions:
        - php
        - module
        - install
        - inc
        - profile
        - test
    sensiolabs_security_checker: false

    # Runs the PHP CS Fixer (http://cs.sensiolabs.org/).
    php_cs_fixer:
        extensions:
            - php
            - module
            - install
            - inc
            - profile
            - test
        filter:
            excluded_paths: ['vendor/*', 'app/*', 'web/*']
        config:
            level:                custom # Allowed Values: "psr0", "psr1", "psr2", "all", "custom"
            fixers:
                indentation:          false
                linefeed:             true # All PHP files must use the Unix LF (linefeed) line ending.
                trailing_spaces:      true # Remove trailing whitespace at the end of lines.
                unused_use:           false
                phpdoc_params:        false
                visibility:           false
                return:               false
                short_tag:            true # PHP code must use the long <?php ?> tags or the short-echo <?= ?> tags; it must not use the other tag variations.
                braces:               false
                include:              true # Include and file path should be divided with a single space. File path should not be placed under brackets.
                php_closing_tag:      true # The closing ?> tag MUST be omitted from files containing only PHP.
                extra_empty_lines:    false
                controls_spaces:      true # A single space should be between: the closing brace and the control, the control and the opening parentheses, the closing parentheses and the opening brace.
                elseif:               true # The keyword elseif should be used instead of else if so that all control keywords looks like single words.
                eof_ending:           true # A file must always end with an empty line feed.

checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        uppercase_constants: true
        uppercase_basic_constants: true
        too_many_arguments: true
        switch_fallthrough_commented: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        side_effects_or_types: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        require_braces_around_control_structures: true
        remove_extra_empty_lines: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        property_assignments: true
        prefer_while_loop_over_for_loop: true
        prefer_unix_line_ending: true
        prefer_sapi_constant: true
        php5_style_constructor: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_function_call_in_for_loop: true
        no_unnecessary_final_modifier: true
        no_trailing_whitespace: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_short_variable_names:
            minimum: '3'
        no_short_open_tag: true
        no_mixed_inline_html: true
        no_long_variable_names:
            maximum: '30'
        no_goto: true
        no_error_suppression: true
        no_eval: true
        no_exit: true
        no_empty_statements: true
        no_else_if_statements: true
        no_duplicate_arguments: true
        no_debug_code: true
        no_commented_out_code: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        lowercase_php_keywords: true
        instanceof_class_exists: true
        function_body_start_on_same_line: true
        foreach_traversable: true
        fix_doc_comments: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        ensure_lower_case_builtin_functions: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        catch_class_exists: true
        blank_line_after_namespace_declaration: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_tab_indentation: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_aliased_php_functions: true
        argument_type_checks: true
