<?php

/**
 * Implements hook_menu
 *
 * Don't know what the final menu structure will be.
 * This is provisional.
 */

function springboard_target_menu() {
  $items = array();

 // Moved this config to advocacy module, but may use later/
 // $items['admin/config/springboard/advocacy/target'] = array(
 //   'title' => 'Target Config',
 //   'description' => '',
 //   'access arguments' => array('administer site configuration'),
 //   'page arguments' => array('springboard_target_admin'),
 //   'page callback' => 'drupal_get_form',
 //   'file' => 'includes/springboard_target.admin.inc',
 //   'weight' => 10,
 //   'type' => MENU_LOCAL_TASK,
 // );

  $items['admin/springboard/advocacy/custom-targets/add'] = array(
    'title' => 'Target Center: Create Targets',
    'description' => '',
    'access arguments' => array('create targets'),
    'page arguments' => array('springboard_target_create_custom_targets_form'),
    'page callback' => 'drupal_get_form',
    'file' => 'includes/springboard_target.custom_targets_create.inc',
  );

  $items['admin/springboard/advocacy/custom-targets/%/edit'] = array(
    'title' => 'Target Center: Edit Target',
    'description' => '',
    'access arguments' => array('edit targets'),
    'page arguments' => array('springboard_target_edit_custom_targets_form', 4),
    'page callback' => 'drupal_get_form',
    'file' => 'includes/springboard_target.custom_targets_edit.inc',
  );

  $items['apitest'] = array(
    'title' => 'Get test the legislator lookup',
    'description' => '',
    'type' => MENU_CALLBACK,
    'page callback' => '_springboard_target_api_test',
    'file' => 'includes/springboard_target.api_test.inc',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_permissions
 *
 */
function springboard_target_permission() {
  return array(
    'administer targets' => array(
      'title' => t('Administer Targets'),
      'description' => t('Perform administration tasks for my targets.'),
    ),
    'view targets' => array(
      'title' => t('View Targets'),
      'description' => t('View Custom targets.'),
    ),
    'create targets' => array(
      'title' => t('Create Targets'),
      'description' => t('Create Custom targets.'),
    ),
    'edit targets' => array(
      'title' => t('Edit Targets'),
      'description' => t('Edit Custom my targets.'),
    ),
    'delete targets' => array(
      'title' => t('Delete Targets'),
      'description' => t(' Custom targets.'),
    ),
    'add target to campaign' => array(
      'title' => t('Add target to campaign.'),
      'description' => t('Add target to campaign.'),
    ),
  );
}
