<?php

/**
 * @file
 * Ubercart based hook implementations for the fundraiser module donations.
 */

/**
 * Implemenation of hook_mail_alter().
 */
function fundraiser_ubercart_mail_alter(&$message) {
  // Catch for mail coming out of UC.
  if ($message['id'] == 'uc_order_action-mail') {
    // Gather data.
    $parts = explode("/", $_GET['q']);
    $nid = $parts[1];
    $node = node_load($nid);
    // Make changes.
    $message['headers']['From'] = $headers['Sender'] = $headers['Return-Path'] = $headers['Errors-To'] = $node->receipt_email_from . ' <' . $node->receipt_email_address . '>';
    $bcc = variable_get('fundraiser_receipt_bcc', '');
    if (!empty($bcc)) {
      $message['headers']['Bcc'] = $bcc;
    }
    $message['from'] = $node->receipt_email_from . ' <' . $node->receipt_email_address . '>';
    $message['subject'] = $node->receipt_email_subject;
  }
}

/**
 * Implementation of hook_order_actions() from Ubercart.
 * Add a refund option to the Order list.
 * From http://drupalcontrib.org/api/drupal/contributions!ubercart!docs!hooks.php/function/hook_order_actions/6
 */
function fundraiser_order_actions($order) {
  $gateway = _fundraiser_get_donation_gateway($order->order_id);
  $can_refund = isset($gateway['credit_refund']) ? $gateway['credit_refund'] : NULL;
  if (user_access('edit orders') && 
    (in_array($order->order_status, array('payment_received', 'partially_refunded')) || empty($order->order_status)) && $can_refund) {  
    $module_path = base_path() . drupal_get_path('module', 'fundraiser');
    $title = t('Issue refund on order !order_id.', array('!order_id' => $order->order_id));
    $actions[] = array(
      'name' => t('Refund'),
      'url' => 'admin/store/orders/' . $order->order_id . '/refund',
      'icon' => '<img src="' . $module_path . '/images/refund.gif" alt="' . $title . '" />',
      'title' => $title,
    );
    return $actions;
  }
}

/**
 * Implementation of hook_order().
 * From http://www.ubercart.org/docs/api/hook_order
 * When an order is deleted, keep fundraiser tables in sync.
 */
function fundraiser_order($op, &$arg1, $arg2) {
  switch ($op) {
    case 'delete':
      _fundraiser_delete_recurring($arg1->order_id); //TODO follow up on this. To remove or rename.
      break;
  }
}

/**
 * Implementation of hook_preprocess_uc_order().
 * From: http://www.ubercart.org/forum/development/18047/inserting_variables_invoices_ubercart_23_and_above
 * Adds additional variables for use in donation receipt emails sent by UC.
 */
function fundraiser_preprocess_uc_order(&$variables) {
  switch ($variables['op']) {
    case 'checkout-mail':
      $nid = $variables['order']->products[0]->nid;
      $fundraiser = _fundraiser_get_fundraiser_by_nid($nid);
      $variables['fundraiser_message'] = $fundraiser->receipt_email_message;
      break;
  }
}

/**
 * Implements hook_fundraiser_gateway_info().
 */
function fundraiser_ubercart_fundraiser_gateway_info() {
  // If no gateways are enabled, this returns an empty array.
  // TODO - make sure where this is accounted for an emtpy is noted, and flagged as a thing to fix. - SeH
  // From Ubsercart http://api.lullabot.com/_uc_payment_gateway_list/7
  // Is ultimately configured by http://api.lullabot.com/hook_uc_payment_gateway
  // Returns in the format:
  // $gateway = array('id', 'title', 'credit', 'credit_refund', 'etc');
  // TODO check that this is the format we want and we don't want to transform it to something else.
  return _uc_payment_gateway_list('', TRUE);
}

/**
 * Implements hook_fundraiser_donation_form_context().
 *
 * Returns context information to fundraiser to be used in other modules as needed for
 * form generation. In this case an array of information about countries and zones.
 */
function fundraiser_ubercart_fundraiser_donation_form_context($context) {
  $countries = array();
  $zones = array();
  // Gather an array of countries.
  $results = db_query('SELECT * FROM {uc_countries}');
  foreach ($results as $result) {
    // First load up id, name, iso code 2, iso code 3, and version from Ubercart.
    $countries[$result->country_id] = $result;
    $countries[$result->country_id]->zones = array();
    $zone_results = db_query('SELECT * FROM {uc_zones} WHERE zone_country_id = :zone_country_id',
      array(':zone_country_id' => $result->country_id));
    foreach ($zone_results as $zone_result) {
      // For each zone load up, zone_id, zone country_id, zone, code, zone_name.
      // Store in the country and zone arrays.
      $countries[$result->country_id]->zones[$zone_result->zone_id] = $zone_result;
      $zones[$zone_result->zone_id] = $zone_result;
    }
  }
  $context->countries = $countries;
  $context->zones = $zones;
  return $context;
}

/**
 * Implements hook_fundraiser_donation_create().
 */
function fundraiser_ubercart_fundraiser_donation_create($donation) {
  $user = $donation->user;
  $node = $donation->node;
  $fundraiser_fields = $donation->submission;
  $additional_fields = isset($donation->additional) ? $donation->additional : array();

  // Generate an order given the values submitted, and return an order_id.
  // Fundraiser uses the concept of an order (as per ubercart).
  // So any hook creating an order should keep that in mind.

  // Pick out the values we need to generate an order.
  $donation_amount = $fundraiser_fields['amount'];
  $cc_number = $fundraiser_fields['card_number'];
  $cc_cvv = $fundraiser_fields['card_cvv'];
  $cc_expiration_month = $fundraiser_fields['card_expiration_month'];
  $cc_expiration_year = $fundraiser_fields['card_expiration_year'];
  $first_name = $fundraiser_fields['first_name'];
  $last_name = $fundraiser_fields['last_name'];
  $email = $fundraiser_fields['email'];
  $billing_address = $fundraiser_fields['address'];
  $billing_address_2 = $fundraiser_fields['address_line_2'];
  $billing_city = $fundraiser_fields['city'];
  $billing_country = $fundraiser_fields['country'];
  $billing_state = $fundraiser_fields['state'];
  $billing_zipcode = $fundraiser_fields['zip'];
  $quantity = isset($fundraiser_fields['quantity']) && !empty($fundraiser_fields['quantity']) ? $fundraiser_fields['quantity'] : 1;

  // Look for other amount if set.
  if ($donation_amount == "other") {
    $donation_amount = preg_replace("/[^\d\.]/i", "", $fundraiser_fields['other_amount']);
  }

  // Create a UC order.
  $order = uc_order_new($user->uid);
  $product = uc_product_load(array($node->nid => $node));
  $order->products[0] = $product;
  $order->products[0]->price = $donation_amount;
  $order->products[0]->qty = $quantity;
  $order->products[0]->title = $node->title;
  $order->products[0]->nid = $node->nid;
  $order->products[0]->data = array(
    'shippable' => isset($order->products[0]->shippable) ? $order->products[0]->shippable : FALSE,
    'model' => isset($order->products[0]->model) ? $order->products[0]->model : '',
    'varprice' => $donation_amount,
    'module' => 'uc_product',
  );

  // Multiply amount by quantity if available.
  if (!empty($quantity)) {
    $donation_amount = $donation_amount * $quantity;
  }

  // Set order properties.
  $order->primary_email = $email;
  $order->order_total = $donation_amount;
  $order->billing_first_name = $first_name;
  $order->billing_last_name = $last_name;
  $order->billing_city = $billing_city;
  $order->billing_street1 = $billing_address;
  $order->billing_street2 = $billing_address_2;
  $order->billing_postal_code = $billing_zipcode;
  $order->billing_zone = $billing_state;
  $order->billing_country = $billing_country;
  $order->payment_method = 'credit';
  $order->payment_details = array(
    'cc_type' => _fundraiser_ubercart_get_cc_type($cc_number),
    'cc_owner' => '',
    'cc_number' => $cc_number,
    'cc_start_month' => '',
    'cc_start_year' => '',
    'cc_exp_month' => $cc_expiration_month,
    'cc_exp_year' => $cc_expiration_year,
    'cc_issue' => '',
    'cc_cvv' => $cc_cvv,
    'cc_bank' => '',
  );
  $order->line_items = array();
  foreach ($additional_fields as $field => $value) {
    $order->data[$field] = $value;
  }
  // If using the gateway manager, store the gateway that was used to make the payment
  if (module_exists('gateway_manager')) {
    $order->data['gateway'] = $node->gateway;
  }
  // Cache the cc details stored by the handler.
  uc_credit_cache('save', $order->payment_details, FALSE);
  // Save the order.
  uc_order_save($order);
  // And add the data to the donation form to return it.
  $donation->donation = $order;  //TODO formalize this return array so we have a standard in/out.
  $donation->donation->did = $order->order_id;
  $donation->donation->donation_amount = $order->order_total;
}

/**
 * Implements hook_fundraiser_donation_get_donation().
 */
function fundraiser_ubercart_fundraiser_donation_get_donation($donation) {
  // Load order specific information for donation.
  $order = uc_order_load($donation->donation->did);
  $donation->donation = $order;
  $donation->donation->donation_amount = $order->order_total;
  $ref_id = '';
  if (isset($order->data['cc_txns']['references'])) {
    $ref_id = array_shift(array_keys($order->data['cc_txns']['references']));
  }
  $data = array(
    'txn_type' => 'reference_txn',
    'ref_id' => $ref_id,
  );
  $donation->donation->data = array_merge($donation->donation->data, $data);
}

/**
 * Implements hook_fundraiser_donation_success().
 */
function fundraiser_ubercart_fundraiser_donation_success($donation) {
  // Complete the sale in Ubercart.
  $order = uc_order_load($donation->donation->did);
  uc_cart_complete_sale($order, variable_get('uc_new_customer_login', FALSE));
  uc_payment_enter($order->order_id, 'fundraiser', $donation->donation->order_total, 0, NULL, 
    t('Payment processed by the fundraiser module.'));
// TODO move this to a db func.
  db_query("UPDATE {uc_orders} SET order_status = 'payment_received' WHERE order_id = :order_id",
    array(':order_id' => $donation->donation->did));
  // And done.
}

/**
 * Implements hook_fundraiser_donation_decline().
 */
function fundraiser_ubercart_fundraiser_donation_decline($donation) {
  // Mark the sale in Ubercart as failed.
//TODO move to db func.
  db_query("UPDATE {uc_orders} SET order_status = 'failed' WHERE order_id = :order_id", array(':order_id' => $donation->donation->did));
  // Clear the credit card cache between orders
  uc_credit_cache('clear');
}

/**
 * Implements hook_fundraiser_donation_exception().
 */
function fundraiser_ubercart_fundraiser_donation_exception($donation) {
  return fundraiser_ubercart_fundraiser_donation_decline($donation);
}

/**
 * Implements hook_fundraiser_donation_cancel().
 */
function fundraiser_ubercart_fundraiser_donation_cancel($donation) {
  // Mark the sale in Ubercart as cencelled.
//TODO move to db func.
  db_query("UPDATE {uc_orders} SET order_status = 'canceled' WHERE order_id = :order_id", array(':order_id' => $donation->donation->did));
  // Make a comment on the order.
  uc_order_comment_save($donation->donation->did, 0, t('Payment was canceled during checkout by the user.'));
}

/** 
 * Helper function, given a card number return likely type.
 */
function _fundraiser_ubercart_get_cc_type($cardnumber) {
  $cardtype = "UNKNOWN";
  $len = strlen($cardnumber);
  if ( $len == 15 && substr($cardnumber, 0, 1) == '3' ) {
    $cardtype = "amex";
  }
  elseif ( $len == 16 && substr($cardnumber, 0, 4) == '6011' ) {
    $cardtype = "discover";
  }
  elseif ( $len == 16 && substr($cardnumber, 0, 1) == '5' ) {
    $cardtype = "mc";
  }
  elseif ( ($len == 16 || $len == 13) && substr($cardnumber, 0, 1) == '4' ) {
    $cardtype = "visa";
  }
  return ( $cardtype );
}

/**
 * Below here are orphan or unknown origin functions. To be reviewed later.
 */

/**
 * Sage billing information update function.
 */
// TODO shouldn't this move elsewhere?
function sage_update_billing_information($reference_id, $billing_info) {
  // TODO hook here to load up order info. - SeH 
  $vault_id = db_query("SELECT vault_id from {uc_sage_vault} WHERE guid = :guid", array(':guid' => $reference_id))->fetchColumn();
  $data = array(
    'billing_name' => $billing_info['first_name'] . ' ' . $billing_info['last_name'],
    'billing_street1' => $billing_info['address_1'],
    'billing_street2' => $billing_info['address_2'],
    'billing_city' => $billing_info['city'],
    'billing_zone' => $billing_info['state'],
    'billing_postal_code' => $billing_info['zipcode'],
    'billing_country' => $billing_info['country'],
    'cc_number' => $billing_info['card_num'],
    'cc_exp_month' => sprintf("%02d", $billing_info['card_exp_date']['month']),
    'cc_exp_year' => $billing_info['card_exp_date']['year'],
  );
  $response = uc_sage_vault_update($vault_id, $data);
  // TODO: Need to add some better returns to the uc_sage module
  return TRUE;
}


/**
 * Implements hook_fundraiser_get_credit_encryption_path(). //TODO where is this called?
 */
function fundraiser_ubercart_fundraiser_get_credit_encryption_path() {
  return variable_get('uc_credit_encryption_path', t('Not configured, see below.'));
}

/**
 * Implements hook_fundraiser_decrypt_credit(). //TODO where is this called?
 */
function fundraiser_ubercart_fundraiser_decrypt_credit($data) {
  $key = uc_credit_encryption_key();
  $crypt = new uc_encryption_class;
  $cc = unserialize($data);
  $cc_data = unserialize($crypt->decrypt($key, $cc['cc_data']));
  $cc_data['cc_number'] = substr($cc_data['cc_number'], -4);
  return $cc_data;
}

/**
 * Implements hook_fundraiser_validate_card(). //TODO where is this called?
 */
function fundraiser_ubercart_fundraiser_validate_card($cc_number){
  if(variable_get('uc_credit_validate_numbers', TRUE)) {
    return _uc_credit_valid_card_number($cc_number);
  }
  return FALSE;
}

/**
 * Implements hook_fundraiser_validate_card_expiration(). //TODO where is this called?
 */
function fundraiser_ubercart_fundraiser_validate_card_expiration($cc_expiration_month, $cc_expiration_year){
  return _uc_credit_valid_card_expiration($cc_expiration_month, $cc_expiration_year);
}


/**
 * Implements hook_fundraiser_validate_card_cvv(). //TODO where is this called?
 */
function fundraiser_ubercart_fundraiser_validate_card_cvv($cc_cvv){
  if (variable_get('uc_credit_cvv_enabled', TRUE)) {
    return _uc_credit_valid_cvv($cc_cvv);
  }
  return FALSE;
}

// Theme / formaty code, really should get refactored at some point. -SeH

/**
 * Implements hook_fundraiser_format_price().//tODO where is this called?
 */
function fundraiser_ubercart_fundraiser_format_price($price) {
  return theme('uc_price', array('price' => $price));
}
