<?php

/*
 *  Menu/config hooks and Common functions used by multiple message types will go here
 */


function springboard_messages_node_insert($node) {
  $types = variable_get('springboard_advocacy_message_types', array());
  if(in_array($node->type, $types)) {
    $uuid = array(
      'nid' => $node->nid,
      'advocacy_id' => uniqid(variable_get('site_name', 'Drupal') . '-'),
    );
    drupal_write_record('springboard_messages_form_id', $uuid);
  }
}

function springboard_messages_node_load($nodes, $types) {
  $message_types = variable_get('springboard_advocacy_message_types', array());
  if (count(array_intersect($message_types, $types))) {  
     $result = db_query(
      'SELECT advocacy_id, nid FROM {springboard_messages_form_id} WHERE nid IN (:nids)', 
       array(':nids' => array_keys($nodes)));
    foreach ($result as $record) {
      $nodes[$record->nid]->advocacy_id = $record->advocacy_id;
    }
  }
}