<?php

/**
 * @file
 * Provides a way to track which campaigns and market sources drive users to the
 * site.
 */

/**
 * Implementation of hook_install().
 */
function market_source_install() {
  // Default to six hours
  variable_set('market_source_validity_period', 6);
}

/**
 * Implementation of hook_uninstall().
 */
function market_source_uninstall() {
  variable_del('market_source_validity_period');
}


