<?php

/**
 * @file
 * Install market_source.
 */

/**
 * Implements hook_install().
 */
function market_source_install() {
  // Default to six hours
  variable_set('market_source_validity_period', 6);
}

/**
 * Implements hook_uninstall().
 */
function market_source_uninstall() {
  variable_del('market_source_validity_period');
}

/**
 * Implements hook_update_last_removed().
 */
function market_source_update_last_removed() {
  return 6001;
}