<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

function fundraiser_designations_schema() {
  $schema = array();


  return $schema;
}

/**
 *  Add addon table
 */
function fundraiser_designations_update_7003() {
  $schema = module_invoke('fundraiser_designations', 'schema');
  if (db_table_exists('fundraiser_designations_overrides') == FALSE) {
    db_create_table('fundraiser_designations_overrides', $schema['fundraiser_designations_overrides']);
  }
}
