<?php

/**
 * @file
 * Fundraiser Easy Edit provides inline editing for Donation forms
 */
 
/**
 * Implements hook_fundraiser_donation_form().
 */ 
function fundraiser_easy_edit_fundraiser_donation_form($form, $form_state) {
  // TODO: minify
  $form['#after_build'][] = 'fundraiser_easy_edit_donation_form_after_build';
  return $form;
}

/**
 * Donation form afterbuild, for CSS and JS.
 */
function fundraiser_easy_edit_donation_form_after_build($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'fundraiser_easy_edit') . '/js/underscore.js');
  drupal_add_js(drupal_get_path('module', 'fundraiser_easy_edit') . '/js/backbone.js');
  drupal_add_js(drupal_get_path('module', 'fundraiser_easy_edit') . '/js/backbone.localStorage.js');
  drupal_add_js(drupal_get_path('module', 'fundraiser_easy_edit') . '/js/fundraiser_easy_edit.js');
  return $form;
}

