<?php
// $Id$

/**
 * @file
 * Webform A/B Testing
 *
 * Adds a content type for an A/B test of webforms.
 */

/**
 * @todo
 *  Make sure all fields are being validated
 *  Add JS to enable Win Criteria value textboxes based on the chosen radio
 *  Define hook_view() to show overview of admin settings
 *  Define tabs within the form
 *  Trigger a hook called when one of the forms in the test is submitted
 *  Permissions: declare winner? Start/end test?
 *  Finish reporting tab
 * 
 *  Instead of using a form alter, should other modules implement a hook to define what types of webforms can be included from them (ie, fundraiser_ab, webform_user)
 * Test permission settings
 */

// Active status, for webforms within a test
define('WEBFORM_AB_WEBFORM_STATUS_ACTIVE', 1);
// Win status for webforms within a test - only one webform per test should have this
define('WEBFORM_AB_WEBFORM_STATUS_WINNER', 2);

/**
 * Implementation of hook_node_info().
 */
function webform_ab_node_info() {
  return array(
    'webform_ab' => array(
      'name' => t('Webform A/B Test'),
      'module' => 'webform_ab',
      'description' => t('An A/B test for Webforms'),
      'title_label' => t('Test Name'),
      'body_label' => t('Admin Description'),
      'locked' => TRUE
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function webform_ab_perm() {
  return array(
    'create webform_ab', 
    'edit own webform_ab', 
    'edit any webform_ab', 
    'delete own webform_ab', 
    'delete any webform_ab', 
    'view own webform_ab reports',
    'view any webform_ab reports',
  );
}

/**
 * Implementation of hook_menu().
 */
function webform_ab_menu() {
  $items = array();

  $items['node/%webform_menu_ab/reports'] = array(
    'title' => 'Reports and Monitoring',
    'page callback' => 'webform_ab_test_reports',
    'page arguments' => array(1),
    'access callback' => 'webform_ab_can_view_reports',
    'access arguments' => array(1),
    'file' => 'webform_ab.admin.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['node/%webform_menu_ab/forms'] = array(
    'title' => 'Included Webforms',
    'page callback' => 'webform_ab_test_forms',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'webform_ab.admin.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['node/%webform_menu_ab/forms/remove'] = array(
    'title' => 'Remove Form',
    'page callback' => 'webform_ab_test_remove_form',
    'page arguments' => array(1),    
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'webform_ab.admin.inc',
    'weight' => 3,
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}


/**
 * Check if the current user can view the reports on a given Webform A/B Test
 */
function webform_ab_can_view_reports($node) {
  global $user;
  $is_author = $user->uid == $node->uid;
  
  return (user_access('view own webform_ab reports', $user) && $is_author) || user_access('view any webform_ab reports', $user);
}


/**
 * Menu loader callback. Load a Webform A/B Test node if the given nid is for 
 * the right node type.
 */
function webform_menu_ab_load($nid) {
  if (!is_numeric($nid)) {
    return FALSE;
  }
  $node = node_load($nid);
  if (!isset($node->type) || $node->type != 'webform_ab') {
    return FALSE;
  }
  return $node;
}




function webform_ab_menu_alter(&$items) {
  /**
   * @todo Make sure "create webform_ab" permission is checked for create menu item
   */
}


/**
 * Implementation of hook_access().
 */
function webform_ab_access($op, $node, $account) {
  $is_author = $account->uid == $node->uid;
  
  switch ($op) {
    case 'create':
      return user_access('create webform_ab', $account);
      break;
    
    case 'update':
      return (user_access('edit own webform_ab', $account) && $is_author) || user_access('edit any webform_ab', $account);
      break;
    
    case 'delete':
      return (user_access('delete own webform_ab', $account) && $is_author) || user_access('delete any webform_ab', $account);
      break;
  }
}


/**
 * Implementation of hook_form().
 * Return the form for admins to edit webform_ab nodes
 */
function webform_ab_form(&$node, $form_state) {
  // Add styling for the form
  drupal_add_css(drupal_get_path('module', 'webform_ab') . '/webform_ab.css');
  
  $type = node_get_types('type', $node);
  
  $form['test_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('A/B Test Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  
  $form['test_settings']['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#size' => 40,
    '#maxlength' => 255,
    '#weight' => -5,
    '#default_value' => $node->title
  );
  
  $form['test_settings']['body'] = array(
    '#type' => 'textarea',
    '#title' => check_plain($type->body_label),
    '#default_value' => $node->body,
    '#cols' => 60,
    '#rows' => 5,
    '#description' => t('Description for admin use. This is not displayed to the public.')
  );
  
  $webform_node_type = node_get_types('type', 'webform');
  
  $form['test_settings']['webform_types'] = array(
    '#type' => 'radios',
    '#title' => t('Which types of forms will this test use?'),
    '#description' => t('Once set, this cannot be changed.'),
    '#options' => array('webform' => check_plain($webform_node_type->name)),
    '#default_value' => $node->webform_types,
    '#required' => TRUE,
  );
  
  $form['winning_conditions'] = array(
    '#type' => 'fieldset',
    '#title' => t('Winning Conditions'),
    '#description' => t('Conditions necessary for a form to win the test.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE
  );
  
  $form['winning_conditions']['minimum_hits'] = array(
    '#type' => 'textfield',
    '#title' => t('Minimum Hits'),
    '#description' => t('The form must be seen by this many users before it can be declared the winner. This prevents a winner from being declared before enough data has been collected.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => empty($node->minimum_hits) ? 100 : $node->minimum_hits
  );
  
  
  $form['winning_conditions']['win_type'] = array(
    '#type' => 'item',
    '#title' => t('Win Criteria'),
    '#prefix' => '<div class="win_type_container">',
    '#suffix' => '</div>',
    '#required' => TRUE,
  );
  
  $form['winning_conditions']['win_type']['total_conversions_group'] = array(
    '#prefix' => '<div class="container form-item">',
    '#suffix' => '</div>'
  );
  
  $form['winning_conditions']['win_type']['total_conversions_group']['total_conversions_radio'] = array(
    '#type' => 'radio',
    '#title' => t('Total Conversions'),
    '#description' => t('This many conversions must be made before the form is declared the winner.'),
    '#return_value' => 'total_conversions',
    '#parents' => array('win_type'),
    '#default_value' => $node->win_type,
  );
  
  $form['winning_conditions']['win_type']['total_conversions_group']['total_conversions'] = array(
    '#type' => 'textfield',
    '#title' => t('Number'),
    '#description' => t('Number of conversions'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $node->total_conversions,
  );
  
  $form['winning_conditions']['win_type']['percent_conversions_group'] = array(
    '#prefix' => '<div class="container form-item">',
    '#suffix' => '</div>'
  );
  
  $form['winning_conditions']['win_type']['percent_conversions_group']['percent_conversions_radio'] = array(
    '#type' => 'radio',
    '#title' => t('Conversion Percentage'),
    '#description' => t('Once the percentage of conversions reaches this, and the minimum hits is reached, form is declared the winner.'),
    '#return_value' => 'percent_conversions',
    '#parents' => array('win_type'),
    '#default_value' => $node->win_type,
  );
  
  $form['winning_conditions']['win_type']['percent_conversions_group']['percent_conversions'] = array(
    '#type' => 'textfield',
    '#title' => t('Percentage'),
    '#description' => t('Percentage of hits that become conversions. Enter either as 25% or 0.25.'),
    '#size' => 10,
    '#maxlength' => 255,
    '#default_value' => $node->percent_conversions,
  );
  
  
  $form['notifications'] = array(
    '#type' => 'fieldset',
    '#title' => t('Notifications'),
    '#description' => t('The following options are specific to this test. You can also set default values for future tests in the Webform A/B Test module settings page.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE
  );
  
  $form['notifications']['daily_summaries'] = array(
    '#type' => 'fieldset',
    '#title' => t('Daily Summaries'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  
  $form['notifications']['daily_summaries']['daily_notification_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Send daily reports by email to'),
    '#description' => t('Separate e-mail addresses with a comma.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $node->daily_notification_email,
  );

  $form['notifications']['daily_summaries']['daily_notification_sms'] = array(
    '#type' => 'textfield',
    '#title' => t('Send daily reports by SMS to'),
    '#description' => t('Separate cell phone numbers with a comma.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $node->daily_notification_sms,
  );
  
  
  $form['notifications']['winning_notice'] = array(
    '#type' => 'fieldset',
    '#title' => t('Winning Notice'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  
  $form['notifications']['winning_notice']['win_notification_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Send winning notice by email to'),
    '#description' => t('Separate e-mail addresses with a comma.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $node->win_notification_email,
  );

  $form['notifications']['winning_notice']['win_notification_sms'] = array(
    '#type' => 'textfield',
    '#title' => t('Send winning notice by SMS to'),
    '#description' => t('Separate cell phone numbers with a comma.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $node->win_notification_sms,
  );

  return $form;
}


/**
 * Implementation of hook_validate().
 * Check values from the node edit form
 */
function webform_ab_validate($node, &$form) {
  // Make sure they chose a win criteria
  if (empty($node->win_type)) {
    form_set_error('win_type', t('Please choose a Win Criteria.'));
  }
  else {
    // Based on the chosen win type, find the title of the field
    $field_title = $form['winning_conditions']['win_type'][$node->win_type . '_group'][$node->win_type . '_radio']['#title'];

    // Make sure they entered a value for the win criteria
    if (empty($node->{$node->win_type})) {
      form_set_error($node->win_type, t('You must define a value for %criteria', array('%criteria' => $field_title)));
    }
    else {
      $win_value = trim($node->{$node->win_type});
      
      // Validate value given for a Total Conversions win criteria
      if ($node->win_type == 'total_conversions') {
        if (!($win_value > 0) || !ctype_digit($win_value)) {
          form_set_error($node->win_type, t('You must define an integer value for %criteria', array('%criteria' => $field_title)));
        }
      }
      // Validate value given for a Conversion Percentage win criteria
      elseif ($node->win_type == 'percent_conversions') {
        // If it's between 0 and 1, it's a decimal and OK
        if ($win_value > 0 && $win_value <= 1) {
          // Fine
        }
        // See if the string ends with a percentage
        elseif (substr($win_value, -1) == '%') {
          // Strip the percent sign
          $number = substr($win_value, 0, strlen($win_value) - 1);
          if (!($number > 0 && $number <= 100)) {
            form_set_error($node->win_type, t('Please enter a valid percentage for %criteria. You can either enter it as a percentage (e.g., 45%) or a decimal value (e.g., 0.45).', array('%criteria' => $field_title)));
          }
        }
        // Otherise, failed
        else {
          form_set_error($node->win_type, t('Please enter a valid percentage for %criteria. You can either enter it as a percentage (e.g., 45%) or a decimal value (e.g., 0.45).', array('%criteria' => $field_title)));
        }
      }
    }
  }
  

  // Validate daily summary email address(es)
  if(trim($node->daily_notification_email) != '') {
    $addresses = explode(',', $node->daily_notification_email);
    $invalid = array();
    foreach ($addresses as $address) {
      if (!valid_email_address(trim($address))) {
        $invalid[] = $address;
      }
    }
    if (!empty($invalid)) {
      form_set_error('daily_notification_email', t('Invalid e-mail address(es) given for daily summaries: %email', array('%email' => implode(', ', $invalid))));
    }
  }
  
  // Validate winning notice email address(es)
  if(trim($node->win_notification_email) != '') {
    $addresses = explode(',', $node->win_notification_email);
    $invalid = array();
    foreach ($addresses as $address) {
      if (!valid_email_address(trim($address))) {
        $invalid[] = $address;
      }
    }
    if (!empty($invalid)) {
      form_set_error('win_notification_email', t('Invalid e-mail address(es) given for winning notice: %email', array('%email' => implode(', ', $invalid))));
    }
  }
}


/**
 * Implementation of hook_insert().
 * Save new Webform A/B Test nodes. Just calls webform_ab_update
 */
function webform_ab_insert($node) {
  return webform_ab_update($node, TRUE);
}


/**
 * Implementation of hook_update().
 * Update existing or insert new Webform A/B Test nodes
 */
function webform_ab_update($node, $is_insert = FALSE) {
  _webform_ab_prep_node_for_save($node);
  
  $replacement_values = array(
    $node->nid,
    $node->webform_types,
    $node->minimum_hits,
    $node->win_type,
    $node->{$node->win_type},
    $node->daily_notification_email,
    $node->daily_notification_sms,
    $node->win_notification_email,
    $node->win_notification_sms
  );
  
  if($is_insert) {
    $sql = "INSERT INTO {webform_ab} (nid, webform_types, minimum_hits, win_type, win_value, daily_notification_email, daily_notification_sms, win_notification_email, win_notification_sms) VALUES(%d, '%s', %d, '%s', %f, '%s', '%s', '%s', '%s')";
  }
  else {
    $sql = "UPDATE {webform_ab} SET nid=%d, webform_types='%s', minimum_hits=%d, win_type='%s', win_value=%f, daily_notification_email='%s', daily_notification_sms='%s', win_notification_email='%s', win_notification_sms='%s' WHERE nid=%d";
    $replacement_values[] = $node->nid;
  }
    
  db_query($sql, $replacement_values);
}


/**
 * Clean up fields before saving them to the DB
 */
function _webform_ab_prep_node_for_save(&$node) {
  // Remove any spaces from lists of daily summary e-mail addresses
  if(trim($node->daily_notification_email) != '') {
    $addresses = explode(',', $node->daily_notification_email);
    $fixed = array();
    foreach ($addresses as $address) {
      $fixed[] = trim($address);
    }
    $node->daily_notification_email = implode(',', $fixed);
  }
  
  // Remove any spaces from lists of win notice e-mail addresses
  if(trim($node->win_notification_email) != '') {
    $addresses = explode(',', $node->win_notification_email);
    $fixed = array();
    foreach ($addresses as $address) {
      $fixed[] = trim($address);
    }
    $node->win_notification_email = implode(',', $fixed);
  }
  
  // If the percent_conversions is a decimal less than 1, convert to a full number
  if ($node->percent_conversions > 0 && $node->percent_conversions <= 1) {
    $node->percent_conversions = $node->percent_conversions * 100;
  }
}


/**
 * Implementation of hook_load().
 */
function webform_ab_load(&$node) {
  $load = db_fetch_object(db_query('SELECT * FROM {webform_ab} WHERE nid = %d', $node->nid));
  if (!empty($load->win_type)) {
    $load->{$load->win_type} = $load->win_value;
  }
  
  $result = db_query('SELECT f.webform_nid, f.status, n.title, COUNT(DISTINCT hits.hit_id) as hits, COUNT(DISTINCT con.sid) AS conversions
    FROM {webform_ab_forms} f
    LEFT JOIN {node} n ON n.nid = f.webform_nid
    LEFT JOIN {webform_ab_hits} hits ON hits.test_nid = f.test_nid AND hits.webform_nid = f.webform_nid
    LEFT JOIN  {webform_ab_conversion} con ON con.test_nid = f.test_nid AND con.webform_nid = f.webform_nid
    WHERE f.test_nid = %d
    GROUP BY f.test_nid, f.webform_nid', $node->nid);
  $included_webforms = array();
  while ($row = db_fetch_array($result)) {
    $included_webforms[$row['webform_nid']] = $row;
  }
  
  $load->included_webforms = $included_webforms;
  
  return $load;
}


/**
 * Implementation of hook_delete().
 * Delete all data for a test
 */
function webform_ab_delete(&$node) {
  db_query('DELETE FROM {webform_ab} WHERE nid=%d', array($node->nid));
  db_query('DELETE FROM {webform_ab_conversion} WHERE test_nid=%d', array($node->nid));
  db_query('DELETE FROM {webform_ab_forms} WHERE test_nid=%d', array($node->nid));
  db_query('DELETE FROM {webform_ab_hits} WHERE test_nid=%d', array($node->nid));
}


/**
 * Implementation of hook_view().
 */
function webform_ab_view(&$node, $teaser = FALSE, $page = FALSE) {
  if (empty($node->included_webforms)) {
    $node = node_prepare($node, $teaser);
    $node->content['no_webforms'] = array(
      '#value' => t('There are no webforms in this A/B test.')
    );
    return $node;
  }
  else {
    if (empty($_SESSION['webform_ab']['webform_for_tests'][$node->nid]) || empty($node->included_webforms[$_SESSION['webform_ab']['webform_for_tests'][$node->nid]])) {
      $key = array_rand($node->included_webforms);
      $_SESSION['webform_ab']['webform_for_tests'][$node->nid] = $key;
      dsm('Setting random webform to ' . $key);
    }
    else {
      dsm('Existing webform: ' . $_SESSION['webform_ab']['webform_for_tests'][$node->nid]);
    }
    drupal_goto('node/' . $_SESSION['webform_ab']['webform_for_tests'][$node->nid]);
  }
}


/**
 * Implementation of hook_webform_ab_valid_webforms().
 * Return an array of webforms of the given form type that may be included in an
 * A/B Test.
 */
function webform_ab_webform_ab_valid_webforms($webform_types) {
  $result = db_query("SELECT nid, title FROM {node} WHERE status > 0 AND type='%s'", array('webform'));
  $forms = array();
  while ($row = db_fetch_array($result)) {
    $forms[] = $row;
  }
  return $forms;
}


/**
 * Implementation of hook_form_alter().
 */
function webform_ab_form_alter(&$form, $form_state, $form_id) {  
  if (is_array($_SESSION['webform_ab']['webform_for_tests'])) {
    foreach ($_SESSION['webform_ab']['webform_for_tests'] as $test_nid => $webform_nid) {
      $test_webform_id = 'webform_client_form_' . $webform_nid;
      if ($test_webform_id == $form_id) {
        $form['#submit'][] = 'webform_ab_webform_submit';
        $form['test_nid'] = array(
          '#type' => 'hidden',
          '#value' => $test_nid
        );
        $form['webform_nid'] = array(
          '#type' => 'hidden',
          '#value' => $webform_nid
        );
        db_query("INSERT INTO {webform_ab_hits} (test_nid, webform_nid, time) VALUES(%d, %d, %d)", array($_GET['test_nid'], $webform_nid, time()));
        break;
      }
    }
  }
}


/**
 * Handle the submission of a webform that is part of a test
 */
function webform_ab_webform_submit($form, &$form_state) {
  db_query("INSERT INTO {webform_ab_conversion} (test_nid, webform_nid, sid) VALUES(%d, %d, %d)", array($form_state['values']['test_nid'], $form_state['values']['webform_nid'], $form_state['values']['details']['sid']));
  _webform_ab_check_for_win($form_state['values']['test_nid']);
}


/**
 * Check if the given A/B Test has a winning webform
 * This function checks to see if a webform has already been declared the winner.
 * If not, it invokes hook_webform_ab_check_win_condition() so that other modules
 * can check their winning conditions, if chosen.
 * This module also implements hook_webform_ab_check_win_condition() below, to
 * check for the basic Total Conversions and Conversion Percentage criteria
 * @todo Check the minimum hit count, too
 */
function _webform_ab_check_for_win($test_nid) {
  $node = node_load($test_nid);
  
  // Check if there is already a winner
  $winner_found = FALSE;
  foreach ($node->included_webforms as $webform_nid => $details) {
    if ($details['status'] == WEBFORM_AB_WEBFORM_STATUS_WINNER) {
      //$winner_found = TRUE;
      break;
    }
  }
  
  if (!$winner_found) {
    // Call a hook to check for wins on all modules that define winning conditions
    $winning_details = module_invoke_all('webform_ab_check_win_condition', $node);

    // Return values of hook implementations are put into a flat array. Loop over and
    // see if any of the returns is a webform nid. Modules that don't find a win will
    // return 0, when they do find a win it will return the webform nid
    foreach ($winning_details as $webform_nid) {
      // See if the webform nid is in the included_webforms array
      if ($node->included_webforms[$webform_nid]) {
        $winning_webform = $node->included_webforms[$webform_nid];
        $node->included_webforms[$webform_nid]['status'] = WEBFORM_AB_WEBFORM_STATUS_WINNER;
        watchdog('webform_ab', "Winner declared in A/B test %testname: %winner", array('%testname' => $winning_webform['title'], '%winner' => $node->title), WATCHDOG_NOTICE);
        db_query("UPDATE {webform_ab_forms} SET status = %d WHERE test_nid = %d AND webform_nid = %d", array(WEBFORM_AB_WEBFORM_STATUS_WINNER, $node->nid, $webform_nid));
      }
    }
  }
}


/**
 * Implementation of hook_webform_ab_check_win_condition().
 * Check which win criteria is being used by the given A/B Test. If it's one of
 * the ones defined by this module, see if any of the webforms in the test have
 * won.
 */
function webform_ab_webform_ab_check_win_condition($node) {
  switch ($node->win_type) {
    case 'total_conversions':
      // Loop over each included webform and check the conversion count
      foreach ($node->included_webforms as $webform_nid => $webform_details) {
        if ($webform_details['conversions'] >= $node->total_conversions) {
          // Win!
          return $webform_nid;
          break;
        }
      }
      break;
    
    case 'percent_conversions':
      foreach ($node->included_webforms as $webform_nid => $webform_details) {
        if (100 * ($webform_details['conversions'] / $webform_details['hits']) > $node->percent_conversions) {
          // Win!
          return $webform_nid;
          break;          
        }
      }
      break;
    
    default:
      dsm($node->win_type, 'win type');
  }
  return 0;
}