<?php

/**
 * @file
 * Integrate Springboard Groups with Springboard Advocacy.
 */

require_once __DIR__ . '/includes/springboard_group_advocacy.access.inc';
require_once __DIR__ . '/includes/springboard_group_advocacy.dashboard.inc';
require_once __DIR__ . '/includes/springboard_group_advocacy.node.inc';
require_once __DIR__ . '/includes/springboard_group_advocacy.node_form.inc';
require_once __DIR__ . '/includes/springboard_group_advocacy.og_context.inc';
require_once __DIR__ . '/includes/springboard_group_advocacy.permissions.inc';
require_once __DIR__ . '/includes/springboard_group_advocacy.subscription.inc';

/**
 * Implements hook_menu_alter().
 */
function springboard_group_advocacy_menu_alter(&$items) {

  $paths = array(
    'admin/springboard/advocacy/actions',
    'admin/springboard/advocacy/message-actions/all',
    'admin/springboard/advocacy/social-actions/all',
    'admin/springboard/advocacy/petitions/all',
  );

  foreach ($items as $path => $item) {
    if (in_array($path, $paths)) {
      if (isset($item['access callback']) && $item['access callback'] == 'springboard_advocacy_user_can_create_advocacy_type') {
        $items[$path]['access callback'] = 'springboard_group_advocacy_user_can_create_advocacy_type';
      }
    }
  }
}


/**
 * Implements hook_views_api().
 */
function springboard_group_advocacy_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'springboard_group_advocacy') . '/includes/views',
  );
}

/**
 * Implements hook_form_alter().
 *
 * Add additional group-specific drupal settings for the sba_target_search.js
 * file to use while searching and adding targets.
 */
function springboard_group_advocacy_form_alter(&$form, &$form_state, $form_id) {

  $types = array(
    'sba_message_edit_form',
    'springboard_target_edit_custom_groups_form',
    'springboard_target_create_custom_groups_form',
  );

  if (in_array($form_id, $types)) {

    $api_call = springboard_advocacy_api_call();
    $subscription = $api_call->getSubscription();

    if (!empty($subscription['is_grouped'])) {
      $group_settings = array(
        'sbaSubscriptionIsGrouped' => TRUE,
        'sbaAllowedStates' => $subscription['states_custom'],
      );
    }
    else {
      $group_settings = array('sbaSubscriptionIsGrouped' => FALSE);
    }
    $form['#attached']['js'][] = array(
      'data' => $group_settings,
      'type' => 'setting',
    );
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * Remove the group selector from the custom target and group edit pages.
 */
function springboard_group_advocacy_preprocess_page(&$vars) {
  $path = current_path();
  $omit = strpos($path, '/add') !== FALSE ? TRUE : strpos($path, '/edit') !== FALSE;
  $og_paths = springboard_group_advocacy_springboard_group_context_menu_paths();
  if ((!in_array($path, $og_paths) || $omit) && isset($_SESSION['springboard_group_context_multiple'])) {
    unset($vars['page']['content']['system_main']['selector']);
  }
}
