<?php
/**
 * @file
 * Process payments using Ogone's e-Commerce and DirectLink methods.
 * 
 * @todo
 *    - Add credit card/direct debit option on the donation form
 */

define('OGONE_DEFAULT_ALIAS_USAGE', 'Check the box below to allow the payment gateway to store your credit card information. This will allow us to make charges for recurring donations without having to store your credit card number, which helps protect your privacy.');

/**
 * Implementation of hook_menu().
 */
function gm_ogone_menu() {
  $items['ogone/post/%uc_order'] = array(
    'title' => t('Redirecting to Ogone...'),
    'page callback' => 'gm_ogone_build_form',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  // Callbacks for responses from Ogone
  $items['ogone/ecommerce_feedback/accept'] = array(
    'title' => 'Ogone Response: Accepted',
    'description' => 'Shown when an Ogone payment is authorized, accepted, or pending.',
    'page callback' => 'gm_ogone_feedback_accepted',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['ogone/ecommerce_feedback/decline'] = array(
    'title' => 'Ogone Response: Declined',
    'description' => 'Shown when an Ogone payment is declined.',
    'page callback' => 'gm_ogone_feedback_declined',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['ogone/ecommerce_feedback/exception'] = array(
    'title' => 'Ogone Response: Exception',
    'description' => 'Shown when an Ogone payment result is uncertain.',
    'page callback' => 'gm_ogone_feedback_exception',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['ogone/ecommerce_feedback/cancel'] = array(
    'title' => 'Ogone Response: Cancelled',
    'description' => 'Shown when an Ogone payment is cancelled by the user.',
    'page callback' => 'gm_ogone_feedback_cancelled',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  
  return $items;
}

/**
 * Build the form that will auto-submit to Ogone
 */
function gm_ogone_build_form($order) {
  drupal_add_js(drupal_get_path('module', 'gm_ogone') . '/gm_ogone.js');
  $output = t("You are being redirected to Ogone to provide your payment details directly to the payment processor. One moment please.");
  $output .= drupal_get_form('gm_ogone_post_form', $order);
  return $output;
}

/**
 * Return the form for the auto-submit form that goes to Ogone
 */
function gm_ogone_post_form(&$form_state, $order) {
  $gateway_config = _gm_ogone_get_config_for_order($order);
  
  // Gather arguments that will be sent
  $arguments = array(
    'ALIASOPERATION' => $gateway_config['ALIASOPERATION'],
    'AMOUNT' => $order->order_total * 100,
    'BGCOLOR' => '',
    'BRAND' => '',
    'BUTTONBGCOLOR' => '',
    'BUTTONTXTCOLOR' => '',
    'CATALOGURL' => '',
    'CN' => $order->billing_first_name . ' ' . $order->billing_last_name,
    'COM' => '',
    'CURRENCY' => 'EUR',
    'EMAIL' => $order->primary_email,
    'FONTTYPE' => '',
    'HOMEURL' => url('<front>', array('absolute' => TRUE)),
    'LANGUAGE' => 'en_US',
    'LOGO' => '',
    'ORDERID' => $order->order_id,
    'OWNERADDRESS' => $order->billing_street1 . ' ' . $order->billing_street2,
    'OWNERCTY' => $order->billing_country,
    'OWNERTOWN' => $order->billing_city,
    'OWNERZIP' => $order->billing_postal_code,
    'PM' => '',
    'PSPID' => $gateway_config['PSPID'],
    'TBLBGCOLOR' => '',
    'TBLTXTCOLOR' => '',
    'TITLE' => '',
    'TP' => '',
    'TXTCOLOR' => '',
    'ACCEPTURL' => url('ogone/ecommerce_feedback/accept', array('absolute' => TRUE)),
    'DECLINEURL' => url('ogone/ecommerce_feedback/decline', array('absolute' => TRUE)),
    'EXCEPTIONURL' => url('ogone/ecommerce_feedback/exception', array('absolute' => TRUE)),
    'CANCELURL' => url('ogone/ecommerce_feedback/cancel', array('absolute' => TRUE)),
  );
  
  // Only send the ALIASUSAGE value if it's set
  if ($gateway_config['ALIASUSAGE'] && $arguments['ALIASOPERATION']) {
    $arguments['ALIASUSAGE'] = $gateway_config['ALIASUSAGE'];
  }
  
  // Sort the arguments by the key. This needs to be done for the SHA-1 verification
  ksort($arguments);
  
  $sha1_signature = '';

  // Loop over the arguments being sent. For each, add a hidden form value, and
  // add it to a string that will be used to calculate the SHA-1 for the values
  // being sent.
  foreach ($arguments as $param_name => $param_value) {
    $param_value = trim($param_value);
    $param_name = strtoupper($param_name);
    if (strlen($param_value) > 0) {
        $sha1_signature .= $param_name . '=' . $param_value . $gateway_config['sha_in'];
        $form[$param_name] = array(
          '#type' => 'hidden',
          '#value' => $param_value,
        );
    }
  }
  $form['SHASign'] = array(
    '#type' => 'hidden',
    '#value' => sha1($sha1_signature),
  );
  
  
  $form['#action'] = $gateway_config['url'];
  $form['#id'] = 'ogone-ecommerce-post';
  
  return $form;
}


/*******************************************************************************
 * Hook Functions (Ubercart)
 ******************************************************************************/
/**
 * Implementation of hook_payment_gateway_managed().
 */
function gm_ogone_payment_gateway_managed() {
  $gateways[] = array(
    'id' => 'ogone',
    'title' => t('Ogone'),
    'description' => t('Process payments using Ogone\'s e-commerce payment method.'),
    'credit' => 'gm_ogone_charge',
    'credit_refund' => 'gm_ogone_refund',
    'settings' => 'gm_ogone_settings_form',
    //'hide_cc_fields' => TRUE,
    'credit_txn_types' => array(UC_CREDIT_PRIOR_AUTH_CAPTURE, UC_CREDIT_AUTH_CAPTURE, UC_CREDIT_REFERENCE_TXN),
  );

  return $gateways;
}


/**
 * Charge callback. This is called from fundraiser_webform_submit()
 */
function gm_ogone_charge($order_id, $amount, $data) {
  if ($credit_card || TRUE) {
    global $user;
    $order = uc_order_load($order_id);

    // Build array of gateway credentials
    $gateway_config = array(
      'PSPID' => $data['config']['gm_ogone_pspid'],
      'USERID' => $data['config']['gm_ogone_userid'],
      'PSWD' => $data['config']['gm_ogone_password'],
      'ALIASOPERATION' => ($data['config']['gm_ogone_alias_enable']) ? 'BYPSP' : '',
    );

    // Set the SHA IN value depending on whether or not the gateway is making live transactions
    if ($data['config']['gm_ogone_transaction_mode'] == 'live') {
      $gateway_config['SHA1IN'] = $data['config']['gm_ogone_directlink_shain_live'];
    }
    else {
      $gateway_config['SHA1IN'] = $data['config']['gm_ogone_directlink_shain_test'];
    }


    // Get the country name from the country ID
    $billing_country = uc_get_country_data(array('country_id' => $order->billing_country));
    $billing_country = !$billing_country ? '' : $billing_country[0]['country_iso_code_2'];
    
    // Build array of charge details
    $charge_details = array(
      // Default currency to US dollars. This is overwritten below if needed
      'CURRENCY' => 'USD',
      // CN name field is limited to 35 characters on the Ogone side
      'CN' => substr($order->billing_first_name . ' ' . $order->billing_last_name, 0, 35),
      'ORDERID' => $order->order_id,
      'AMOUNT' => $amount,
      'CARDNO' => $order->payment_details['cc_number'],
      'ED' => $order->payment_details['cc_exp_month'] .'/'. $order->payment_details['cc_exp_year'],
      'CVC' => $order->payment_details['cc_cvv'],
      'EMAIL' => $order->primary_email,
      'OWNERADDRESS' => $order->billing_street1 . ' ' . $order->billing_street2,
      'OWNERCTY' => $billing_country,
      'OWNERTOWN' => $order->billing_city,
      'OWNERZIP' => $order->billing_postal_code,
    );

    // If a currency was set for this order, use it
    if ($order->data['currency']) {
      $charge_details['CURRENCY'] = strtoupper($order->data['currency']);
    }


    $charge_result = ogone_directlink_api_charge_credit($gateway_config, $charge_details);

    $success = FALSE;
    if ($charge_result && $charge_result['NCERROR'] == 0) {
      $success = TRUE;
      $context = array(
        'revision' => 'formatted-original',
        'type' => 'amount',
      );
      $message = t('Credit card charged: !amount', array('!amount' => uc_price($amount, $context)));
      uc_order_comment_save($order_id, $user->uid, $message, 'admin');
    }
    else {
      $message = t('Credit card charge failed.');
      uc_order_comment_save($order_id, $user->uid, $message, 'admin');
    }

    $message = t('Card charged: ID: @id', array('@id' => $charge_result['PAYID']));
    $result = array(
      'success' => $success,
      'comment' => $message,
      'message' => $success ? t('Credit card payment processed successfully.') : t('Credit card charge failed.'),
      'uid' => $user->uid,
      'data' => array('module' => 'gm_ogone', 'txn_id' => $charge_result['PAYID']),
    );

    return $result;
  }
  // Non-credit card payment, so redirect to Ogone so the user can enter
  // their payment info there
  else {
    drupal_goto('ogone/post/' . $order_id);
  }
}


/**
 * Issue a refund against an e-Commerce payment
 * 
 * @param $order_id
 *   Order ID
 * @param $amount
 *   Amount to refund
 * @param $data
 *   Array of info about the transaction to be made
 * 
 * @return
 *   Array of info about the success/failure of the refund transaction
 */
function gm_ogone_refund($order_id, $amount, $data) {
  global $user;
  $order = uc_order_load($order_id);

  // Build array of gateway credentials
  $gateway_config = array(
    'PSPID' => $data['config']['gm_ogone_pspid'],
    'USERID' => $data['config']['gm_ogone_userid'],
    'PSWD' => $data['config']['gm_ogone_password'],
    'ALIASOPERATION' => ($data['config']['gm_ogone_alias_enable']) ? 'BYPSP' : '',
  );
  
  // Set the SHA IN value depending on whether or not the gateway is making live transactions
  if ($data['config']['gm_ogone_directlink_transaction_mode'] == 'live') {
    $gateway_config['SHA1IN'] = $data['config']['gm_ogone_directlink_shain_live'];
  }
  else {
    $gateway_config['SHA1IN'] = $data['config']['gm_ogone_directlink_shain_test'];
  }
  

  // Build array of charge details
  $charge_details = array(
    'CURRENCY' => 'USD',    // Default currency to US dollars. This is overwritten below if needed
    'ORDERID' => $order->order_id,
    'AMOUNT' => $amount,
  );
  
  // If a currency was set for this order, use it
  if ($order->data['currency']) {
    $charge_details['CURRENCY'] = strtoupper($order->data['currency']);
  }
  
  $charge_result = ogone_directlink_api_refund($gateway_config, $charge_details);
  
  $success = FALSE;
  if ($charge_result && $charge_result['NCERROR'] == 0) {
    $success = TRUE;
    $context = array(
      'revision' => 'formatted-original',
      'type' => 'amount',
    );
    $message = t('Credit card refunded: !amount', array('!amount' => uc_price($amount, $context)));
    uc_order_comment_save($order_id, $user->uid, $message, 'admin');
  }
  else {
    $message = t('Credit card refund failed.');
    uc_order_comment_save($order_id, $user->uid, $message, 'admin');
  }

  $message = t('Card refunded: ID: @id', array('@id' => $charge_result['PAYID']));
  $result = array(
    'success' => $success,
    'comment' => $message,
    'message' => $success ? t('Credit card refund processed successfully.') : t('Credit card refund failed.'),
    'uid' => $user->uid,
    'data' => array('module' => 'gm_ogone', 'txn_id' => $charge_result['PAYID']),
  );

  return $result;
}


/**
 * Settings form for an Ogone gateway
 */
function gm_ogone_settings_form($config = array()) {
  $form['account_credentials'] = array(
    '#type' => 'fieldset',
    '#title' => t('Account Credentials'),
    '#description' => t('The title you enter here appears on the page.'),
    '#size' => 40,
    '#maxlength' => 255,
  );
  
  $form['account_credentials']['gm_ogone_pspid'] = array(
    '#type' => 'textfield',
    '#title' => t('PSPID'),
    '#description' => t('Ogone PSPID.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_pspid'],
    '#required' => TRUE,
  );

  $form['account_credentials']['gm_ogone_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('DirectLink User ID'),
    '#description' => t('User ID for use with DirectLink API.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_userid'],
    '#required' => TRUE,
  );

  $form['account_credentials']['gm_ogone_password'] = array(
    '#type' => 'textfield',
    '#title' => t('DirectLink Password'),
    '#description' => t('Password for use with DirectLink API user.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_password'],
    '#required' => TRUE,
  );


  $form['gm_ogone_transaction_mode'] = array(
    '#type' => 'radios',
    '#title' => t('Transaction Mode'),
    '#description' => t('Should transactions be made in a live or test environment? This setting will determine which of the options below are used: live or test.'),
    '#options' => array(
      'test' => t('Test'),
      'live' => t('Live'),
    ),
    '#default_value' => $config['gm_ogone_transaction_mode'],
    '#required' => TRUE,
  );
  
  
  $form['security_keys_test'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('Security keys for test transactions'),
    '#description' => t('Security keys used for test transactions. Log in to the !merchant_admin to set these values.', array('!merchant_admin' => l('merchant admin', 'https://secure.ogone.com/ncol/test/frame_ogone.asp'))),
  );
  $form['security_keys_test']['shain'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('SHA-IN'),
    '#description' => t('Security keys used to verify data sent to Ogone. These are set on the "Data and origin verification" tab in the Technical Information section of the Ogone admin.'),
  );
  $form['security_keys_test']['shain']['gm_ogone_ecommerce_shain_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Passphrase for e-Commerce'),
    '#description' => t('Listed under "Checks for e-Commerce" on the "Date and origin verification" tab.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_ecommerce_shain_test'],
  );
  $form['security_keys_test']['shain']['gm_ogone_directlink_shain_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Passphrase for DirectLink'),
    '#description' => t('Listed under "Checks for Ogone DirectLink" on the "Date and origin verification" tab.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_directlink_shain_test'],
  );
  $form['security_keys_test']['shaout'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('SHA-OUT'),
    '#description' => t('Security keys used to verify data returned from Ogone. These are set on the "Transaction feedback" tab in the Technical Information section of the Ogone admin.'),
  );
  $form['security_keys_test']['shaout']['gm_ogone_ecommerce_shaout_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Passphrase for e-Commerce'),
    '#description' => t('Listed under "Security for request parameters" on the "Transaction Feedback" tab.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_ecommerce_shaout_test'],
  );
  
  $form['security_keys_live'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('Security keys for live transactions'),
    '#description' => t('Security keys used for live transactions. Log in to the !merchant_admin to set these values.', array('!merchant_admin' => l('merchant admin', 'https://secure.ogone.com/ncol/prod/frame_ogone.asp'))),    
  );
  $form['security_keys_live']['shain'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('SHA-IN'),
    '#description' => t('Security keys used to verify data sent to Ogone. These are set on the "Data and origin verification" tab in the Technical Information section of the Ogone admin.'),
  );
  $form['security_keys_live']['shain']['gm_ogone_ecommerce_shain_live'] = array(
    '#type' => 'textfield',
    '#title' => t('Passphrase for e-Commerce'),
    '#description' => t('Listed under "Checks for e-Commerce" on the "Date and origin verification" tab.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_ecommerce_shain_live'],
  );
  $form['security_keys_live']['shain']['gm_ogone_directlink_shain_live'] = array(
    '#type' => 'textfield',
    '#title' => t('Passphrase for DirectLink'),
    '#description' => t('Listed under "Checks for Ogone DirectLink" on the "Date and origin verification" tab.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_directlink_shain_live'],
  );
  $form['security_keys_live']['shaout'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('SHA-OUT'),
    '#description' => t('Security keys used to verify data returned from Ogone. These are set on the "Transaction feedback" tab in the Technical Information section of the Ogone admin.'),
  );
  $form['security_keys_live']['shaout']['gm_ogone_ecommerce_shaout_live'] = array(
    '#type' => 'textfield',
    '#title' => t('Passphrase for e-Commerce'),
    '#description' => t('Listed under "Security for request parameters" on the "Transaction Feedback" tab.'),
    '#maxlength' => 255,
    '#default_value' => $config['gm_ogone_ecommerce_shaout_live'],
  );
  
  
  
  $form['alias_settings'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#title' => t('Alias Settings'),
    '#description' => t('Ogone uses "aliases" to retain the payment information for users so that it may be used again in the future. This is necessary for recurring donations: credit card numbers are not stored in Springboard. Ogone manages the storage of that information and gives us an alias that we can pass them for future recurring donations.'),
  );
  $form['alias_settings']['gm_ogone_alias_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Alias usage'),
    '#description' => t('If you have not already, you may need to enable Alias Management in the Ogone admin web interface, at Configuration > Account > Your Options.'),
    '#default_value' => !empty($config['gm_ogone_alias_enable']) ? $config['gm_ogone_alias_enable'] : FALSE,
  );
  
  $form['alias_settings']['gm_ogone_alias_usage'] = array(
    '#type' => 'textarea',
    '#title' => t('Alias Usage Explanation'),
    '#description' => t('This brief message will be shown to the user on the page where they enter their credit card info. It is shown above a checkbox labeled, "I allow Ogone to store my financial details in a secure way so I won\'t have to enter them again for future orders with this merchant." Ogone limits this explanation to 255 characters.'),
    '#cols' => 60,
    '#rows' => 2,
    '#maxlength' => 255,
    '#default_value' => isset($config['gm_ogone_alias_usage']) ? $config['gm_ogone_alias_usage'] : OGONE_DEFAULT_ALIAS_USAGE,
  );
  
  
  return $form;
}






/*******************************************************************************
 * Ogone Feedback Functions
 ******************************************************************************/
/**
 * Menu callback: successful payment
 */
function gm_ogone_feedback_accepted() {
  $payment_values = _gm_ogone_get_returned_values();
  $order_id = $payment_values['ORDERID'];
  $transaction_id = $payment_values['PAYID'];
  $webform = db_fetch_object(db_query("SELECT webform_nid, sid FROM {fundraiser_webform_order} WHERE order_id = %d", $order_id));

  if (_gm_ogone_check_feedback_sha($payment_values)) {
    // If no Alias could be set, the donation cannot be recurring
    $order = uc_order_load($order_id);
    if ($order->data['recurring_status'] == DONATION_RECURRING && empty($payment_values['ALIAS'])) {
      $order->data['recurring_status'] = DONATION_NON_RECURRING;
      uc_order_save($order); 
    }    
    
    fundraiser_order_accept($order_id, $transaction_id);
    drupal_goto('node/' . $webform->webform_nid . '/confirmation', array('sid' => $webform->sid));
  }
  else {
    fundraiser_order_exception($order_id, t('There was an error with your payment. The data from the payment processor may have been tampered with before reaching our server. Please contact a site administrator to check on the status of your payment.'));
    drupal_goto('node/' . $webform->webform_nid);
  }
}


/**
 * Menu callback: declined payment
 */
function gm_ogone_feedback_declined() {
  $payment_values = _gm_ogone_get_returned_values();
  $order_id = $payment_values['ORDERID'];
  $webform = db_fetch_object(db_query("SELECT webform_nid, sid FROM {fundraiser_webform_order} WHERE order_id = %d", $order_id));
  
  if (_gm_ogone_check_feedback_sha($payment_values)) {
    fundraiser_order_decline($order_id, $message);
  }
  else {
    fundraiser_order_exception($order_id, t('There was an error with your payment. The data from the payment processor may have been tampered with before reaching our server. Please contact a site administrator to check on the status of your payment.'));
  }
  drupal_goto('node/' . $webform->webform_nid);
}


/**
 * Menu callback: exception
 */
function gm_ogone_feedback_exception() {
  $payment_values = _gm_ogone_get_returned_values();
  $order_id = $payment_values['ORDERID'];
  $webform = db_fetch_object(db_query("SELECT webform_nid, sid FROM {fundraiser_webform_order} WHERE order_id = %d", $order_id));
  
  if (_gm_ogone_check_feedback_sha($payment_values)) {
    fundraiser_order_exception($order_id, '');
  }
  else {
    fundraiser_order_exception($order_id, t('There was an error with your payment. The data from the payment processor may have been tampered with before reaching our server. Please contact a site administrator to check on the status of your payment.'));
  }
  drupal_goto('node/' . $webform->webform_nid);
}



/**
 * Menu callback: cancelled payment
 */
function gm_ogone_feedback_cancelled() {
  $payment_values = _gm_ogone_get_returned_values();
  $order_id = $payment_values['ORDERID'];
  $webform = db_fetch_object(db_query("SELECT webform_nid, sid FROM {fundraiser_webform_order} WHERE order_id = %d", $order_id));

  if (_gm_ogone_check_feedback_sha($payment_values)) {
    fundraiser_order_cancel($order_id);
  }
  else {
    fundraiser_order_exception($order_id, t('There was an error with your payment. The data from the payment processor may have been tampered with before reaching our server. Please contact a site administrator to check on the status of your payment.'));
  }
  drupal_goto('node/' . $webform->webform_nid);
}


/**
 * Check if the SHA value from the payment processor is correct
 */
function _gm_ogone_check_feedback_sha($return_values) {
  $gateway_config = _gm_ogone_get_config_for_order($return_values['ORDERID']);
  $sha_out_phrase = $gateway_config['sha_out'];
  
  ksort($return_values);
  
  $sha1_signature = '';
  foreach ($return_values as $param_name => $param_value) {
    if (strlen($param_value) > 0 && $param_name != 'SHASIGN') {
      $sha1_signature .= $param_name . '=' . $param_value . $sha_out_phrase;
    }
  }
  $sha1_signature = sha1($sha1_signature);
  if (strtoupper($sha1_signature) == $return_values['SHASIGN']) {
    return true;
  }
  else {
    return false;
  }
}


/**
 * Get an array of the data passed back from the payment processor
 */
function _gm_ogone_get_returned_values() {
  static $return_values;
  if (empty($return_values)) {
    $return_values = array(
      'AAVCHECK' => check_plain(trim($_GET['AAVCheck'])),
      'ACCEPTANCE' => check_plain(trim($_GET['ACCEPTANCE'])),
      'ALIAS' => check_plain(trim($_GET['ALIAS'])),
      'AMOUNT' => check_plain(trim($_GET['amount'])),
      'BRAND' => check_plain(trim($_GET['BRAND'])),
      'CARDNO' => check_plain(trim($_GET['CARDNO'])),
      'CCCTY'=> check_plain(trim($_GET['CCCTY'])),
      'CN' => check_plain(trim($_GET['CN'])),
      'CURRENCY' => check_plain(trim($_GET['currency'])),
      'CVCCHECK' => check_plain(trim($_GET['CVCCheck'])),
      'ECI' => check_plain(trim($_GET['ECI'])),
      'ED' => check_plain(trim($_GET['ED'])),
      'IP' => check_plain(trim($_GET['IP'])),
      'IPCTY' => check_plain(trim($_GET['IPCTY'])),
      'NCERROR' => check_plain(trim($_GET['NCERROR'])),
      'ORDERID' => check_plain(trim($_GET['orderID'])),
      'PAYID' => check_plain(trim($_GET['PAYID'])),
      'PM' => check_plain(trim($_GET['PM'])),
      'STATUS' => check_plain(trim($_GET['STATUS'])),
      'TRXDATE' => check_plain(trim($_GET['TRXDATE'])),
      'VC' => check_plain(trim($_GET['VC'])),
      'SHASIGN' => check_plain(trim($_GET['SHASIGN'])),
    );
  }
  return $return_values;
}


/**
 * Get the Ogone config variables for the given order
 * 
 * This function checks if the gateway is configured to use live or test
 * transactions, and returns the appropriate variables.
 * 
 * @param $order_or_id
 *   Ubercart order object, or an order ID
 * @return
 *   Array of gateway config info
 */
function _gm_ogone_get_config_for_order($order_or_id) {
  // Load gateway details
  $gateway = gateway_manager_gateway_for_order($order_or_id);
  $gateway_config = $gateway['config'];
 
  $config = array(
    'PSPID' => $gateway_config['gm_ogone_pspid'],
    'ALIASUSAGE' => $gateway_config['gm_ogone_alias_usage'],
    'ALIASOPERATION' => ($gateway_config['gm_ogone_alias_enable']) ? 'BYPSP' : '',
  );
  
  // If using the live transaction mode, load live vars
  if ($gateway_config['gm_ogone_transaction_mode'] == 'live') {
    $config['sha_in'] = $gateway_config['gm_ogone_ecommerce_shain_live'];
    $config['sha_out'] = $gateway_config['gm_ogone_ecommerce_shaout_live'];
    $config['url'] = 'https://secure.ogone.com/ncol/prod/orderstandard.asp';
  }
  // Not using live transactions, so use test vars
  else {
    $config['sha_in'] = $gateway_config['gm_ogone_ecommerce_shain_test'];
    $config['sha_out'] = $gateway_config['gm_ogone_ecommerce_shaout_test'];
    $config['url'] = 'https://secure.ogone.com/ncol/test/orderstandard.asp';
  }
  return $config;
}