<?php
// $Id$

/**
 * @file
 * This is the file description for springboard_ga module.
 *
 */

/**
 * Implements hook_menu().
 */
function springboard_ga_menu() {
  $items = array();
  $items['admin/springboard/settings/ga'] = array(
    'title' => 'Google Analytics Tracking Configuration',
    'description' => 'Configuration for the Springboard GA Tracking module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('springboard_ga_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function springboard_ga_settings_form($form, &$form_state)  {
  $form['springboard_ga_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => 'Enable Google Analytics Tracking for Donations',
    '#default_value' => variable_get('springboard_ga_enabled', 0),
  );
  $form['springboard_ga_trans'] = array(
    '#type' => 'fieldset',
    '#title' => 'Transaction Defaults',
    '#description' => 'Populate default values for transactions. A token list is available below.'
  );
  $form['springboard_ga_trans']['springboard_ga_trans_transaction_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Transaction ID'),
    '#description' => t('Internal unique transaction ID number for this transaction.'),
    '#max_length' => 100,
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_trans_transaction_id', '[donation:did]'),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_affiliation'] = array(
    '#type' => 'textfield',
    '#title' => t('Affiliation'),
    '#description' => t('Partner or store affiliation.'),
    '#max_length' => 100,
    '#size' => 20,
    '#required' => FALSE,
    '#default_value' => variable_get('springboard_ga_trans_affiliation', ''),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_total'] = array(
    '#type' => 'textfield',
    '#title' => t('Total'),
    '#description' => t('Total dollar amount of the transaction. Does not include tax and shipping and should only be considered the "grand total" if you explicitly include shipping and tax.'),
    '#max_length' => 100,
    '#size' => 10,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_trans_total', '[donation:amount]'),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_tax'] = array(
    '#type' => 'textfield',
    '#title' => t('Tax'),
    '#description' => t('Tax amount of the transaction.'),
    '#max_length' => 100,
    '#size' => 10,
    '#required' => FALSE,
    '#default_value' => variable_get('springboard_ga_trans_tax', ''),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_shipping'] = array(
    '#type' => 'textfield',
    '#title' => t('Shipping'),
    '#description' => t('Shipping charge for the transaction.'),
    '#max_length' => 100,
    '#size' => 10,
    '#required' => FALSE,
    '#default_value' => variable_get('springboard_ga_trans_shipping', ''),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#description' => t('City to associate with transaction.'),
    '#max_length' => 100,
    '#size' => 25,
    '#required' => FALSE,
    '#default_value' => variable_get('springboard_ga_trans_city', '[donation:city]'),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_state'] = array(
    '#type' => 'textfield',
    '#title' => t('State'),
    '#description' => t('State to associate with transaction.'),
    '#max_length' => 100,
    '#size' => 25,
    '#required' => FALSE,
    '#default_value' => variable_get('springboard_ga_trans_state', '[donation:state]'),
  );
  $form['springboard_ga_trans']['springboard_ga_trans_country'] = array(
    '#type' => 'textfield',
    '#title' => t('Country'),
    '#description' => t('Country to associate with transaction.'),
    '#max_length' => 100,
    '#size' => 40,
    '#required' => FALSE,
    '#default_value' => variable_get('springboard_ga_trans_country', '[donation:country]'),
  );
  $form['springboard_ga_item'] = array(
    '#type' => 'fieldset',
    '#title' => 'Item Defaults',
    '#description' => 'Populate default values for transactions. A token list is available below.'
  );
  $form['springboard_ga_item']['springboard_ga_item_order_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Order ID'),
    '#description' => t('Optional Order ID of the transaction to associate with item.'),
    '#max_length' => 100,
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_item_order_id', '[donation:did]'),
  );
  $form['springboard_ga_item']['springboard_ga_item_sku'] = array(
    '#type' => 'textfield',
    '#title' => t('SKU Code'),
    '#description' => t("Item's SKU code."),
    '#max_length' => 100,
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_item_sku', '[donation:node:nid]'),
  );
  $form['springboard_ga_item']['springboard_ga_item_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#description' => t('Product name. Required to see data in the product detail report.'),
    '#max_length' => 255,
    '#size' => 40,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_item_name', '[donation:node:title]'),
  );
  $form['springboard_ga_item']['springboard_ga_item_category'] = array(
    '#type' => 'textfield',
    '#title' => t('Category'),
    '#description' => t('Product category.'),
    '#max_length' => 255,
    '#size' => 40,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_item_category', 'Donation'),
  );
  $form['springboard_ga_item']['springboard_ga_item_price'] = array(
    '#type' => 'textfield',
    '#title' => t('Price'),
    '#description' => t('Product price.'),
    '#max_length' => 100,
    '#size' => 10,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_item_price', '[donation:amount]'),
  );
  $form['springboard_ga_item']['springboard_ga_item_quantity'] = array(
    '#type' => 'textfield',
    '#title' => t('Quantity'),
    '#description' => t('Product quantity.'),
    '#max_length' => 100,
    '#size' => 5,
    '#required' => TRUE,
    '#default_value' => variable_get('springboard_ga_item_quantity', '1'),
  );
  $form['springboard_ga_tokens_message']['tokens'] = array(
    '#type' => 'fieldset',
    '#title' => t('Tracking Replacement Tokens'),
    '#description' => t('The following tokens are available for any of the Item fields.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $token_set = array('donation', 'user', 'node');
  $form['springboard_ga_tokens_message']['tokens']['token_help'] = array(
    '#type' => 'item',
    '#title' => t('Drupal tokens'),
    '#description' => theme('token_tree', array('token_types' => $token_set, 'recursion_limit' => 2, 'click_insert' => FALSE)),
  );
  return system_settings_form($form);
}

function springboard_ga_nodeform_submit($form, &$form_state) {
  global $user;
  if(!empty($form_state['values']['springboard_ga'])) {
    $result = db_query('SELECT nid, uid, settings FROM {springboard_ga} WHERE nid = :nid',  array(':nid' => $form_state['values']['nid']));
    $record = $result->fetchObject();
    if((!$record)&&($form_state['values']['springboard_ga']['springboard_ga_enabled'] == 1)) {
      db_insert('springboard_ga') // Table name no longer needs {}
        ->fields(array(
          'nid' => $form_state['values']['nid'],
          'uid' => $user->uid,
          'settings' => serialize($form_state['values']['springboard_ga']),
        ))
        ->execute();
    } else {
      db_update('springboard_ga') // Table name no longer needs {}
        ->fields(array(
          'uid' => $user->uid,
          'settings' => serialize($form_state['values']['springboard_ga']),
        ))
        ->condition('nid',$form_state['values']['nid'])
        ->execute();
    }
  }
}

function springboard_ga_form_donation_form_node_form_alter(&$form, &$form_state) {
  if(fundraiser_is_donation_type($form['#node']->type)) {
    if(variable_get('springboard_ga_enabled',0) == 1) {
      if(is_numeric($form_state['build_info']['args'][0]->nid)) {
        $n = node_load($form_state['build_info']['args'][0]->nid);
      }
      $form['#submit'][] = 'springboard_ga_nodeform_submit';
      $form['springboard_ga'] = array(
        '#type' => 'fieldset',
        '#title' => t('E-commerce tracking'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE,
        '#group' => 'additional_settings',
      );
      $form['springboard_ga']['springboard_ga_enabled'] = array(
        '#type' => 'checkbox',
        '#title' => 'Override Default GA Tracking for this Donation Form',
        '#default_value' => $n->springboard_ga['springboard_ga_enabled'],
      );
      $form['springboard_ga']['springboard_ga_trans'] = array(
        '#type' => 'fieldset',
        '#title' => 'Transaction Defaults',
        '#description' => 'Populate default values for transactions. A token list is available below.',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_transaction_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Transaction ID'),
        '#description' => t('Internal unique transaction ID number for this transaction.'),
        '#max_length' => 100,
        '#size' => 20,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_transaction_id'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_affiliation'] = array(
        '#type' => 'textfield',
        '#title' => t('Affiliation'),
        '#description' => t('Partner or store affiliation.'),
        '#max_length' => 100,
        '#size' => 20,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_affiliation'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_total'] = array(
        '#type' => 'textfield',
        '#title' => t('Total'),
        '#description' => t('Total dollar amount of the transaction. Does not include tax and shipping and should only be considered the "grand total" if you explicitly include shipping and tax.'),
        '#max_length' => 100,
        '#size' => 10,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_total'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_tax'] = array(
        '#type' => 'textfield',
        '#title' => t('Tax'),
        '#description' => t('Tax amount of the transaction.'),
        '#max_length' => 100,
        '#size' => 10,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_tax'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_shipping'] = array(
        '#type' => 'textfield',
        '#title' => t('Shipping'),
        '#description' => t('Shipping charge for the transaction.'),
        '#max_length' => 100,
        '#size' => 10,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_shipping'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_city'] = array(
        '#type' => 'textfield',
        '#title' => t('City'),
        '#description' => t('City to associate with transaction.'),
        '#max_length' => 100,
        '#size' => 25,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_city'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_state'] = array(
        '#type' => 'textfield',
        '#title' => t('State'),
        '#description' => t('State to associate with transaction.'),
        '#max_length' => 100,
        '#size' => 25,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_state'],
      );
      $form['springboard_ga']['springboard_ga_trans']['springboard_ga_trans_country'] = array(
        '#type' => 'textfield',
        '#title' => t('Country'),
        '#description' => t('Country to associate with transaction.'),
        '#max_length' => 100,
        '#size' => 40,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_trans']['springboard_ga_trans_country'],
      );
      $form['springboard_ga']['springboard_ga_item'] = array(
        '#type' => 'fieldset',
        '#title' => 'Item Defaults',
        '#description' => 'Populate default values for transactions. A token list is available below.',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      $form['springboard_ga']['springboard_ga_item']['springboard_ga_item_order_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Order ID'),
        '#description' => t('Optional Order ID of the transaction to associate with item.'),
        '#max_length' => 100,
        '#size' => 20,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_item']['springboard_ga_item_order_id'],
      );
      $form['springboard_ga']['springboard_ga_item']['springboard_ga_item_sku'] = array(
        '#type' => 'textfield',
        '#title' => t('SKU Code'),
        '#description' => t("Item's SKU code."),
        '#max_length' => 100,
        '#size' => 20,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_item']['springboard_ga_item_sku'],
      );
      $form['springboard_ga']['springboard_ga_item']['springboard_ga_item_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#description' => t('Product name. Required to see data in the product detail report.'),
        '#max_length' => 255,
        '#size' => 40,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_item']['springboard_ga_item_name'],
      );
      $form['springboard_ga']['springboard_ga_item']['springboard_ga_item_category'] = array(
        '#type' => 'textfield',
        '#title' => t('Category'),
        '#description' => t('Product category.'),
        '#max_length' => 255,
        '#size' => 40,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_item']['springboard_ga_item_category'],
      );
      $form['springboard_ga']['springboard_ga_item']['springboard_ga_item_price'] = array(
        '#type' => 'textfield',
        '#title' => t('Price'),
        '#description' => t('Product price.'),
        '#max_length' => 100,
        '#size' => 10,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_item']['springboard_ga_item_price'],
      );
      $form['springboard_ga']['springboard_ga_item']['springboard_ga_item_quantity'] = array(
        '#type' => 'textfield',
        '#title' => t('Quantity'),
        '#description' => t('Product quantity.'),
        '#max_length' => 100,
        '#size' => 5,
        '#required' => FALSE,
        '#default_value' => $n->springboard_ga['springboard_ga_item']['springboard_ga_item_quantity'],
      );
      $form['springboard_ga']['springboard_ga_tokens_message']['tokens'] = array(
        '#type' => 'fieldset',
        '#title' => t('Tracking Replacement Tokens'),
        '#description' => t('The following tokens are available for any of the Item fields.'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );
      $token_set = array('donation', 'user', 'node');
      $form['springboard_ga']['springboard_ga_tokens_message']['tokens']['token_help'] = array(
        '#type' => 'item',
        '#title' => t('Drupal tokens'),
        '#description' => theme('token_tree', array('token_types' => $token_set, 'recursion_limit' => 2, 'click_insert' => FALSE)),
      );
    }
  }
}

function springboard_ga_node_load($nodes, $types) {
  if (count(array_intersect(array('donation_form'), $types))) {
    $result = db_query('SELECT nid, uid, settings FROM {springboard_ga} WHERE nid IN(:nids)', 
                       array(':nids' => array_keys($nodes)));
    foreach ($result as $record) {
      $settings = unserialize($record->settings);
      if($settings['springboard_ga_enabled'] == 1) {
        $nodes[$record->nid]->springboard_ga = $settings;
      }
    }
    foreach($nodes AS $n) {
      if(empty($nodes[$n->nid]->springboard_ga)) {
        $nodes[$n->nid]->springboard_ga = array(
          'springboard_ga_enabled' => 0,
          'springboard_ga_trans' => array(
            'springboard_ga_trans_transaction_id' => variable_get('springboard_ga_trans_transaction_id',''),
            'springboard_ga_trans_affiliation' => variable_get('springboard_ga_trans_affiliation',''),
            'springboard_ga_trans_total' => variable_get('springboard_ga_trans_total',''),
            'springboard_ga_trans_tax' => variable_get('springboard_ga_trans_tax',''),
            'springboard_ga_trans_shipping' => variable_get('springboard_ga_trans_shipping',''),
            'springboard_ga_trans_city' => variable_get('springboard_ga_trans_city',''),
            'springboard_ga_trans_state' => variable_get('springboard_ga_trans_state',''),
            'springboard_ga_trans_country' => variable_get('springboard_ga_trans_country',''),
          ),
          'springboard_ga_item' => array(
            'springboard_ga_item_order_id' => variable_get('springboard_ga_item_order_id',''),
            'springboard_ga_item_sku' => variable_get('springboard_ga_item_sku',''),
            'springboard_ga_item_name' => variable_get('springboard_ga_item_name',''),
            'springboard_ga_item_category' => variable_get('springboard_ga_item_category',''),
            'springboard_ga_item_price' => variable_get('springboard_ga_item_price',''),
            'springboard_ga_item_quantity' => variable_get('springboard_ga_item_quantity',''),
          )
        );
      }
    }
  }
}

function springboard_ga_preprocess_webform_confirmation (&$vars) {
  $script = _springboard_ga_js_build($vars, 'asynch');
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  $token_set = array('node' => node_load($vars['node']->nid));
  drupal_alter('webform_confirmations_token_replace', $token_set, $vars['sid']);
  $script = token_replace($script, $token_set);
  $submission = webform_get_submission($vars['node']->nid, $vars['sid']);
  $GLOBALS['conf']['googleanalytics_codesnippet_before'] .= $script;
  /*
  // Which version of the tracking library should be used?
  $script .= '(function() {';
  $script .= 'var ga = document.createElement("script");';
  $script .= 'ga.type = "text/javascript";';
  $script .= 'ga.async = true;';
  if ($trackdoubleclick = variable_get('googleanalytics_trackdoubleclick', FALSE)) {
    $library_tracker_url = 'stats.g.doubleclick.net/dc.js';
    $library_cache_url = 'http://' . $library_tracker_url;
  }
  else {
    $library_tracker_url = '.google-analytics.com/ga.js';
    $library_cache_url = 'http://www' . $library_tracker_url;
  }

  // Should a local cached copy of ga.js be used?
  if (variable_get('googleanalytics_cache', 0) && $url = _googleanalytics_cache($library_cache_url)) {
    // A dummy query-string is added to filenames, to gain control over
    // browser-caching. The string changes on every update or full cache
    // flush, forcing browsers to load a new copy of the files, as the
    // URL changed.
    $query_string = '?' . variable_get('css_js_query_string', '0');

    $script .= "\n\nga.src = \"" . $url . $query_string . '";';
  }
  else {
    // Library paths do not follow the same naming convention.
    if ($trackdoubleclick) {
      $script .= 'ga.src = ("https:" == document.location.protocol ? "https://" : "http://") + "' . $library_tracker_url . '";';
    }
    else {
      $script .= 'ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + "' . $library_tracker_url . '";';
    }
  }
  $script .= 'var s = document.getElementsByTagName("script")[0];';
  $script .= 's.parentNode.insertBefore(ga, s);';
  $script .= '});';


  $scope = variable_get('googleanalytics_js_scope', 'header');
  drupal_add_js($script, array('scope' => $scope, 'type' => 'inline'));
  */
  // add_js
}

function springboard_ga_node_delete($node) {
  if($node->type == 'donation_form') {
    db_delete('springboard_ga')->condition('nid', $node->nid)->execute();
  }
}

function _springboard_ga_js_build(&$vars, $type = 'asynch') {
  if($type == 'asynch') {
    $js = "\nvar _gaq = _gaq || [];";
    $js .= "\n_gaq.push(['_setAccount', '" . variable_get('googleanalytics_account', '') . "']);";
    $js .= "\n" . variable_get('googleanalytics_codesnippet_before', '');
    $js .= "\n_gaq.push(['_trackPageview']);";
    $js .= variable_get('googleanalytics_codesnippet_after', '');
    $js .= "\n" . _springboard_ga_js_add_trans($vars,'asynch');
    $js .= "\n" . _springboard_ga_js_add_item($vars,'asynch');
    $js .= "\n_gaq.push(['_trackTrans']);\n";
  } else {
    $js = <<<EOS
    try{
      var springboard_ga_pageTracker = _gat._getTracker("UA-40474837-1");
      springboard_ga_pageTracker._trackPageview();
EOS;
    $js .= "\n" . _springboard_ga_js_add_trans($vars,'traditional');
    $js .= "\n" . _springboard_ga_js_add_item($vars,'traditional');
    $js .= <<<EOS
      
      springboard_ga_pageTracker._trackTrans();
    } catch(err) {}
EOS;
  }
  return $js;
}

function _springboard_ga_js_add_trans(&$vars, $type = 'asynch') {
  $jsq = '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_transaction_id'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_affiliation'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_total'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_tax'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_shipping'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_city'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_state'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_trans']['springboard_ga_trans_country'] .'"';
  if($type == 'asynch') {
    $js = "_gaq.push(['_addTrans',";
    $js .= $jsq;
    $js .= "]);";
  } else {
    $js = "\nspringboard_ga_pageTracker._addTrans(";
    $js .= $jsq;
    $js .= ");";
  }
  return $js;
}

function _springboard_ga_js_add_item(&$vars, $type = 'asynch') {
  $jsq = '"' . $vars['node']->springboard_ga['springboard_ga_item']['springboard_ga_item_order_id'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_item']['springboard_ga_item_sku'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_item']['springboard_ga_item_name'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_item']['springboard_ga_item_category'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_item']['springboard_ga_item_price'] .'",';
  $jsq .= '"' . $vars['node']->springboard_ga['springboard_ga_item']['springboard_ga_item_quantity'] .'"';
  if($type == 'asynch') {
    $js = "_gaq.push(['_addItem',";
    $js .= $jsq;
    $js .= "]);";
  } else {
    $js = "springboard_ga_pageTracker._addItem(";
    $js .= $jsq;
    $js .= ");";
  }
  return $js;
}

