<?php
/**
 * @file
 * Module file for fundraiser_quick_donate.
 */

define('FUNDRAISER_QUICK_DONATE_DEFAULT_FORM_PREFIX', 'fundraiser_quick_donate_default_form_');

require_once 'includes/fundraiser_quick_donate.fundraiser.inc';
require_once 'includes/fundraiser_quick_donate.node_form.inc';
require_once 'includes/fundraiser_quick_donate.springboard_hmac.inc';

/**
 * Implements hook_menu().
 */
function fundraiser_quick_donate_menu() {
  $items = array();

  $items['admin/springboard/options/fundraiser/fundraiser_quick_donate'] = array(
    'title' => 'Quick Donate Settings',
    'description' => 'Settings for quick donations.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fundraiser_quick_donate_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer quickdonate configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/fundraiser_quick_donate.admin.inc',
  );

  $items['admin/springboard/options/fundraiser/fundraiser_quick_donate/autocomplete'] = array(
    'title' => 'Autocomplete for Quick Donation forms',
    'page callback' => 'fundraiser_quick_donate_admin_settings_autocomplete_callback',
    'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/fundraiser_quick_donate.admin.inc',
  );

  $items['admin/springboard/options/fundraiser/fundraiser_quick_donate/card_ids_by_uid'] = array(
    'title' => 'Autocomplete for fetching card ids associated with a user',
    'page callback' => '_fundraiser_quick_donate_admin_get_card_ids_by_uid',
    'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/fundraiser_quick_donate.admin.inc',
  );

  // HMAC token generator page.
  $items['admin/config/system/fundraiser/quick-donate/token-generator'] = array(
    'title' => 'Quick Donate Token Generator',
    'description' => 'Generate quick donate HMAC tokens for testing or use',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fundraiser_quick_donate_token_generator'),
    'access arguments' => array('administer fundraiser quick_donate'),
    'file' => 'includes/fundraiser_quick_donate.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function fundraiser_quick_donate_menu_alter(&$items) {
  if (module_exists('commerce_cardonfile')) {
    $items['user/%user/cards/%commerce_cardonfile/edit'] += array(
      'page callback' => 'fundraiser_quick_donate_form_commerce_cardonfile_card_form',
      'page arguments' => array(3, 1),
    );
  }
  return $items;
}

/**
 * Implements hook_springboard_admin_admin_menu_items_alter().
 */
function fundraiser_quick_donate_springboard_admin_admin_menu_items_alter(&$items) {
  // Settings > Settings > Sustainer Upsell.
  $items['admin/springboard/settings']['_children']['admin/springboard/settings/config']['_children']['admin/springboard/options/fundraiser/fundraiser_quick_donate'] = array(
    'link_path' => 'admin/springboard/options/fundraiser/fundraiser_quick_donate',
    'link_title' => 'Quick Donate Settings',
    'menu_name' => 'springboard_admin_menu',
    'expanded' => 0,
    'customized' => 1,
    'weight' => 0,
  );
}

/**
 * Implements hook_FORM_ID_alter().
 *
 * Used to add a quick donation related message.
 */
function fundraiser_quick_donate_form_user_login_alter(&$form, &$form_state) {
  drupal_session_start();
  $destination = drupal_get_destination();
  if (isset($_SESSION['quickdonate']) && $_SESSION['quickdonate'] && !empty($destination)) {
    $destination = $destination['destination'];
    $form['#prefix'] = t("Please login to verify your identity. Or if you'd prefer, you may !proceed.", array(
      '!proceed' => l(t('proceed to the full donation form'), $destination),
    ));
  }
}

/**
 * Implements hook_node_load().
 */
function fundraiser_quick_donate_node_load($nodes, $types) {
  $fundraiser_types = fundraiser_get_donation_types();
  $fundraiser_types = array_filter($fundraiser_types);
  $fundraiser_types = array_keys($fundraiser_types);
  if (!array_intersect($fundraiser_types, $types)) {
    return;
  }

  foreach ($nodes as $nid => $node) {
    _fundraiser_quick_donate_attach_quick_donate_fields($nodes[$nid]);
  }
}

/**
 * Implements hook_node_prepare().
 */
function fundraiser_quick_donate_node_prepare($node) {
  if (!fundraiser_is_donation_type($node->type)) {
    return;
  }

  _fundraiser_quick_donate_attach_quick_donate_fields($node);
}

/**
 * Helper function to attach quick donation settings to a node.
 *
 * @param object $node
 *   The node object.
 *
 * @return object
 *   The modified node object.
 */
function _fundraiser_quick_donate_attach_quick_donate_fields(&$node) {
  // Return early if node already has quickdonate information.
  if (isset($node->quickdonate)) {
    return array();
  }

  if (!isset($node->nid) || empty($results = db_query('SELECT quickdonate_optin_message_new_user, quickdonate_help_message_new_user_format, quickdonate_help_message_new_user, quickdonate_optin_message_existing_user, quickdonate_help_message_existing_user_format, quickdonate_help_message_existing_user, quickdonate_login_message, quickdonate_login_link_message FROM {fundraiser_quick_donate} WHERE fundraiser_nid = :nid', array(
    ':nid' => $node->nid,
  ))->fetchAssoc())) {
    // Set default values.
    $results = array(
      'quickdonate_optin_message_new_user' => variable_get('fundraiser_quick_donate_default_optin_message_new_user', 'Save this @type for future use?'),
      'quickdonate_help_message_new_user_format' => 'filtered_html',
      'quickdonate_help_message_new_user' => variable_get('fundraiser_quick_donate_default_help_message_new_user', 'Save your @type details and donate faster next time. We may email you from time to time with quick donate opportunities. You can update your @type details or cancel your enrollment at any time.'),
      'quickdonate_optin_message_existing_user' => variable_get('fundraiser_quick_donate_default_optin_message_existing_user', 'Update your saved @type?'),
      'quickdonate_help_message_existing_user_format' => 'filtered_html',
      'quickdonate_help_message_existing_user' => variable_get('fundraiser_quick_donate_default_help_message_existing_user', 'Check this box if you want to make this new @type your default for future donations.'),
      'quickdonate_login_message' => variable_get('fundraiser_quick_donate_default_login_message', t('Already have a saved @type?')),
      'quickdonate_login_link_message' => variable_get('fundraiser_quick_donate_default_login_link_message', t('Click here to login')),
      'quickdonate' => FALSE,
    );
  }
  else {
    $results['quickdonate'] = TRUE;
  }

  foreach ($results as $key => $result) {
    $node->{$key} = $result;
  }

  return $node;
}

/**
 * Implements hook_node_insert().
 */
function fundraiser_quick_donate_node_insert($node) {
  if (!empty($node->quickdonate)) {
    $fields = array(
      'fundraiser_nid' => $node->nid,
      'quickdonate_optin_message_new_user' => $node->quickdonate_optin_message_new_user,
      'quickdonate_help_message_new_user' => !is_array($node->quickdonate_help_message_new_user) ? $node->quickdonate_help_message_new_user : $node->quickdonate_help_message_new_user['value'],
      'quickdonate_help_message_new_user_format' => isset($node->quickdonate_help_message_new_user_format) ? $node->quickdonate_help_message_new_user_format : $node->quickdonate_help_message_new_user['format'],
      'quickdonate_optin_message_existing_user' => $node->quickdonate_optin_message_existing_user,
      'quickdonate_help_message_existing_user' => !is_array($node->quickdonate_help_message_existing_user) ? $node->quickdonate_help_message_existing_user : $node->quickdonate_help_message_existing_user['value'],
      'quickdonate_help_message_existing_user_format' => isset($node->quickdonate_help_message_existing_user_format) ? $node->quickdonate_help_message_existing_user_format : $node->quickdonate_help_message_existing_user['format'],
      'quickdonate_login_message' => $node->quickdonate_login_message,
      'quickdonate_login_link_message' => $node->quickdonate_login_link_message,
    );

    db_merge('fundraiser_quick_donate')
      ->key(array('fundraiser_nid' => $fields['fundraiser_nid']))
      ->fields($fields)
      ->execute();
  }
}

/**
 * Implements hook_node_delete().
 */
function fundraiser_quick_donate_node_delete($node) {
  if (!empty($node->quickdonate)) {
    db_delete('fundraiser_quick_donate')
      ->condition('fundraiser_nid', $node->nid)
      ->execute();
  }
}

/**
 * Implements hook_payment_method_fields_alter().
 */
function fundraiser_quick_donate_payment_method_fields_alter(&$element, &$payment_method, &$context) {
  if (array_key_exists('bank_name', $element)) {
    $keys = array(
      'bank_name' => array(),
      'routing_number' => array(),
      'account_number' => array(),
      'confirm_account_number' => array(),
      'account_type' => array(),
    );
  }
  else {
    $keys = array(
      'card_number' => array(),
      'expiration_date' => array(
        'card_expiration_year' => array(),
      ),
      'card_cvv' => array(),
      'card_type' => array(),
    );
  }

  // The way this is set up in fundraiser_commerce, it assumes that all payment
  // fields will be required. We need to change that by copying the #states
  // value in the parent element to each applicable child element, then unset
  // the #states element in the parent.
  _fundraiser_quick_donate_payment_method_fields_alter_states($element['#states'], $keys, $element);

  $element['quickdonate'] = array(
    '#type' => 'hidden',
    '#value' => FALSE,
    '#states' => array(
      'visible' => $element['#states']['visible'],
    ),
  );
  unset($element['quickdonate']['#states']['required']);
  unset($element['#states']['required']);
}

/**
 * Helper function to update the #states property based on provided keys.
 *
 * @param array $states
 *   The original #states value to copy to the each key in $keys.
 * @param array $keys
 *   A multi-dimensional array specifying the keys of the element children to
 *   copy the states for.
 * @param array $element
 *   The form element array.
 */
function _fundraiser_quick_donate_payment_method_fields_alter_states($states, $keys, &$element) {
  foreach ($keys as $key => $value) {
    if (count($value)) {
      _fundraiser_quick_donate_payment_method_fields_alter_states($states, $value, $element[$key]);
    }
    else {
      $element[$key]['#states'] = $states;
    }
  }
}

/**
 * Implements hook_webform_user_save_profile_map_alter().
 */
function fundraiser_quick_donate_webform_user_save_profile_map_alter(&$account, $form, $form_state) {
  if (empty($form['#node']->type) || !fundraiser_is_donation_type($form['#node']->type)) {
    return;
  }

  $values = $form_state['values']['submitted_tree']['payment_information'];
  if (isset($form['#node']->quickdonate) && $form['#node']->quickdonate && $values['payment_fields'][$values['payment_method']]['quickdonate']) {
    $account->field_quick_donate_opt_in = array(
      LANGUAGE_NONE => array(
        0 => array(
          'value' => date("Y-m-d H:i:s"),
          'timezone' => drupal_get_user_timezone(),
          'timezone_db' => 'UTC',
          'date_type' => 'datetime',
        ),
      ),
    );
    // If there was an opt-out date previously, reset it now.
    $account->field_quick_donate_opt_out = array(
      LANGUAGE_NONE => array(
        0 => NULL,
      ),
    );
  }
}

/**
 * Implements hook_webform_user_profile_fields_alter().
 *
 * Used to remove the user profile field for quick donations from webform
 * components, which is a date field. Replaced with a flag in
 * fundraiser_quick_donate_fundraiser_field_info_alter().
 */
function fundraiser_quick_donate_webform_user_profile_fields_alter(&$fields, $node) {
  $fields = array_filter($fields, function($value) {
    return ($value['name'] != 'field_quick_donate_opt_in' && $value['name'] != 'field_quick_donate_opt_out');
  });
}

/**
 * Implements hook_fundraiser_field_info().
 *
 * Used to add a webform component for quick donations.
 */
function fundraiser_quick_donate_fundraiser_field_info_alter(&$fields) {
  $fields['quick_donate_opt_in'] = array(
    '#type' => 'hidden',
    '#name' => 'sbp_quick_donate_opt_in',
    '#title' => 'Quick Donate Opt-in',
  );
  $fields['quick_donate_opt_out'] = array(
    '#type' => 'hidden',
    '#name' => 'sbp_quick_donate_opt_out',
    '#title' => 'Quick Donate Opt-out',
  );
  return $fields;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fundraiser_quick_donate_form_commerce_cardonfile_card_form($card, $user) {
  // Load the cardonfile's quick donation record, return early if empty.
  $qd = _fundraiser_quick_donate_get_payment_info_for_card_id($card->card_id, FALSE);
  if (!empty($qd)) {
    $card_id = $qd['card_id'];
  }
  else {
    $card_id = $card->card_id;
  }

  // Load the user's newest donation for the card's gateway.
  $donation = fundraiser_donation_get_donations_by_uid($user->uid, 1, 'DESC', $qd['gateway'], $card_id);
  if (empty($donation)) {
    return;
  }

  drupal_set_title('Edit Payment Method');

  $data = array(
    'calling module' => 'fundraiser_quick_donate',
    'donation' => $donation,
    'card' => $card,
    'payment_fields' => array(
      'credit' => array(
        'expiration_date' => array(
          'card_expiration_month' => array(
            '#default_value' => $card->card_exp_month,
          ),
          'card_expiration_year' => array(
            '#default_value' => $card->card_exp_year,
          ),
        ),
      ),
    ),
  );

  return drupal_get_form('fundraiser_update_billing_form', $data);
}

/**
 * Implements hook_fundraiser_update_billing_form_alter().
 *
 * Updates the billing update form on cardonfile card edit pages to redirect
 * back to the cards overview page.
 */
function fundraiser_quick_donate_fundraiser_update_billing_form_postprocess($form, $form_state) {
  $form['actions']['submit']['#submit'][] = '_fundraiser_quick_donate_check_qd_default';
  return $form;
}

/**
 * Submit handler to check if the quick donate card needs to be updated.
 */
function _fundraiser_quick_donate_check_qd_default($form, $form_state) {
  $donation = $form_state['donation'];
  $card = $form_state['card'];
  $values = $form_state['values'];

  // If the card number is the same, don't do anything.
  if ($card->card_number == $values['credit_card']['number']) {
    return;
  }

  $cardonfile_fields = array(
    'card_number' => substr($values['credit_card']['number'], -4),
    'card_exp_month' => $values['credit_card']['exp_month'],
    'card_exp_year' => $values['credit_card']['exp_year'],
  ) + array('instance_id' => $donation->gateway['id'], 'uid' => $donation->uid);

  $new_card = _fundraiser_commerce_cardonfile_match($cardonfile_fields, TRUE);

  if (empty($new_card)) {
    return;
  }

  // If the card number has changed, we need to check if the card was QD enabled
  // and if so, set the new card to QD enabled and disable the old one.
  $qd = db_query('SELECT * FROM {fundraiser_quick_donate_cardonfile} WHERE card_id = :card_id AND uid = :uid AND status = 1', array(
    ':card_id' => $card->card_id,
    ':uid' => $values['uid'],
  ))->fetch();

  if (empty($qd)) {
    return;
  }

  db_update('fundraiser_quick_donate_cardonfile')
    ->fields(array(
      'status' => 0,
    ))
    ->condition('card_id', $card->card_id, '=')
    ->execute();
  db_merge('fundraiser_quick_donate_cardonfile')
    ->key(array('card_id' => $new_card->card_id))
    ->fields(array(
      'status' => 1,
      'uid' => $donation->uid,
      'optin_date' => $qd->optin_date,
      'did' => $qd->did,
      'ms' => $qd->ms,
      'cid' => $qd->cid,
      'nid' => $qd->nid,
      'gateway' => $donation->gateway['id'],
    ))
    ->condition('card_id', $new_card->card_id, '=')
    ->execute();

  $user = user_load($donation->uid);
  module_invoke_all('fundraiser_quick_donate_optin_update', $user, $donation, $card->card_id, $new_card->card_id);
}

/**
 * Implements hook_fundraiser_update_billing_form_alter().
 *
 * Updates the billing update form on cardonfile card edit pages to redirect
 * back to the cards overview page.
 */
function fundraiser_quick_donate_fundraiser_update_billing_form__fundraiser_quick_donate__alter(&$form, $form_state) {
  $card = $form_state['card'];

  $title = array(
    '#type' => 'html_tag',
    '#tag' => 'h4',
    '#value' => t('You are editing billing information for:'),
  );
  $title = drupal_render($title);
  $card_title = array(
    '#type' => 'html_tag',
    '#tag' => 'span',
    '#value' => format_string('@type - XXXX-XXXX-XXXX-@number', array(
      '@type' => strtoupper($card->card_type),
      '@number' => $card->card_number,
    )),
  );
  $card_title = drupal_render($card_title);
  $expires = array(
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => t('Expires: @month/@year', array(
      '@month' => sprintf('%02d', $card->card_exp_month),
      '@year' => $card->card_exp_year,
    )),
  );
  $expires = drupal_render($expires);
  $form = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => $title . $card_title . $expires,
    ),
  ) + $form;

  $gateway_type = $form['payment_method']['#value'];
  $enabled = db_query('SELECT card_id FROM {fundraiser_quick_donate_cardonfile} WHERE card_id = :card_id AND status = 1', array(
    ':card_id' => $card->card_id,
  ))->fetchField();

  $form['payment_fields'][$gateway_type]['quickdonate'] = array(
    '#type' => 'checkbox',
    '#title' => '&nbsp;' . t('Use this card for Quick Donate'),
    '#default_value' => !!$enabled,
  );

  $form['actions']['submit']['#submit'][] = '_fundraiser_quick_donate_set_new_qd_cof';

  $form['actions']['cancel'] = array(
    '#markup' => '<span class="cancel"> or ' . l(t('Cancel'), 'user/' . $card->uid . '/cards') . '</span>',
    '#weight' => 20,
  );
}

/**
 * Submission handler to update {fundraiser_quick_donate_cardonfile}.
 *
 * Updated when user selects "Make this my default Quick Donate card" on the
 * user's stored cards page.
 *
 * @see fundraiser_quick_donate_fundraiser_update_billing_form__fundraiser_quick_donate__alter()
 * @see fundraiser_update_billing_form()
 */
function _fundraiser_quick_donate_set_new_qd_cof(&$form, &$form_state) {
  // Check if the expiration date changed. If it has and this is a recurring
  // series, we need to add the submission handler from the
  // fundraiser_sustainers module to the submission handler array.
  if (module_exists('fundraiser_sustainers') && property_exists($form_state['donation'], 'recurring')) {
    $exp_month_match = $form['payment_fields']['credit']['expiration_date']['card_expiration_month']['#default_value'] == $form_state['input']['payment_fields']['credit']['expiration_date']['card_expiration_month'];
    $exp_year_match = $form['payment_fields']['credit']['expiration_date']['card_expiration_year']['#default_value'] == $form_state['input']['payment_fields']['credit']['expiration_date']['card_expiration_year'];
    if (!$exp_month_match || !$exp_year_match) {
      $form_state['values']['master_did'] = $form_state['donation']->recurring->master_did;
      fundraiser_sustainers_update_billing_form_submit($form, $form_state);
    }
  }

  $values = $form_state['values'];
  $payment_fields = $values['payment_fields'];
  $payment_method = $values['payment_method'];

  // If quickdonate is not true the user may be opting this card out.
  if (!$payment_fields['credit']['quickdonate']) {
    fundraiser_quick_donate_opt_out_card($values['uid'], $form_state['card']->card_id);
  }

  // First reset all existing cards' status to 0.
  db_query('UPDATE {fundraiser_quick_donate_cardonfile} SET status = 0 WHERE uid = :uid', array(
    ':uid' => $values['uid'],
  ));

  // If the checkbox was left unchecked, we can return early.
  if (empty($payment_fields[$payment_method]['quickdonate'])) {
    return;
  }

  $user = user_load($values['uid']);
  $did = NULL;

  // Check if the card has a corresponding record in
  // {fundraiser_quick_donate_cardonfile}, if it does just update that one.
  // Otherwise we'll need to create one.
  $results = db_query('SELECT card_id, did FROM {fundraiser_quick_donate_cardonfile} WHERE card_id = :card_id ORDER BY optin_date LIMIT 1', array(
    ':card_id' => $form_state['card']->card_id,
  ))->fetchAllKeyed();
  $did = reset($results);

  if (empty($results)) {
    // Need a node id, query the table for any pre-existing ones the user has
    // opted into.
    $nid = db_query('SELECT nid FROM {fundraiser_quick_donate_cardonfile} WHERE uid = :uid LIMIT 1', array(
      ':uid' => $values['uid'],
    ))->fetchField();

    // If the user isn't currently opted into any quick donation forms, select
    // one from {fundraiser_quick_donate}.
    if (empty($nid)) {
      $nid = db_query('SELECT fundraiser_nid FROM {fundraiser_quick_donate} LIMIT 1')->fetchField();
    }

    // If no quick donation forms exist, we'll need to exit prematurely.
    if (empty($nid)) {
      return;
    }

    $did = db_query('SELECT did FROM fundraiser_donation WHERE nid = :nid AND uid = :uid LIMIT 1', array(
      ':nid' => $nid,
      ':uid' => $values['uid'],
    ))->fetchField();

    // Set all existing cards to status=0.
    db_query('UPDATE {fundraiser_quick_donate_cardonfile} SET status = 0 WHERE uid = :uid', array(
      ':uid' => $values['uid'],
    ));

    // Set the opted in card to status=1. Using db_merge in case card doesn't
    // exist in table yet.
    db_insert('fundraiser_quick_donate_cardonfile')
      ->fields(array(
        'uid' => $values['uid'],
        'status' => 1,
        'card_id' => $form_state['card']->card_id,
        'optin_date' => time(),
        'ms' => 'default_ms',
        'cid' => NULL,
        'nid' => $nid,
        'did' => $did,
        'gateway' => $form_state['card']->instance_id,
      ))
      ->execute();
  }
  else {
    db_query('UPDATE {fundraiser_quick_donate_cardonfile} SET status = 1, optin_date = :time WHERE card_id = :card_id', array(
      ':time' => time(),
      ':card_id' => $form_state['card']->card_id,
    ));
  }

  if (!empty($did)) {
    $donation = fundraiser_donation_get_donation($did);
    module_invoke_all('fundraiser_quick_donate_optin_create', $user, $donation, $form_state['card']->card_id);
  }
}

/**
 * Returns a user's quick donate card or FALSE if they have none.
 *
 * @param int $uid
 *   The id of the user whose quick donate card you want to retreive.
 */
function fundraiser_quick_donate_get_default_card($uid) {
  return db_query('SELECT card_id FROM {fundraiser_quick_donate_cardonfile} WHERE status = 1 and uid = :uid', array(':uid' => $uid))->fetchField();
}

/**
 * Helper function to invoke a hook when a card is opted out of Quick Donate.
 *
 * Whenever a card is taken out of QD eligility, either by explicit opting out
 * or by deletion, check if it was the QD default and if so make opt-out-related
 * updates.
 *
 * @param int $uid
 *   The user's uid.
 * @param int $card_id
 *   The card's id.
 *
 * @throws \Exception
 */
function fundraiser_quick_donate_opt_out_card($uid, $card_id) {
  // See if the user currently has a default card.
  $default_card = fundraiser_quick_donate_get_default_card($uid);
  if ($default_card && $default_card == $card_id) {
    // Update the user, setting the opt-out date.
    $account = user_load($uid);
    $account->field_quick_donate_opt_out = array(
      LANGUAGE_NONE => array(
        0 => array(
          'value' => date("Y-m-d H:i:s"),
          'timezone' => drupal_get_user_timezone(),
          'timezone_db' => 'UTC',
          'date_type' => 'datetime',
        ),
      ),
    );
    user_save($account);
    // Invoke quick donate opt-out hook.
    module_invoke_all('fundraiser_quick_donate_optout', $card_id, $uid);
  }
}

/**
 * Implements hook_entity_presave().
 *
 * If the 'card_number' session is set, we'll know that the card number is being
 * updated, and to update the cardonfile entity before it's saved.
 *
 * This function is needed because the cardonfile module doesn't tell us when
 * it's updating a card, or what the new card values are.
 */
function fundraiser_quick_donate_entity_presave($entity, $type) {
  $args = arg();
  if ($type == 'commerce_cardonfile' && isset($args[2]) && $args[2] == 'cards' && isset($_SESSION['card_number']) && strlen($_SESSION['card_number']) > 4) {
    $entity->card_number = substr($_SESSION['card_number'], -4);
    unset($_SESSION['card_number']);
  }
}

/**
 * Implements hook_entity_delete().
 */
function fundraiser_quick_donate_entity_delete($entity, $type) {
  if ($type == 'commerce_cardonfile') {
    fundraiser_quick_donate_opt_out_card($entity->uid, $entity->card_id);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove the Quick Donate Opt In and Opt Out fields from appearing on the user edit form.
 */
function fundraiser_quick_donate_form_user_profile_form_alter(&$form, $form_state) {
  unset($form['field_quick_donate_opt_in']);
  unset($form['field_quick_donate_opt_out']);
}

/**
 * Implements hook_webform_user_send_mail_alter().
 */
function fundraiser_quick_donate_webform_user_send_mail_alter(&$options) {
  if (empty($options['parameters'])) {
    return;
  }
  $params = $options['parameters'];

  // If the account password is already set, we can return early.
  if (!empty($params['account']->pass)) {
    return;
  }

  // Since this is coming from the webform_user module, and if this is a Quick
  // Donation, set the email to send regardless of what the node's settings are.
  if (isset($params['form_state']['values']['submitted_tree']['payment_information'])) {
    $payment_info = $params['form_state']['values']['submitted_tree']['payment_information'];
    if (isset($payment_info['payment_method']) && isset($payment_info['payment_fields'][$payment_info['payment_method']])) {
      $payment_method = $payment_info['payment_fields'][$payment_info['payment_method']];
      if (!empty($payment_method['quickdonate'])) {
        $options['send'] = TRUE;
      }
    }
  }
}

/**
 * Helper function to return the QD record for the specified card id.
 *
 * @param int $card_id
 *   The card ID.
 *
 * @return array
 *   The QD field record.
 */
function _fundraiser_quick_donate_get_payment_info_for_card_id($card_id, $status = TRUE) {
  $query = db_select('fundraiser_quick_donate_cardonfile', 'fqdc')
    ->fields('fqdc')
    ->condition('card_id', $card_id, '=');
  if ($status) {
    $query->condition('status', TRUE, '=');
  }
  return $query->execute()->fetchAssoc();
}

/**
 * Implements hook_fundraiser_commerce_cardonfile_used_by().
 *
 * Used to inform fundraiser_commerce_cardonfile if the card is used for Quick
 * Donations.
 */
function fundraiser_quick_donate_fundraiser_commerce_cardonfile_used_by($card_id) {
  $result = _fundraiser_quick_donate_get_payment_info_for_card_id($card_id);
  if (empty($result)) {
    return;
  }
  return t('Quick Donate');
}

/**
 * Implements hook_user_view_alter().
 *
 * Re-weight the profile fields so they appear in the correct order.
 */
function fundraiser_quick_donate_user_view_alter(&$build) {
  $ordered_fields = array(
    'first_name',
    'last_name',
    'address',
    'address_line_2',
    'city',
    'state',
    'country',
  );
  foreach ($ordered_fields as $weight => $field) {
    $build['sbp_' . $field]['#weight'] = $weight;
  }
  $build['summary']['#weight'] = $weight++;
}

/**
 * Implements hook_field_extra_fields_display_alter().
 *
 * Moves the summary field for the user profile so that it appears below every-
 * thing else.
 */
function fundraiser_quick_donate_field_extra_fields_display_alter(&$displays, $context) {
  if (!empty($displays['summary'])) {
    $displays['summary']['weight'] = 8;
  }
}
