<?php
/**
 * @file
 * Module file for fundraiser_quick_donate.
 */

define('FUNDRAISER_QUICK_DONATE_DEFAULT_FORM_PREFIX', 'fundraiser_quick_donate_default_form_');

require_once __DIR__ . '/includes/fundraiser_quick_donate.fundraiser.inc';
require_once __DIR__ . '/includes/fundraiser_quick_donate.node_form.inc';

/**
 * Implements hook_menu().
 */
function fundraiser_quick_donate_menu() {
  $items = array();

  $items['admin/springboard/options/fundraiser/fundraiser_quick_donate'] = array(
    'title' => 'Quick Donate Settings',
    'description' => 'Settings for quick donations.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fundraiser_quick_donate_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer quickdonate configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/fundraiser_quick_donate.admin.inc',
  );

  $items['admin/springboard/options/fundraiser/fundraiser_quick_donate/autocomplete'] = array(
    'title' => 'Autocomplete for cities',
    'page callback' => 'fundraiser_quick_donate_admin_settings_autocomplete_callback',
    'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/fundraiser_quick_donate.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function fundraiser_quick_donate_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'fundraiser_quick_donate') . '/includes/views',
  );
}

/**
 * Implements hook_FORM_ID_alter().
 *
 * Used to add a quick donation related message.
 */
function fundraiser_quick_donate_form_user_login_alter(&$form, &$form_state) {
  drupal_session_start();
  $destination = drupal_get_destination();
  if (isset($_SESSION['quickdonate']) && $_SESSION['quickdonate'] && !empty($destination)) {
    $destination = $destination['destination'];
    $form['#prefix'] = t("Please login to verify your identity. Or if you'd prefer, you may !proceed.", array(
      '!proceed' => l(t('proceed to the full donation form'), $destination),
    ));
  }
}

/**
 * Implements hook_node_load().
 */
function fundraiser_quick_donate_node_load($nodes, $types) {
  $fundraiser_types = fundraiser_get_donation_types();
  $fundraiser_types = array_filter($fundraiser_types);
  $fundraiser_types = array_keys($fundraiser_types);
  if (!array_intersect($fundraiser_types, $types)) {
    return;
  }

  foreach ($nodes as $nid => $node) {
    _fundraiser_quick_donate_attach_quick_donate_fields($nodes[$nid]);
  }
}

/**
 * Implements hook_node_prepare().
 */
function fundraiser_quick_donate_node_prepare($node) {
  if (!fundraiser_is_donation_type($node->type)) {
    return;
  }

  _fundraiser_quick_donate_attach_quick_donate_fields($node);
}

/**
 * Helper function to attach quick donation settings to a node.
 *
 * @param object $node
 *   The node object.
 *
 * @return object
 *   The modified node object.
 */
function _fundraiser_quick_donate_attach_quick_donate_fields($node) {
  if (isset($node->nid)) {
    $query = db_select('fundraiser_quick_donate', 'sqd')
      ->fields('sqd', array(
        'quickdonate_optin_message',
        'quickdonate_help_message_format',
        'quickdonate_help_message',
        'quickdonate_login_message',
        'quickdonate_login_link_message',
      ))
      ->condition('fundraiser_nid', $node->nid, '=')
      ->execute();

    if (!$query->rowCount()) {
      return $node;
    }

    $results = $query->fetchAssoc();
    $results['quickdonate'] = TRUE;
  }
  else {
    // Set default values.
    $results = array(
      'quickdonate_optin_message' => variable_get('fundraiser_quick_donate_default_optin_message', 'Save this @type for future use?'),
      'quickdonate_help_message_format' => 'filtered_html',
      'quickdonate_help_message' => variable_get('fundraiser_quick_donate_default_help_message', 'Save your @type details and donate faster next time. We may email you from time to time with quick donate opportunities. You can update your @type details or cancel your enrollment at any time.'),
      'quickdonate_login_message' => variable_get('fundraiser_quick_donate_default_login_message', t('Already have a saved @type?')),
      'quickdonate_login_link_message' => variable_get('fundraiser_quick_donate_default_login_link_message', t('Click here to login')),
      'quickdonate' => FALSE,
    );
  }

  foreach ($results as $key => $result) {
    $node->{$key} = $result;
  }
  return $node;
}

/**
 * Implements hook_payment_method_fields_alter().
 */
function fundraiser_quick_donate_payment_method_fields_alter(&$element, &$payment_method, &$context) {
  $element['quickdonate'] = array(
    '#type' => 'hidden',
    '#value' => 'false',
  );
}

/**
 * Implements hook_webform_user_save_profile_map_alter().
 */
function fundraiser_quick_donate_webform_user_save_profile_map_alter(&$account, $form, $form_state) {
  $values = $form_state['values']['submitted_tree']['payment_information'];
  if (isset($form['#node']->quickdonate) && $form['#node']->quickdonate && $values['payment_fields'][$values['payment_method']]['quickdonate']) {
    $account->field_quick_donate_opt_in = array(
      LANGUAGE_NONE => array(
        0 => array(
          'value' => date("Y-m-d H:i:s"),
          'timezone' => drupal_get_user_timezone(),
          'timezone_db' => 'UTC',
          'date_type' => 'datetime',
        ),
      ),
    );
  }
}

/**
 * Implements hook_webform_user_profile_fields_alter().
 *
 * Used to remove the user profile field for quick donations from webform
 * components, which is a date field. Replaced with a flag in
 * fundraiser_quick_donate_fundraiser_field_info_alter().
 */
function fundraiser_quick_donate_webform_user_profile_fields_alter(&$fields, $node) {
  $fields = array_filter($fields, function($value) {
    return $value['name'] != 'field_quick_donate_opt_in';
  });
}

/**
 * Implements hook_fundraiser_field_info().
 *
 * Used to add a webform component for quick donations.
 */
function fundraiser_quick_donate_fundraiser_field_info_alter(&$fields) {
  $fields['quick_donate'] = array(
    '#type' => 'hidden',
    '#name' => 'sbp_quick_donate_opt_in',
    '#title' => 'Quick Donate Opt-in',
  );
  return $fields;
}
