<?php

/**
 * @file
 * Data warehousing functionality for Fundraiser.
 */

/**
 * Implements hook_cron_queue_info()
 */
function fundraiser_data_warehousing_cron_queue_info() {
  $queues['data_warehouse_donation_ids'] = array(
    'worker callback' => 'fundraiser_data_warehousing_send_donation_data',
    'time' => 120,
  );

  return $queues;
}

/**
 * Implements hook_cron()
 */
function fundraiser_data_warehousing_cron() {
  $queue = DrupalQueue::get('data_warehouse_donation_ids');

  $last_update_time = variable_get('fundraiser_data_warehousing_last_update', 0);

  $result = db_select('fundraiser_donation')
      ->fields('fundraiser_donation', array('did'))
      ->condition('created', $last_update_time, '>')
      ->orderBy('did', 'ASC')
      ->execute();

  while ($record = $result->fetchAssoc()) {
    $queue->createItem($record['did']);
  }

  variable_set('fundraiser_data_warehousing_last_update', time());
}

/**
 * Sends an array of formatted donation data to the data warehouse.
 *
 * @param int $donation_id
 *   The ID of the donation to send.
 */
function fundraiser_data_warehousing_send_donation_data($donation_id) {
  $donation = fundraiser_donation_get_donation($donation_id);

  // TODO: Handle extra data for sustainers.

  if (!empty($donation)) {
    $donation_data = fundraiser_data_warehousing_get_formatted_donation_data($donation);
    springboard_data_warehousing_send_data($donation_data, '/one-time');
  }
}

/**
 * Implements hook_fundraiser_sustainers_create_recurring()
 */
function fundraiser_data_warehousing_fundraiser_sustainers_create_recurring($recurring_data) {
  $original_recurring = _fundraiser_sustainers_get_recurring_by_did($recurring_data['did']);
  $recurring_donation = fundraiser_donation_get_donation($recurring_data['did']);

  if (!empty($original_recurring->master_did)) {
    $master_donation = fundraiser_donation_get_donation($original_recurring->master_did);

    $donation_data = fundraiser_data_warehousing_get_formatted_donation_data($master_donation);

    // Overwrite original donation data with of recurring donation data.
    $donation_data['did'] = $recurring_donation->did;
    $donation_data['status'] = $recurring_donation->status;

    // Add sustainer-specific data.
    $donation_data['master_did'] = $original_recurring->master_did;
    $donation_data['next_charge'] = $recurring_data['next_charge'];
    $donation_data['sustainer_key'] = isset($recurring_data['sustainer_key']) ? $recurring_data['sustainer_key'] : NULL;

    springboard_data_warehousing_send_data($donation_data, '/one-time');
  }
}

/**
 * Creates an array of donation data to send to the data warehouse.
 *
 * @param object $donation
 *   The donation object to use as a data source.
 *
 * @return array
 *   Array of donation data.
 */
function fundraiser_data_warehousing_get_formatted_donation_data($donation) {
  $donation_data = array(
    'nid' => $donation->nid,
    'sid' => $donation->sid,
    'uid' => $donation->uid,
    'did' => $donation->did,
    'amount' => $donation->amount,
    'currency' => $donation->currency,
    'first_name' => $donation->donation['first_name'],
    'last_name' => $donation->donation['last_name'],
    'mail' => $donation->donation['mail'],
    'address' => $donation->donation['address'],
    'address_line_2' => $donation->donation['address_line_2'],
    'city' => $donation->donation['city'],
    'country' => $donation->donation['country'],
    'state' => $donation->donation['state'],
    'zip' => $donation->donation['zip'],
    'gateway' => $donation->gateway['id'],
    'txn_id' => $donation->data['txn_id'],
    'status' => $donation->status,
  );

  drupal_alter('fundraiser_data_housing_donation_data', $donation_data);

  return $donation_data;
}
