<?php
/**
 * @file
 * springboard_p2p_campaign.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function springboard_p2p_campaign_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-p2p_campaign-body'
  $field_instances['node-p2p_campaign-body'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Description',
    'required' => 1,
    'settings' => array(
      'display_summary' => 1,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_allow_donor_comments'
  $field_instances['node-p2p_campaign-field_p2p_allow_donor_comments'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'When enabled, constituents will be able to leave an additional comment that can be displayed on the personal campaign page.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 20,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_allow_donor_comments',
    'label' => 'Allow constituent comments',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_ask_amount_edit'
  $field_instances['node-p2p_campaign-field_p2p_ask_amount_edit'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_ask_amount_edit',
    'label' => 'This content can be overridden by a personal campaigner',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 20,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_campaign_action_button'
  $field_instances['node-p2p_campaign-field_p2p_campaign_action_button'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 'Donate now',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 15,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_campaign_action_button',
    'label' => 'Personal campaign action button label',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_campaign_banner'
  $field_instances['node-p2p_campaign-field_p2p_campaign_banner'] = array(
    'bundle' => 'p2p_campaign',
    'deleted' => 0,
    'description' => 'Upload a campaign banner. Suggested size is 1170 x 240 pixels.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'p2p_campaign_image_slideshow',
        ),
        'type' => 'image',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_campaign_banner',
    'label' => 'Campaign banner',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => 'p2p-campaign-banner',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '2 MB',
      'max_resolution' => '',
      'min_resolution' => '800x240',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_campaign_goals'
  $field_instances['node-p2p_campaign-field_p2p_campaign_goals'] = array(
    'bundle' => 'p2p_campaign',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 23,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_campaign_goals',
    'label' => 'Goals',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'springboard_p2p_fields',
      'settings' => array(),
      'type' => 'springboard_p2p_fields_campaign_goals_widget',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_campaign_slider'
  $field_instances['node-p2p_campaign-field_p2p_campaign_slider'] = array(
    'bundle' => 'p2p_campaign',
    'deleted' => 0,
    'description' => 'Upload a slideshow image. The minimum size should be 1170 x 360 pixels.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_campaign_slider',
    'label' => 'Landing page slider',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => 'p2p-campaign-slider',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '2 MB',
      'max_resolution' => '',
      'min_resolution' => '800x360',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 16,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_campaign_thumbnail'
  $field_instances['node-p2p_campaign-field_p2p_campaign_thumbnail'] = array(
    'bundle' => 'p2p_campaign',
    'deleted' => 0,
    'description' => 'Upload a campaign Thumbnail. The minimum size should be 400 x 240 pixels.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_campaign_thumbnail',
    'label' => 'Campaign thumbnail',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => 'p2p-campaign-thumbnail',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '2 MB',
      'max_resolution' => '',
      'min_resolution' => '400x240',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 16,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_campaigns_approval'
  $field_instances['node-p2p_campaign-field_p2p_campaigns_approval'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'This setting cannot be changed after campaign creation.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 17,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_campaigns_approval',
    'label' => 'Personal campaigns require approval',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_category'
  $field_instances['node-p2p_campaign-field_p2p_category'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => 1,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_category',
    'label' => 'Category',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_expiration_message'
  $field_instances['node-p2p_campaign-field_p2p_expiration_message'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Set a message to show when the campaign expires.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_expiration_message',
    'label' => 'Personal Campaign Expiration Message',
    'required' => 1,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_expiration_required'
  $field_instances['node-p2p_campaign-field_p2p_expiration_required'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 13,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_expiration_required',
    'label' => 'Require personal campaign expiration date',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_external_link'
  $field_instances['node-p2p_campaign-field_p2p_external_link'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 'no',
      ),
    ),
    'deleted' => 0,
    'description' => 'Choose whether or not this is an external link. ',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_external_link',
    'label' => 'External Link?',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 18,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_feature_pers_campaigns'
  $field_instances['node-p2p_campaign-field_p2p_feature_pers_campaigns'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_feature_pers_campaigns',
    'label' => 'Featured Personal Campaigns',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_help_content'
  $field_instances['node-p2p_campaign-field_p2p_help_content'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter content or HTML which will display at the top of the personal campaign page when a personal campaigner is logged in and on their personal campaign page.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 16,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_help_content',
    'label' => 'Help content for logged-in personal campaigners',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_images'
  $field_instances['node-p2p_campaign-field_p2p_images'] = array(
    'bundle' => 'p2p_campaign',
    'deleted' => 0,
    'description' => 'Upload a personal campaign thumbnail image. Ideal size is 400 x 240 pixels.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 18,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_images',
    'label' => 'Personal campaign images',
    'required' => 0,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => 'p2p-images',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '2 MB',
      'max_resolution' => '',
      'min_resolution' => '400x240',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_images_edit'
  $field_instances['node-p2p_campaign-field_p2p_images_edit'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 27,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_images_edit',
    'label' => 'This content can be overridden by a personal campaigner',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_landing_slider_link'
  $field_instances['node-p2p_campaign-field_p2p_landing_slider_link'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_landing_slider_link',
    'label' => 'Landing page slider optional external link',
    'required' => 0,
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'configurable_title' => 0,
        'rel' => '',
        'target' => '_blank',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'required',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 20,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_landing_slider_text'
  $field_instances['node-p2p_campaign-field_p2p_landing_slider_text'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 11,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_landing_slider_text',
    'label' => 'Landing page slider teaser',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 22,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_org_intro'
  $field_instances['node-p2p_campaign-field_p2p_org_intro'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 24,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_org_intro',
    'label' => 'Organization introduction',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_personal_intro'
  $field_instances['node-p2p_campaign-field_p2p_personal_intro'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => ' ',
        'format' => 'filtered_html',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 25,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_personal_intro',
    'label' => 'Personal campaign introduction',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_personal_intro_edit'
  $field_instances['node-p2p_campaign-field_p2p_personal_intro_edit'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 26,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_personal_intro_edit',
    'label' => 'This content can be overridden by a personal campaigner',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_private_access_message'
  $field_instances['node-p2p_campaign-field_p2p_private_access_message'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'A brief message to display if a user attempts to create a personal campaign without prior authorization.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_private_access_message',
    'label' => 'Authorization required message',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_show_donor_comments'
  $field_instances['node-p2p_campaign-field_p2p_show_donor_comments'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 21,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_show_donor_comments',
    'label' => 'Show constituent comments on personal campaign pages',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_show_donor_scroll'
  $field_instances['node-p2p_campaign-field_p2p_show_donor_scroll'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 22,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_show_donor_scroll',
    'label' => 'Show constituent scroll on personal campaign pages',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_suggested_donation'
  $field_instances['node-p2p_campaign-field_p2p_suggested_donation'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_decimal',
        'weight' => 14,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_suggested_donation',
    'label' => 'Suggested Donation Amount',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '$',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 21,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_video_embed'
  $field_instances['node-p2p_campaign-field_p2p_video_embed'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'This is a YouTube or Vimeo video URL. Example: https://www.youtube.com/watch?v=kJ4CYbCGhLA',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 19,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_video_embed',
    'label' => 'Video embed',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'description_length' => 128,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'video_embed_field',
      'settings' => array(),
      'type' => 'video_embed_field_video',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_video_embed_edit'
  $field_instances['node-p2p_campaign-field_p2p_video_embed_edit'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 28,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_video_embed_edit',
    'label' => 'This content can be overridden by a personal campaigner',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'node-p2p_campaign-field_p2p_webform_fieldset_label'
  $field_instances['node-p2p_campaign-field_p2p_webform_fieldset_label'] = array(
    'bundle' => 'p2p_campaign',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'This will display at the bottom of the form, above the option for users to display their name on the campaign and leave a comment.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 12,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_p2p_webform_fieldset_label',
    'label' => 'Public Support Call-Out',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('A brief message to display if a user attempts to create a personal campaign without prior authorization.');
  t('Allow constituent comments');
  t('Authorization required message');
  t('Campaign banner');
  t('Campaign thumbnail');
  t('Category');
  t('Choose whether or not this is an external link. ');
  t('Description');
  t('Enter content or HTML which will display at the top of the personal campaign page when a personal campaigner is logged in and on their personal campaign page.');
  t('External Link?');
  t('Featured Personal Campaigns');
  t('Goals');
  t('Help content for logged-in personal campaigners');
  t('Landing page slider');
  t('Landing page slider optional external link');
  t('Landing page slider teaser');
  t('Organization introduction');
  t('Personal Campaign Expiration Message');
  t('Personal campaign action button label');
  t('Personal campaign images');
  t('Personal campaign introduction');
  t('Personal campaigns require approval');
  t('Public Support Call-Out');
  t('Require personal campaign expiration date');
  t('Set a message to show when the campaign expires.');
  t('Show constituent comments on personal campaign pages');
  t('Show constituent scroll on personal campaign pages');
  t('Suggested Donation Amount');
  t('This content can be overridden by a personal campaigner');
  t('This is a Youtube or Vimeo video URL. Example: https://www.youtube.com/watch?v=kJ4CYbCGhLA');
  t('This setting cannot be changed after campaign creation.');
  t('This will display at the bottom of the form, above the option for users to display their name on the campaign and leave a comment.');
  t('Upload a campaign Thumbnail. The minimum size should be 400 x 240 pixels.');
  t('Upload a campaign banner. Suggested size is 1170 x 240 pixels.');
  t('Upload a personal campaign thumbnail image. Ideal size is 400 x 240 pixels.');
  t('Upload a slideshow image. The minimum size should be 1170 x 360 pixels.');
  t('Video embed');
  t('When enabled, constituents will be able to leave an additional comment that can be displayed on the personal campaign page.');

  return $field_instances;
}
