<?php

/**
 * @file
 * A test module used as an example for a managed payment gateway.
 *
 */

module_load_include('inc', 'gateway_manager', 'includes/gateway_manager.credit');
/**
 * Implements hook_payment_gateway_managed().
 */
function gm_test_gateway_payment_gateway_managed() {
  $gateways['test_gateway'] = array(
    'id' => 'test_gateway',
    'title' => t('Test Gateway'),
    'description' => t('Process credit card payments through the Test Gateway.'),
    'settings' => NULL,
    'file' => 'gm_test_gateway.gm.inc',
    'payment_methods' => array(
      'credit' => array(
        'label' => t('Credit'),
        'payment_callback' => 'gm_test_gateway_credit_charge',
        'render_callback' => 'gm_test_gateway_credit_webform_render',
        'validate_callback' => 'gm_test_gateway_credit_webform_validate',
        'payment_details_callback' => 'gm_test_gateway_credit_payment_details',
        'recurring' => TRUE,
      ),
      'paypal' => array(
        'label' => t('PayPal'),
        'payment_callback' => 'gm_test_gateway_paypal_charge',
        'render_callback' => 'gm_test_gateway_paypal_webform_render',
        'payment_details_callback' => 'gm_test_gateway_paypal_payment_details',
        'recurring' => FALSE,
      ),
      'direct_debit' => array(
        'label' => t('Direct Debit'),
        'payment_callback' => 'gm_test_gateway_direct_debit',
        'render_callback' => 'gm_test_gateway_direct_debit_render',
        'payment_details_callback' => 'gm_test_gateway_direct_debit_payment_details',
        'recurring' => FALSE,
      ),
    ),
  );

  return $gateways;
}
