<?php

/**
 * @file
 * Focuses on synchronization controls for Salesforce integration.
 */


/**
 * @defgroup salesforce_sync_rules Sync Rule Options with Salesforce
 * @{
 */

// Always replace the recipient record, or record's field, with the incoming
// data.
define('SALESFORCE_SYNC_RULE_ALWAYS', 'always');

// Only insert the incoming data if the recipient record, or record's field, has
// no data.
define('SALESFORCE_SYNC_RULE_BLANK', 'blank');

// Add the incoming data to the end of the current recipient record, or record's
// field.
define('SALESFORCE_SYNC_RULE_APPEND', 'append');

// Never place the incoming data in the recipient record, or record's field.
define('SALESFORCE_SYNC_RULE_NEVER', 'never');

/**
 * @} salesforce_queue_sync_rules
 */


/**
 * @defgroup salesforce_sync_var_default Default Variables for Salesforce Sync
 * @{
 */

// The maximum length of a query string that can be sent to Salesforce.
define('SALESFORCE_SYNC_MAX_QUERY_LENGTH_DEFAULT', 10000);

// The maximum amount of items that can be sent to Salesforce in one call.
define('SALESFORCE_SYNC_MAX_BATCH_SIZE_DEFAULT', 200);

/**
 * @}
 */


/**
 * @defgroup salesforce_sync_item_fail_responses Item fail responses
 * @{
 * When an item fails, one of the following reasons is given for its failure.
 */

// Item failed when it was attempted to be created in Salesforce.
define('SALESFORCE_SYNC_ITEM_FAIL_CREATE', 'Item failed to be created.');

// Item failed when it attempted an upsert in Salesforce.
define('SALESFORCE_SYNC_ITEM_FAIL_UPSERT', 'Item failed to be upserted.');

// Item failed when it attempted an update in Salesforce.
define('SALESFORCE_SYNC_ITEM_FAIL_UPDATE', 'Item failed to be updated.');

// Item failed when it was attempted to be deleted in Salesforce.
define('SALESFORCE_SYNC_ITEM_FAIL_DELETE', 'Item failed to be deleted.');

// Item failed when it was attempted to be undeleted in Salesforce.
define('SALESFORCE_SYNC_ITEM_FAIL_UNDELETE', 'Item failed to be undeleted.');

// The entire batch failed to be processed due to some error with Salesforce.
define('SALESFORCE_SYNC_ITEM_FAIL_BATCH', 'Batch caused Salesforce to throw exception.');

/**
 * @} salesforce_sync_item_fail_responces
 */


/**
 * Implements hook_menu().
 */
function salesforce_sync_menu() {
  $items['admin/config/services/salesforce/salesforce-sync'] = array(
    'title' => 'Syncing',
    'description' => 'Configuration settings for syncing with Salesforce.',
    'page callback' => 'salesforce_sync_admin_page',
    'access arguments' => array('administer salesforce sync'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/salesforce_sync.admin.inc',
  );
  $items['admin/config/services/salesforce/salesforce-sync/config'] = $items['admin/config/services/salesforce/salesforce-sync'];
  $items['admin/config/services/salesforce/salesforce-sync/config']['title'] = 'Sync';
  $items['admin/config/services/salesforce/salesforce-sync/config']['type'] = MENU_DEFAULT_LOCAL_TASK;
  $items['admin/config/services/salesforce/salesforce-sync/config']['weight'] = -10;

  return $items;
}

/**
 * Implements hook_permission().
 */
function salesforce_sync_permission() {
  return array(
    'administer salesforce sync' => array(
      'description' => t('Configure settings for syncing with Salesforce.'),
      'title' => t('Configure Salesforce Sync'),
      'restrict access' => TRUE,
    ),
  );
}
