<?php

function sba_social_action_install() {

  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.install');
  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.install_examples');
  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.twitter_message_install');

  sba_social_action_create_twitter_message_entity();
  _sba_social_action_create_content_type();
  _sba_social_action_create_example_social_action();

}

function sba_social_action_uninstall() {
  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.install');
  _sba_social_action_delete_nodes();
  // Remove fields implemented by this module.
  node_type_delete('sba_social_action');

  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.twitter_message_install');
  _sba_social_action_delete_twitter_fields();
  field_purge_batch(1000);
}

function sba_social_action_update_7001() {
  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.install_fields');
  _sba_social_action_create_node_fields(TRUE);
}

function sba_social_action_update_7003() {
  module_load_include('inc', 'sba_social_action', 'includes/install/sba_social_action.twitter_message_install');
  sba_social_action_create_twitter_message_entity(TRUE);

  $groups = field_group_read_groups(array(
    'entity_type' => 'sba_message',
    'bundle'      => 'sba_social_action_twitter_message',
    'view_mode'   => 'full'
  ));

  $group = $groups['sba_message']['sba_social_action_twitter_message']['form']['group_sba_sample_tweet'];
  $group->children[] = 'field_sba_prepend_target_name';
  field_group_group_save($group);

}
