<?php

/**
 * @file
 *
 * This module is used to generate massive amounts of donations for testing purposes.
 */

/**
 * Implemenation of hook_menu().
 */
function fundraiser_generate_menu() {
  $items['admin/config/development/generate/donation'] = array(
    'title' => 'Generate donations',
    'description' => 'Generate a given number of donations. Optionally configure generation on cron.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fundraiser_generate_donations_form'),
    'access arguments' => array('create test donations'),
  );
  $items['fundraiser/generate/cron/%/%'] = array(
    'title' => t('Cron donation generation'),
    'page callback' => 'fundraiser_generate_cron_create',
    'page arguments' => array(3, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implemenatation of hook_permission().
 */
function fundraiser_generate_permission() {
  return array(
    'create test donations' => array(
      'title' => t('create test donations'),
      'description' => t('Create test donations.'),
    ),
  );
}

/**
 * Generate donations form.
 */
function fundraiser_generate_donations_form($form, &$form_state) {
  $options = _fundraiser_generate_get_forms();
  $types = array(
    'single' => 'Single',
    'recurring' => 'Recurring',
    'random' => 'Random',
  );
  $form['nid'] = array(
    '#type' => 'select',
    '#title' => t('Donation form'),
    '#options' => $options,
  );
  $form['number'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of donations to generate'),
    '#size' => 3,
    '#default_value' => 1,
  );
  $form['type'] = array(
    '#type' => 'radios',
    '#title' => t('Donation type'),
    '#options' => $types,
    '#default_value' => 'single',
  );
  $form['ms'] = array(
    '#type' => 'textfield',
    '#title' => t('Market source'),
  );
  $form['cid'] = array(
    '#type' => 'textfield',
    '#title' => t('Salesforce campaign'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate!'),
  );
  return $form;
}

/**
 * Submission handler.
 */
function fundraiser_generate_donations_form_submit($form, &$form_state) {
  $nid = $form_state['values']['nid'];
  $number_to_create = $form_state['values']['number'];
  $type = $form_state['values']['type'];
  $ms = $form_state['values']['ms'];
  $cid = $form_state['values']['cid'];
  fundraiser_generate_donations($nid, $number_to_create, $type, $ms, $cid);
}

/**
 * Used to generate donations on cron runs.
 */
function fundraiser_generate_cron_create($nid, $count = 1) {
  fundraiser_generate_donations($nid, $count, 'random');
}

/**
 * API function to generate a set of testing donations.
 */
function fundraiser_generate_donations($nid, $count = 1, $type = 'single', $ms = NULL, $cid = NULL) {
  if (empty($nid)) {
    drupal_set_message('You must pass in the donation form node id.');
    return;
  }
  // Ensure that devel_generate code is available.
  module_load_include('inc', 'devel_generate', 'devel_generate');

  // TODO - do this with the process system in fundraiser. No more form execute if possible.
  // Load up the donation form node.
  $donation_form_node = node_load($nid);
  for ($i = 0; $i < $count; $i++) {

    if ($type == 'single') {
      $recurs = FALSE;
    }
    elseif ($type == 'recurring') {
      $recurs = 'recurs';
    }
    else {
      $recurs = rand(0, 1) ? 'recurs' : FALSE;
    }

    // Create some random strings using devel_generate functions.
    $url = parse_url($GLOBALS['base_url']);
    $first_name = devel_generate_word(mt_rand(4, 10)); // From devel_generate.module.
    $last_name = devel_generate_word(mt_rand(3, 11)); // From devel_generate.module.
    $email =  $first_name . '.' . $last_name . '@' . $url['host'];
    $year = date('Y');
    // Build up a bogus form_state to submit.
    $state = array(
      'submitted' => TRUE,
      'clicked_button' => array(
        '#type' => 'submit',
        '#value' => 'Submit',
        '#parents' => array('submit'),
      ),
      'values' => array(
        'op' => t('Submit'),
        'submit' => t('Submit'),
        'form_id' => 'webform_client_form_' . $nid,
        'details' => array(
          'nid' => $nid,
          'sid' => '',
          'uid' => 0,
          'finished' => 0,
          'page_num' => 1,
          'page_count' => 1,
        ),
        'submitted' => array(
          'currency' => 'USD',
          'donation' => array(
            'amount' => _fundraiser_generate_random_ask_amount($nid),
            'other_amount' => '',
          ),
          'donor_information' => array(
            'first_name' => $first_name,
            'last_name' => $last_name,
            'mail' => $email,
          ),
          'billing_information' => array(
            'address' => devel_generate_word(mt_rand(10, 20)), // From devel_generate.module.
            'address_line_2' => '',
            'city' => devel_generate_word(mt_rand(7, 15)), // From devel_generate.module.
            'country' => 'US',
            'state' => 'DC',
            'zip' => mt_rand(11111, 55555),
          ),
          'payment_information' => array(
            'payment_fields' => array(
              'credit' => array(
                'card_number' => '4111111111111111',
                'expiration_date' => array(
                  'card_expiration_month' => mt_rand(1, 12),
                  'card_expiration_year' => mt_rand($year + 1, $year + 3),
                ),
                'card_cvv' => '111',
              ),
            ),
            'recurs_monthly' => array(
              'recurs' => $recurs,
            ),
          ),
          'ms' => $ms,
          'cid' => $cid,
          'referrer' => '',
          'initial_referrer' => '',
        ),
      ),
    );
    // Submit the form.
    drupal_form_submit('webform_client_form_' . $nid, $state, $donation_form_node, NULL, TRUE, FALSE);
  }
}

/**
 * Generates an option list of donation forms on the site.
 */
function _fundraiser_generate_get_forms() {
  $forms = array();
  $result = db_query("SELECT nid, title FROM {node} WHERE type = :type ORDER BY title", array(':type' => 'donation_form'));
  while ($data = $result->fetchObject()) {
    $forms[$data->nid] = $data->title;
  }
  return $forms;
}

/**
 * Generates a random ask amount value().
 */
function _fundraiser_generate_random_ask_amount($nid) {
  // From fundraiser_webform.module.
  $amount_values = _fundraiser_webform_get_extra_by_key($nid, 'amount');
  $amount_values = preg_split('/\n/', trim($amount_values['items']));
  array_pop($amount_values); // Get rid of other for now.
  $values = array();
  foreach ($amount_values as $amount) {
    $split_amount = explode('|', $amount);
    $values[] = $split_amount[0];
  }
  $length = count($values) - 1;
  return $values[rand(0, $length)];
}
