<?php
/**
 * @file
 * Provides content type and config for letters to targets.
 */

/**
 * Implements hook_node_insert
 * 
 * Adds some custom fields to new webforms.
 */
function springboard_letter_node_insert($node) {
  if($node->type == 'springboard_letter') {
    module_load_include('inc', 'webform', 'includes/webform.components');

    //add custom fields for the messages
    $fields[] = array(
      'nid' => $node->nid,
      'form_key' => 'sba_phone',
      'pid' => 0,
      'name' => t('Phone Number'),
      'type' => 'textfield',
      'mandatory' => 1,
      'weight' => 13,
      'email' => 1,
      'extra' => array(
      'description' => t(''),
      ),
    );

    //limit the state field to US states
    $fields[] = array(
        'nid' => $node->nid,
        'form_key' => 'sbp_state',
        'pid' => 0,
        'name' => t('State'),
        'type' => 'select',
        'mandatory' => 1,
        'weight' => 12,
        'email' => 1,
        'extra' => array(
        'options_source' => 'united_states', //may have to remove some.
        'aslist' => 'Y',
        'multiple' => 0,
      ),
    );
    $fields[] = array(
        'nid' => $node->nid,
        'form_key' => 'sbp_zip',
        'pid' => 0,
        'name' => t('Zip Code'),
        'type' => 'textfield',
        'mandatory' => 1,
        'weight' => 13,
        'email' => 1,
        'extra' => array(
        'maxlength' => 5,
      ),
    );

    // Add the component to the Webform.

    foreach ($fields as $field) {
      $cid = webform_component_insert($field);
      //user map the state field
      if ($field['form_key'] == 'sbp_state' || $field['form_key'] == 'sbp_zip') {
            $map = array(
            'nid' => $node->nid,
            'cid' => $cid,
            'map_id' => $field['form_key'],
          );
          drupal_write_record('webform_user_component_map', $map);
      }
    }
  }
}

/**
 * Implements hook_webform_user_profile_fields_alter
 *
 */
function springboard_letter_webform_user_profile_fields_alter(&$fields, $node) {
  if($node->type == 'springboard_letter') {
    foreach ($fields as $index => $profile_field) {
      //make all fields except address2 mandatory
      if ($profile_field['name'] != 'sbp_address_line_2'){
        $fields[$index]['mandatory'] = 1;
      }
      //setup removal of non-US provinces
      if ($profile_field['name'] == 'sbp_state'){
        unset($fields[$index]);
      }
      //remove zip
      if ($profile_field['name'] == 'sbp_zip'){
        unset($fields[$index]);
      }
      //move email field lower
      if ($profile_field['name'] == 'mail'){
        $fields[$index]['weight'] = 14;
      }
    } 
  }
}

/**
 * Implements hook_form_alter
 * 
 * Add our submit handler.
 */
// function springboard_letter_form_alter(&$form, &$form_state, $form_id) {
//   if(isset($form['#node']) && $form['#node']->type == 'springboard_letter') {
//     $pos = strpos($form_id, 'client_form');
//     if($pos !== FALSE) {
//       $form['#submit'][] = 'springboard_letter_submit';
//     }
//   }
// }


