<?php

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_paywithmybank_commerce_payment_method_info() {
  $payment_methods = array();
  $payment_methods['commerce_paywithmybank_bank'] = array(
    'base' => 'commerce_paywithmybank_bank',
    'title' => t('PayWithMyBank Bank Account'),
    'short_title' => t('PayWithMyBank'),
    'display_title' => t('Bank Account'),
    'description' => t('Integrates PayWithMyBank for Commerce transactions.'),
    'cardonfile' => array(
      'charge callback' => 'commerce_paywithmybank_bank_cardonfile_charge',
      'update callback' => 'commerce_paywithmybank_bank_cardonfile_update',
      'delete callback' => 'commerce_paywithmybank_bank_cardonfile_delete',
    ),
  );

  return $payment_methods;
}

/**
 * Payment method callback: settings form.
 */
function commerce_paywithmybank_bank_settings_form($settings = NULL) {
  $form = array();
  $form['commerce_paywithmybank_settings_access_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Access ID'),
    '#default_value' => isset($settings['commerce_paywithmybank_settings_access_id']) ? $settings['commerce_paywithmybank_settings_access_id'] : '',
  );

  $form['commerce_paywithmybank_settings_access_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Access Key'),
    '#default_value' => isset($settings['commerce_paywithmybank_settings_access_key']) ? $settings['commerce_paywithmybank_settings_access_key'] : '',
  );

  return $form;
}

/**
 * Payment method callback: checkout form.
 */
function commerce_paywithmybank_bank_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  
}

/**
 * Payment method callback: checkout form validation.
 */
function commerce_paywithmybank_bank_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  
}

/**
 * Payment method callback: checkout form submission.
 */
function commerce_paywithmybank_bank_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  
}

function commerce_paywithmybank_bank_cardonfile_charge($payment_method, $card_data, $order, $charge = NULL) {
  
}

function commerce_paywithmybank_bank_cardonfile_update($form, &$form_state, $payment_method, $card_data) {
  
}

function commerce_paywithmybank_bank_cardonfile_delete() {
  
}
