<?php

/**
 * @file
 * Field management functions for the fundraiser module
 */

/**
 * Implements hook_menu_alter().
 */
function fundraiser_webform_menu_alter(&$items) {
  // Move fundraisers confirmation paths to webform menu paths, for UI.
  $items['node/%node/webform/confirmations'] = $items['node/%node/fundraiser/confirmations'];
  $items['node/%node/webform/confirmations']['type'] = MENU_LOCAL_TASK;
  // Remove fundraiser tab, we don't want it if we're using webform.
  unset($items['node/%node/fundraiser']);
  unset($items['node/%node/fundraiser/confirmations']);
  // Alter some built-in webform menu items.
  $items['node/%webform_menu/webform/configure']['access callback'] = 'fundraiser_webform_configure_access';
  $items['node/%webform_menu/webform/configure']['access arguments'] = array('update', 1);
}

/**
 * Menu access callback. Permission check for donation form settings tab.
 */
function fundraiser_webform_configure_access($perm, $node) {
  // Don't show the 'Form settings' tab on donation forms.
  if (_fundraiser_is_donation_type($node->type)) { // From fundraiser.module.
    return FALSE;
  }
  else {
    return node_access($perm, $node);
  }
}

/**
 * Implements hook_webform_submission_presave().
 */
function fundraiser_webform_webform_submission_presave($node, &$submission) {
  // Remove any non-component form fields from the submitted data.
  unset($submission->data['']);
  // Remove senstive form data before the submission is saved to the database.
  if (_fundraiser_is_donation_type($node->type)) { // From fundraiser.module.
    $results = _fundraiser_webform_get_components_by_keys($node->nid, array('card_number', 'card_cvv', 'card_expiration_date'));
    foreach ($results as $result) {
      // Set sensitive info to NULL.
      $submission->data[$result->cid]['value'][0] = NULL;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
// Alter the webform component delete form to prevent the deletion of required fundraiser fields
// Why not handle this by removing delete options from the interface? Because edit/delete operations are added at theme layer.
// Unfortunately the theme layer adds the values and immediately renders, negating any chance for us to make changes.
// In order to remove delete properly, we will need a patch in webform addressing this issue.
// TODO look into using preprocess to intercept?
function fundraiser_webform_form_webform_component_delete_form_alter(&$form, &$form_state, $form_id) {
  // Make sure we are dealing with a donation form.
  if (_fundraiser_is_donation_type($form['node']['#value']->type)) { // From fundraiser.module.
    // Check vs. required fields to make sure we can't delete them.
    $required_fields = _fundraiser_field_info();
    // TODO Locate each field, and see which one is flagged as required. If required, deny delete.
    $cid = $form['component']['#value']['cid'];
    $component = $form['node']['#value']->webform['components'][$cid];
    // Check to see if the form_key is in our required fields array
    if (in_array($component['form_key'], $required_fields)) {
      $message = t('<strong>!name</strong> is a required fundraiser field and cannot be deleted from this form.',
        array('!name' => $component['name']));
      $form['description']['#markup'] = $message;
      unset($form['actions']['submit']);
    }
  }
}

/**
 * Implements hook_form_alter().
 * Why hook_form_alter and not hook_form_FORM_ID_alter? Because webform's form id varies: webform_client_form_NID.
 */
function fundraiser_webform_form_alter(&$form, $form_state, $form_id) {
  // Alter the webform client form.
  if (strstr($form_id, 'webform_client_form') !== FALSE) {
    // Handle donation form edit submission pg.
    if (_fundraiser_is_donation_type($form['#node']->type) && arg(2) == 'submission') { // From fundraiser.module.
      fundraiser_webform_submission_display($form, $form_state);
    }
    // Handle the donation form display.
    if (_fundraiser_is_donation_type($form['#node']->type)  && arg(2) != 'submission') { // From fundraiser.module.
      // From fundraiser.module, calls hooks to create form and submission paths.
      $form = fundraiser_donation_form($form, $form_state); // From fundraiser.module.
    }
  }
  return $form;
}

/**
 * Form, alters the display of webform submissions to prevent edits / display of confusing info.
 */
function fundraiser_webform_submission_display(&$form, &$form_state) {
  // Set up a view only display of the donation amount.
  if ('other' != $form['submitted']['donation']['amount']['#default_value']) {
    $amount = $form['submitted']['donation']['amount']['#default_value'];
  }
  else {
    $amount = $form['submitted']['donation']['other_amount']['#default_value'];
  }
  // Add new fields.
  $form['submitted']['donation']['display_amount'] = array(
    '#markup' => '<div class="form-item"><label>' . t('Donation Amount') .
      ':</label>' . '$' . number_format($amount, 2) . '</div>', // TODO this should be updated for an international audience.
  );
  // Show whether or not it's a recurring donation
  // TODO In the future we should work out a way to move this administractive UI into fundraiser, to allow the
  // reference to recurssion to move entirely out to sustainers, and abstract the display of field data for the
  // webform user. As it stands, for now this remains here.
  if (isset($form['submitted']['credit_card_information']['recurs_monthly'])) {
    $recurs = t('No');
    if (isset($form['submitted']['credit_card_information']['recurs_monthly']['#default_value'][0])
      && ($form['submitted']['credit_card_information']['recurs_monthly']['#default_value'][0] == 'recurs')) {
      $recurs = t('Yes'); 
    }
    $form['submitted']['donation']['recurring'] = array(
      '#markup' => '<div class="form-item"><label>' . t('Recurring Donation?') .
        ':</label>' . $recurs . '</div>',
    );
  }
  // Clean up the donor info section - replace the form fields with read only info
  $form['submitted']['donor_information']['#title'] = t('Donor Information');
  $form['submitted']['donor_information']['first_name_readonly'] = array(
    '#markup' => '<div class="form-item"><label>' . t('First Name') . ':</label>' .
      $form['submitted']['donor_information']['first_name']['#default_value'] . '</div>',
  );
  $form['submitted']['donor_information']['last_name_readonly'] = array(
    '#markup' => '<div class="form-item"><label>' . t('Last Name') . ':</label>' .
      $form['submitted']['donor_information']['last_name']['#default_value'] . '</div>',
  );
  $form['submitted']['donor_information']['email_readonly'] = array(
    '#markup' => '<div class="form-item"><label>' . t('Email') . ':</label>' .
      $form['submitted']['donor_information']['email']['#default_value'] . '</div>',
  );
  $form['submitted']['donor_information']['first_name']['#prefix'] =
    $form['submitted']['donor_information']['last_name']['#prefix'] =
      $form['submitted']['donor_information']['email']['#prefix'] = '<div style="display:none">';
  $form['submitted']['donor_information']['first_name']['#suffix'] =
    $form['submitted']['donor_information']['last_name']['#suffix'] =
      $form['submitted']['donor_information']['email']['#suffix'] = '</div>';
  // Remove sections no one really needs to see here.
  unset($form['submitted']['donation']['amount']);
  unset($form['submitted']['donation']['other_amount']);
  unset($form['submitted']['credit_card_information']);
}

/**
 * Implements hook_fundraiser_donation_form().
 */
function fundraiser_webform_fundraiser_donation_form($form, $form_state) {
  $context = $form['#context'];
  $node = node_load($form['#node']->nid);

  // Create a data structure that will tell us exactly where each webform component lives in the FAPI array.
  $components = $node->webform['components'];
  $component_hierarchy = _fundraiser_webform_parse_components($node->nid, $components);

  // Add js and css as needed.
  $base = drupal_get_path('module', 'fundraiser_webform');
  drupal_add_js( $base . '/js/jquery.alphanumeric.js', 'file');
  drupal_add_js( $base . '/js/fundraiser.js', 'file');
  drupal_add_css( $base . '/css/fundraiser-donation-form.css', 'file');

  // Combine expiration month and year into a single component.
  $cc_exp_month_field =& _fundraiser_webform_find_field($form, $component_hierarchy['card_expiration_month']);
  $cc_exp_year_field =& _fundraiser_webform_find_field($form, $component_hierarchy['card_expiration_year']);
  $cc_info_field =& _fundraiser_webform_find_field($form, $component_hierarchy['credit_card_information']);
  $cc_exp_month_field['#default_value'] = date('n');
  $cc_exp_year_field['#default_value'] = date('Y');

  // Make sure the year field always has a good range of years.
  $this_year = date('Y');
  $years = array($this_year => $this_year);
  for ($i = 1; $i <= 5; $i++) {
    $years[$this_year + $i] = $this_year + $i;
  }
  $cc_exp_year_field['#options'] = $years;

  // Check to see if the credit card information fieldset still exists because it may have been removed.
  if (is_array($cc_info_field)) {
    $cc_info_field['expiration_date'] = array();
    $cc_info_field['expiration_date']['card_expiration_month'] = $cc_exp_month_field;
    $cc_info_field['expiration_date']['card_expiration_year'] = $cc_exp_year_field;
    $cc_info_field['expiration_date']['#weight'] = $cc_exp_month_field['#weight'];
    $cc_info_field['expiration_date']['#theme'] = 'fundraiser_credit_card_expiration_date';
  }
  else {
    // Add the new expiration_date directly to the form with the same weight as the cc_exp_month field.
    $form['expiration_date'] = array();
    $form['expiration_date']['card_expiration_month'] = $cc_exp_month_field;
    $form['expiration_date']['card_expiration_year'] = $cc_exp_year_field;
    $form['expiration_date']['#weight'] = $cc_exp_month_field['#weight'];
    $form['expiration_date']['#theme'] = 'fundraiser_credit_card_expiration_date';
  }
  // Remove old fields from form layout after moving them to their new location.
  $cc_exp_month_field = NULL;
  $cc_exp_year_field = NULL;

  // Alter country drop down to populate zone drop down.
  if (isset($component_hierarchy['country'])) {
    $country_field =& _fundraiser_webform_find_field($form, $component_hierarchy['country']);
    $country_field['#ajax'] = array(
      'callback' => '_fundraiser_webform_client_state_ajax_submit',
      'wrapper' => 'zone-select-wrapper',
      'method' => 'replace',
      'effect' => 'fade',
    );
  }

  // Add a wrapper around the state field so it can be replaced via ajax.
  if (isset($component_hierarchy['state'])) {
    $state_field =& _fundraiser_webform_find_field($form, $component_hierarchy['state']);
    // Add the wrapper for AJAX to react to.
    $state_field['#prefix'] = '<div id="zone-select-wrapper">';
    $state_field['#suffix'] = '</div>';
    // Flatten form state array so we can get the user selection easier.
    $fields = _fundraiser_array_flatten($form_state); // From fundraiser.module.
    // Country/state dependant drop down code
    $available_zones = $context->zones;
    if (array_key_exists('country', $fields)) {
      // Grab the selected country from $form_state, and set default.
      $country_field['#default_value'] = $fields['country'];
      // Filter options down to just the zones available for this country.
      if (isset($context->countries[ $country_field['#default_value'] ])) {
        $available_zones = $context->countries[ $country_field['#default_value'] ]->zones;
      }
    }
    // Given available zones, filter the dropdown to match.
    if (!empty($available_zones)) {
      $new_zone_options = array();
      foreach ($available_zones as $zone_id => $zone) {
        $new_zone_options[$zone_id] = $zone->zone_name;
      }
      $state_field['#options'] = $new_zone_options;
    }
  }

  // And lastly add a user facing message for submit.
  $form['submit']['#suffix'] = '<div class="fundraiser_submit_message">' .
    theme('image', array('path' =>  drupal_get_path('module', 'fundraiser_webform') . '/images/padlock.gif' )) .
    t('By clicking SUBMIT DONATION your credit card will be securely processed.') .
    '</div>';

  // Add a submit handler in advance of the webform_client_form_submit to cleanup after our move.
  // Important: It needs to run before webform runs, so it's getting put at the fornt of the array.
  array_unshift($form['#submit'], '_fundraiser_webform_pre_submit_cleanup');
  return $form;
}

/**
 * Submit callback, this moves the expiration month and year back into the structure where they
 * are expected, and removes 'expiration_date' from the list. If 'expiration_date' remained in the
 * submission, webform will try to look up a cid for it and reference it as if the component exists.
 * (Aka: there's no check to make sure a cid was recieved before acting on it.
 * So: We put everything back after we're done so that webform never knows the difference.
 */
function _fundraiser_webform_pre_submit_cleanup($form, &$form_state) {
  $form_state['values']['submitted']['credit_card_information']['card_expiration_month'] = 
      $form_state['values']['submitted']['credit_card_information']['expiration_date']['card_expiration_month'];
  $form_state['values']['submitted']['credit_card_information']['card_expiration_year'] = 
      $form_state['values']['submitted']['credit_card_information']['expiration_date']['card_expiration_year'];
  // Remove 'expiration_date' so webform doesn't get confused when it tries to process.
  unset($form_state['values']['submitted']['credit_card_information']['expiration_date']);
}

/**
 * AJAX callback for dealing with changes to the donation form.
 */
function _fundraiser_webform_client_state_ajax_submit($form, $form_state) {
  // Get the form item we want to render.
  return _fundraiser_webform_find_field($form, _fundraiser_webform_parse_component($form['#node']->nid, 'state'));
}

// add hook_fundraiser_donation_validate_field() for UBERCART fields. TODO.

/**
 * Implements hook_fundraiser_donation_validate().
 */
function fundraiser_webform_fundraiser_donation_validate($form, $form_state) {
  $fundraiser_fields = _fundraiser_array_flatten($form_state['values']['submitted']); // From fundraiser.module.
  $node_id = $form_state['values']['details']['nid'];
  $errors = FALSE;
  $donation_amount = $fundraiser_fields['amount'];
  $email = $fundraiser_fields['email'];
  // Look for other amount.
  if ($donation_amount == "other") {
    $donation_amount = preg_replace("/[^\d\.]/i", "", $fundraiser_fields['other_amount']);
    // Make sure other amount is numeric.
    if (!is_numeric($donation_amount)) {
      form_set_error('other_amount', "You must enter a valid donation amount.");
      $errors = TRUE;
    }
  }

  // Check for minimum amount.
  $fundraiser = _fundraiser_get_fundraiser_by_nid($node_id);
  $minimum_donation_amount = isset($fundraiser->minimum_donation_amount) ? $fundraiser->minimum_donation_amount : 10;
  $minimum_donation_amount = number_format($minimum_donation_amount, 2);
  if ($donation_amount < $minimum_donation_amount) {
    form_set_error('submitted][donation][other_amount', 
      'Your donation amount must be greater than or equal to $minimum_donation_amount.');
    $errors = TRUE;
  }

// TODO - these all need to be changed and updated to match how ubercart is pulled into our system now.
// Perhaps with the validation running through fundraiser field stuff?
  //TODO move cc number stuff to Ubercart. Fundraiser doesn't know this stuff, and neither should webform.
  $cc_number = $fundraiser_fields['card_number'];
  $cc_cvv = $fundraiser_fields['card_cvv'];
  $cc_expiration_month = $fundraiser_fields['card_expiration_month'];
  $cc_expiration_year = $fundraiser_fields['card_expiration_year'];

  // Validate the card number. By Ubercart. TODO yank this out.
  $valid_card = module_invoke_all('fundraiser_validate_card', $cc_number);
  if (!empty($cc_number) && ( !$valid_card[0]|| !ctype_digit($cc_number) )) {
    form_set_error('submitted][credit_card_information][card_number',
      'You have entered an invalid credit card number.');
    $errors = TRUE;
  }
  // Validate the card expiration date. By Ubercart.
  $valid_date = module_invoke_all('fundraiser_validate_card_expiration', $cc_expiration_month, $cc_expiration_year);
  if (!empty($cc_expiration_month) && !empty($cc_expiration_year) && !$valid_date[0]) {
    form_set_error('submitted][credit_card_information][expiration_date][card_expiration_month',
      t('The credit card you entered has expired.'));
    form_set_error('submitted][credit_card_information][expiration_date][card_expiration_year', ' ');
    $errors = TRUE;
  }
  // Validate the CVV Number.  By Ubercart.
  $valid_cvv = module_invoke_all('fundraiser_validate_card_cvv', $cc_cvv);
  if (!empty($cc_cvv) && !$valid_cvv[0]) {
    form_set_error('submitted][credit_card_information][card_cvv', t('You have entered an invalid CVV number.'));
    $errors = TRUE;
  }

  // Validate email address.
  if (!_fundraiser_validate_email($email)) {
    form_set_error('email', t('You must enter a valid email address.'));
    $errors = TRUE;
  }

  // Create watchdog entry on validation errors.
  if ($errors) {
    $base = drupal_get_path('module', 'fundraiser_webform');
    drupal_add_js($base . '/js/jquery.alphanumeric.js');
    drupal_add_js($base . '/js/fundraiser.js');
    drupal_add_css($base . '/css/fundraiser-donation-form.css');

    $message = "The following donation form fields failed local validation:\n\n";
    $check_errors = form_get_errors();
    $validation_errors = is_array($check_errors) ? array_keys($check_errors) : array();
    foreach ($validation_errors as $field) {
      $keys = explode('][', $field);
      $message .= array_pop($keys) . "\n";
    }

    $fundraiser_fields['card_number'] = substr_replace($fundraiser_fields['card_number'],
      str_repeat('*', strlen($fundraiser_fields['card_number'])), 0);
    $fundraiser_fields['card_cvv'] = substr_replace($fundraiser_fields['card_cvv'],
      str_repeat('*', strlen($fundraiser_fields['card_cvv'])), 0);

    $message .= "\n\nSubmitted Values:\n\n";
    foreach ($fundraiser_fields as $key => $value) {
      $message .= $key . ': ' . $value . "\n";
      watchdog('fundraiser_webform', $message, NULL, WATCHDOG_DEBUG, NULL);
    }
    // Provide data to fundraiser about the node that failed to validate.
    // TODO check if returning the nid is enough or if other context information will be needed.
    $errors = array();
    $errors['nid'] = $form_state['values']['details']['nid'];
    return $errors; // So fundraiser can pick up on the failure.
  }
}

/**
 * Implements hook_fundraiser_donation_submit().
 */
function fundraiser_webform_fundraiser_donation_submit($form, $form_state, $donation) {
  // Retrieve data from the submission.
  $sid = $form_state['values']['details']['sid'];
  $donation->sid = $sid;
  $fundraiser_fields = _fundraiser_array_flatten($form_state['values']['submitted_tree']); // From fundraiser.module.
/**
 * The values returned here are:
 *  amount, card_number, card_expiration_month, card_expiration_year, first_name, last_name, email, address,
 *  address_line_2, city, state, zip, quantity, other_amount.
 *
 * In the future should this change, a mapping function to map the keywords from one to the other would be good.
 */
  $donation->submission = $fundraiser_fields;

  // Set if this was a recurring donation.
  // TODO In the future we should abstract retrieveing the field information from webform to allow this call
  // to move this to sustainer. For now it can stay here, but to fully seperate we should have a field-handler
  // implem,ented by fuundraiser_webform, driven by fundraiser to allow the sustainer system to pick up the data.
  $recurs = FALSE;
  $results = _fundraiser_webform_get_components_by_keys($donation->nid, array('recurs_monthly'));
  foreach ($results as $result) {
    $recurs_cid = $result->cid;
  }
  if (!empty($recurs_cid) && isset($form_state['values']['submitted'][$recurs_cid])) {
    $value = $form_state['values']['submitted'][$recurs_cid];
    if (is_array($value)) {
      // If this is an array, then it is a single item checkbox
      if (isset($value[0])) {
        $recurs = $value[0] == 'recurs' ? TRUE : FALSE;
      }
    }
    else {
      $recurs = $value == 'recurs' ? TRUE : FALSE;
    }
  }
  $donation->recurs = $recurs ? DONATION_RECURRING : DONATION_NON_RECURRING;
  // TODO is there any other information about the submission I can grab at this point for use down the line?
}

/**
 * Implements hook_fundraiser_donation_post_submit().
 */
function fundraiser_webform_fundraiser_donation_post_submit($form, $form_state, $donation, $result) {
  // Relate the donation id to webform before we try to process the payment. //TODO change terminology
  $webform_order = array(
    'webform_nid' => $donation->nid,
    'order_id' => $donation->did,
    'sid' => $donation->sid,
    'recurring_status' => $donation->recurs,
    //TODO In the future we should clarify these data fields to clean up the database as a whole. For now this
    // can live here until we clean up the database to remove redundant data like this.
  );
  _fundraiser_webform_create_webform_order($webform_order);
  // Handle behavior if it was a failure.
  if (!$donation->result['success']) {
    // Tell webform we're not done and rebuild the form.
    unset($form_state['values']['details']['sid']);
    form_set_error('credit_card_information][card_number', $donation->result['message']);
    $form_state['values']['details']['finished'] = 0;
    $form_state['rebuild'] = TRUE;
  }
}

/**
 * Implements hook_fundraiser_donation_success().
 */
function fundraiser_webform_fundraiser_donation_success($donation) {
  // Record that the donation was successful for the webform submission.
  // TODO for some reason the transaction id isn't coming back on test gateway.
  // So this is set by default at the moment to '-'.
  $txn_id = '-';
  if (isset($donation->result['data']['txn_id'])) {
    $txn_id = $donation->result['data']['txn_id'];
  }
  $webform_order = array(
    'webform_nid' => $donation->nid,
    'order_id' => $donation->did,  
    'gateway' => $donation->node->gateway,
    'sid' => $donation->sid,
    'txn_id' => $txn_id,
  );
  _fundraiser_webform_update_webform_order($webform_order);

  // Update the uid on the webform submission table.
  _fundraiser_webform_update_submissions($donation->donation->uid, $donation->sid);

  // Update the recurring status, if it was changed by the payment gateway module
  if (isset($donation->donation->data['recurring_status']) && ($donation->recurs != $donation->donation->data['recurring_status'])) {
    $webform_order = array(
      'webform_nid' => $donation->nid,
      'order_id' => $donation->did,
      'sid' => $donation->sid,
      'recurring_status' => $donation->donation->data['recurring_status'],
    );
    //TODO In the future we should clarify these data fields to clean up the database as a whole. For now this
    // can live here until we clean up the database to remove redundant data like this.
    _fundraiser_webform_update_webform_order($webform_order);
  }
}

/**
 * Implements hook_fundraiser_donation_decline().
 */
function fundraiser_webform_fundraiser_donation_decline($donation) {
  // Delete the webform order info.
  _fundraiser_webform_delete_webform_order($donation->nid, $donation->did);
  _fundraiser_webform_delete_submissions($donation->sid);
}

/**
 * Implements hook_fundraiser_donation_cancel().
 */
function fundraiser_webform_fundraiser_donation_cancel($donation) {
  db_query('UPDATE {fundraiser_webform_order} ' .
   'SET recurring_status = :recurring_status ' .
   'WHERE order_id = :did',
    array(':recurring_status' => DONATION_CANCELLED, ':did' => $donation->did));
}

/**
 * Implements hook_fundraiser_donation_get_donation().
 */
function fundraiser_webform_fundraiser_donation_get_donation($donation) {
  $submission = _fundraiser_webform_get_webform_order_by_did($donation->did);
  if ($submission) {
    $donation->sid = $submission->sid;
    module_load_include('inc', 'webform', 'includes/webform.submissions');
    $donation->submission = webform_get_submission($donation->nid, $donation->sid); // From webform.submissions.inc
  }
}

/**
 * Implements hook_fundraiser_replace_tokens().
 */
function fundraiser_webform_fundraiser_replace_tokens($message, $donation) {
  // Replace the message with webform psuedo-tokens.
  $message = _webform_filter_values($message, $donation->node, $donation->submission, NULL, FALSE); // From webform.module
  return $message;
}

/**
 * Implements hook_fundraiser_get_fundraiser_alter().
 */
function fundraiser_webform_fundraiser_get_fundraiser_alter($fundraiser) {
  // Get the webform data for this node. This overrides the saved amount values in fundraiser itself.
  // Add the amount_values for the fundraiser information on load.
  if (is_numeric($fundraiser->nid)) {
    $amounts = _fundraiser_webform_get_extra_by_key($fundraiser->nid, 'amount');
    if (isset($amounts['items'])) {
      $amounts = preg_split('/\n/', trim($amounts['items']));
      $amounts = array_unique($amounts);
      $donation_amounts = array();
      for ($i = 0; $i < count($amounts); ++$i) {
        $donation_amounts[] = explode('|', $amounts[$i]);
      }
      $fundraiser->donation_amounts = $donation_amounts;
    }
  }
}

/**
 * Implements hook_fundraiser_create_fundraiser_alter().
 */
function fundraiser_webform_fundraiser_create_fundraiser_alter($fundraiser) {
  // Construct an array of donation amounts.
  $donation_amounts = array();
  if (isset($fundraiser->donation_amounts)) {
    $amount_sets = explode(',', $fundraiser->donation_amounts);
    $amount_sets = array_unique($amount_sets);
    foreach ($amount_sets as $amount_set) {
      $amount_set = explode('|', $amount_set);
      if (count($amount_set) == 2) {
        $donation_amounts[$amount_set[0]] = $amount_set[1];
      }
    }
    ksort($donation_amounts, SORT_NUMERIC);
  }
  $fundraiser->donation_amounts = $donation_amounts;
  // Create the components for the fundraiser, amount and otherwise.
  $components = _fundraiser_webform_create_components($fundraiser);
}

/**
 * Implements hook_fundraiser_update_fundraiser_alter().
 */
function fundraiser_webform_fundraiser_update_fundraiser_alter($fundraiser) {
  // Construct an array of donation amounts.
  $donation_amounts = array();
  if (isset($fundraiser->donation_amounts)) {
    $amount_sets = explode(',', $fundraiser->donation_amounts);
    $amount_sets = array_unique($amount_sets);
    foreach ($amount_sets as $amount_set) {
      $amount_set = explode('|', $amount_set);
      if (count($amount_set) == 2) {
        $donation_amounts[$amount_set[0]] = $amount_set[1];
      }
    }
    ksort($donation_amounts, SORT_NUMERIC);
  }
  $fundraiser->donation_amounts = $donation_amounts;
  // Update the webform component table with new data.
  if ($fundraiser->show_other_amount == 1) {
    $other_amount = _fundraiser_webform_get_extra_by_key($fundraiser->nid, 'other_amount');
    $other_amount['description'] = 'Minimum payment $' . $fundraiser->minimum_donation_amount . '.'; // TODO - fix for international audience.
    _fundraiser_webform_update_component($fundraiser->nid, 'other_amount', array('extra' => serialize($other_amount)));
  }
  // Update the amount components for the fundraiser.
  _fundraiser_webform_update_amount_components($fundraiser);
}

/**
 * Implements hook_get_donation_gateway().
 */
function fundraiser_webform_get_donation_gateway($did, $gateway) {
  // Get details on the original payment so we can load the payment gateway details.
  $submission = _fundraiser_webform_get_webform_order_by_did($did);
  if (!$submission) {
    return '';
  }
  return $submission->gateway;
}

/**
 * Implements hook_fundraiser_field_info_alter().
 */
function fundraiser_webform_fundraiser_field_info_alter($fields) {
  $email_map = array('amount', 'other_amount', 'first_name', 'last_name', 'email', 'address', 'address_line_2',
    'city', 'zip', 'country', 'state');
  foreach(element_children($fields) as $key) {
    $fields[$key] = _fundraiser_webform_fundraiser_field_info_alter($key, $fields[$key], $email_map);
  }
  return $fields;
}

/**
 * Handles recursion for fundraiser_sustainers_fundraiser_field_info_alter().
 */
function _fundraiser_webform_fundraiser_field_info_alter($field_key, $field, $map) {
  if (isset($map[$field_key])) {
    $field['#email'] = 1;
  }
  // Check for children. Recursion occurs here.
  foreach(element_children($field) as $key) {
    $field[$key] = _fundraiser_webform_fundraiser_field_info_alter($key, $field[$key], $map);
  }
  return $field;
}

/**
 * Helper functions below.
 */

/**
 * Helper function.
 * Creates a nested array of where a component exists in the FAPI array.
 */
function _fundraiser_webform_parse_component($nid, $form_key) {
  $results = _fundraiser_webform_get_components_by_keys($nid, array($form_key));
  foreach ($results as $result) {
    $cid = $result->cid;
  }
  $component_path = 'submitted[' . implode('][', _fundraiser_webform_walk_component_hierarchy($nid, $cid)) . ']';
  parse_str($component_path, $output); // Convert string to a nested array.
  return $output;
}

/**
 * Helper function.
 * Creates a nested array of where components exist in the FAPI array for all components in a webform.
 * This is needed because the webform module allows the user to move components around. Therefore
 * we must be able to find them if they are not in their usual spot.
 */
function _fundraiser_webform_parse_components($nid, $components) {
  $component_hierarchy = array();
  foreach ($components as $cid => $component) {
    $component_path = 'submitted[' . implode('][', _fundraiser_webform_walk_component_hierarchy($nid, $cid)) . ']';
    parse_str($component_path, $output); // Convert string to a nested array.
    $component_hierarchy[$component['form_key']] = $output;
  }
  return $component_hierarchy;
}

/**
 * Helper function.
 * Builds a path from the webform component to it's topmost parent.
 * Recursion is here. Be careful.
 */
function _fundraiser_webform_walk_component_hierarchy($nid, $cid, &$path = array()) { 
  // Store all the components for this node in a static cache to reduce the number of duplicated database hits.
  static $component_hierarchy = array();
  if (empty($component_hierarchy[$nid])) {
    $component_hierarchy[$nid] = array();
    $results = _fundraiser_webform_get_components_by_nid($nid);
    foreach ($results as $data) {
      $cid = $data->cid;
      $component_hierarchy[$nid][$cid][] = $data;
    }
  }
  // Build a path from the webform component to its topmost parent.
  foreach ($component_hierarchy[$nid][$cid] as $data) {
    array_unshift($path, $data->form_key);
    if ($data->pid > 0) {
      _fundraiser_webform_walk_component_hierarchy($nid, $data->pid, $path);
    }
  }
  return $path;
}

/**
 * Helper function, returns a reference to an element of a FAPI array based on a known path.
 * This returns a reference to the form variable, allowing for manipulation into the form array.
 */
function &_fundraiser_webform_find_field(&$form, $path) {
  foreach (array_keys($path) as $v) {
    if (is_array($path[$v]) && count($path[$v])) {
      // Recurse if there are more keys.
      return _fundraiser_webform_find_field($form[$v], $path[$v]);
    }
    else {
      return $form[$v];
    }
  }
}

/**
 * DB functions.
 */

/**
 * CRUD style DB function for fundraiser_webform_order.
 */
function _fundraiser_webform_create_webform_order($webform_order) {
  // Cast donation just in case.
  $webform_order = (array) $webform_order;
  // Check for old data.
  $webform_order_data = FALSE;
  if (isset($webform_order['webform_nid']) && isset($webform_order['order_id'])) {
    $webform_order_data = _fundraiser_webform_get_webform_order_by_nid_did(
      $webform_order['webform_nid'], $webform_order['order_id']);
  }
  if (!$webform_order_data) {
    $record = $webform_order;
    drupal_write_record('fundraiser_webform_order', $record);
  }
  else {
    _fundraiser_webform_update_webform_order($webform_order);
  }
}

/**
 * CRUD style DB function for fundraiser_webform_order.
 */
function _fundraiser_webform_get_webform_order_by_nid_did($nid, $did) {
  return db_query('SELECT * FROM {fundraiser_webform_order} ' .
    'WHERE webform_nid = :nid ' .
    'AND order_id = :did', // TODO change this terminology.
    array(':nid' => $nid, ':did' => $did))->fetchObject();
}

/**
 * CRUD style DB function for fundraiser_webform_order.
 */
function _fundraiser_webform_update_webform_order($webform_order) {
  // Cast donation just in case.
  $webform_order = (array) $webform_order;
  // Check for old data.
  $webform_order_data = FALSE;
  if (isset($webform_order['webform_nid']) && isset($webform_order['order_id'])) {
    $webform_order_data = _fundraiser_webform_get_webform_order_by_nid_did(
      $webform_order['webform_nid'], $webform_order['order_id']);
  }
  if (!$webform_order_data) {
    _fundraiser_webform_create_webform_order($webform_order);
  }
  else {
    $record = array_merge((array) $webform_order_data, $webform_order); 
    // Merge data together so we get everything in the record.
    drupal_write_record('fundraiser_webform_order', $webform_order, array('webform_nid', 'order_id'));
  }
}

/**
 * CRUD style DB function for fundraiser_webform_order.
 */
function _fundraiser_webform_delete_webform_order($nid, $did) {
  db_delete('fundraiser_webform_order')->condition('webform_nid', $nid)->condition('order_id', $did)->execute();
}

/**
 * DB function, get submission from a donation form.
 */
function _fundraiser_webform_get_webform_order_by_did($did) {
  return db_query('SELECT * FROM {fundraiser_webform_order} ' .
    'WHERE order_id = :did', // TODO change this terminology.
    array(':did' => $did))->fetchObject();
    // For now, there can be only one. TODO change this later.
}

/**
 * DB function, update submissions table with the right uid, sids.
 */
function _fundraiser_webform_update_submissions($uid, $sid) {
  db_query('UPDATE {webform_submissions} SET ' .
    'uid = :uid '.
    'WHERE sid = :sid',
    array(':uid' => $uid, ':sid' => $sid));
}

/**
 * DB function, delete submission data for a failed order.
 */
function _fundraiser_webform_delete_submissions($sid) {
  db_delete('webform_submitted_data')->condition('sid', $sid)->execute();
  db_delete('webform_submissions')->condition('sid', $sid)->execute();
}

/**
 * DB function, get webform component form elements.
 */
function _fundraiser_webform_get_amount_count($nid) {
  $results = db_query('SELECT COUNT(nid) as count FROM {webform_component} ' .
    'WHERE nid = :nid ' .
    'AND form_key LIKE \'amount\' ' .
    'AND type = \'select\'',
    array(':nid' => $nid));
  foreach ($results as $result) {
    return $result->count;
  }
}

/**
 * DB function, get webform component form elements.
 */
function _fundraiser_webform_get_components_by_nid($nid) {
  return db_query('SELECT * FROM {webform_component} ' .
    'WHERE nid = :nid',
    array(':nid'=>$nid))->fetchAll();
}

/**
 * DB function, select webform component given node, form key info.
 */
function _fundraiser_webform_get_component_by_nid_key($nid, $form_key) {
  return db_query('SELECT * FROM {webform_component} ' .
    'WHERE nid = :nid ' .
    'AND form_key = :form_key',
    array(':nid' => $nid, ':form_key' => $form_key))->fetchObject();
}

/**
 * DB function, get webform component form elements.
 */
function _fundraiser_webform_get_components_by_keys($nid, $form_keys) {
  if (!is_array($form_keys)) {
    $form_keys = array($form_keys);
  }
  return db_query('SELECT * FROM {webform_component} ' .
    'WHERE nid = :nid ' .
    'AND form_key IN (:form_keys)',
    array(':nid'=>$nid, ':form_keys' => $form_keys))->fetchAll();
}

/**
 * DB function, update webform component given node, form key info.
 */
function _fundraiser_webform_update_component($nid, $form_key, $fields) {
  db_update('webform_component')
    ->fields($fields)
    ->condition('nid', $nid)
    ->condition('form_key', $form_key)
    ->execute();
}

/**
 * DB function, delete webform component given node, form key info.
 */
function _fundraiser_webform_delete_component($nid, $form_key) {
  db_delete('webform_component')
    ->condition('nid', $nid)
    ->condition('form_key', $form_key)
    ->execute();
}

/**
 * Helper function, creates all donation specific webform components
 */
function _fundraiser_webform_create_components($fundraiser) {
  // Poll other modules for the information they would normally provide to the donation form.
  $fields = _fundraiser_field_info();
  // Start creating fields based on the component.
  $components = array();
  $child_weight = 0;
  foreach ($fields as $field_key => $field) {
    _fundraiser_webform_create_component($fundraiser, $field_key, $field, 0, $child_weight);
    $child_weight++;
  }
  return $components;
}

/**
 * Helper function, handles recursion for _fundraiser_webform_create_components().
 */
function _fundraiser_webform_create_component($fundraiser, $field_key, $field, $pid = 0, $weight = 0) {
  // Tweak the field with a callback as needed.
  if (isset($field['#callback']) && function_exists($field['#callback'])) {
    $field = call_user_func($field['#callback'], $fundraiser, $field);
  }
  if (!isset($field['#type'])) {
    drupal_set_message('Error in creating component: '.print_r($field,TRUE));
    return;
  }
  // Check if empty.
  if (!empty($field)) {
    // Donation amount.
    $component = array();
    $component['nid'] = $fundraiser->nid;
    $component['pid'] = $pid;
    $component['form_key'] = $field_key;
    $component['name'] = isset($field['#name']) ? $field['#name'] : '';
    if (isset($field['#value'])) {
      $component['value'] = $field['#value'];
    }
    $component['type'] = isset($field['#type']) ? $field['#type'] : '';
    $component['extra'] = isset($field['#extra']) ? $field['#extra'] : array('description' => '');
    $component['mandatory'] = isset($field['#required']) ? $field['#required'] : '';
    $component['email'] = isset($field['#email']) ? 1 : 0;
    if (isset($field['#profile_map'])) {
      $component['maps_to'] = $field['#profile_map'];
    }
    $component['weight'] = $weight;
    $pid = webform_component_insert($component);
    $components[$pid] = $component;
    // Check for children. Recursion occurs here.
    $child_weight = 0;
    foreach(element_children($field) as $key) {
      _fundraiser_webform_create_component($fundraiser, $key, $field[$key], $pid, $child_weight);
      $child_weight++;
    }
  }
}

/**
 * Helper function, updates ask amount and show other amount webform components.
 */
function _fundraiser_webform_update_amount_components($fundraiser) {
  // Get the donation component for the pid of the two fields we're looking at.
  $donation_components = _fundraiser_webform_get_components_by_keys($fundraiser->nid, array('donation'));
  foreach ($donation_components as $donation_component) {
    $pid = $donation_component->cid;
  }
  // Poll other modules for the information they would normally provide to the donation form.
  $fields = _fundraiser_field_info();
  $had_select = _fundraiser_webform_get_amount_count($fundraiser->nid);

  // First handle the amount field changes, we will always have an 'amount' component.
  // If no donation amounts are available, then we have a textfield.
  if (!count($fundraiser->donation_amounts)) {
    // If the amount field used to have select, we're deleteing it and creating a new field.
    if ($had_select) {
      _fundraiser_webform_delete_component($fundraiser->nid, 'amount');
      _fundraiser_webform_create_component($fundraiser, 'amount', $fields['donation']['amount'], $pid);
    }
    // Otherwise, the amount field is already a text field and we can leave it alone safely.
  }
  // Else we are adding (or updating) select fields.
  else {
    // If the current component is already a select, just update with current donation amount values.
    if ($had_select) {
      $extra = $fields['donation']['amount']['#extra'];
      // Construct a set of options based on the configured amounts.
      $formatted_amounts = '';
      foreach ($fundraiser->donation_amounts as $amount => $label) {
        if (!$label) {
          $formatted_amounts .= $amount . '|$' . $amount;
        }
        else {
          $formatted_amounts .= $amount . '|' . $label;
        }
        $formatted_amounts .= "\n";
      }
      if ($fundraiser->show_other_amount && count($fundraiser->donation_amounts)) {
        $formatted_amounts .= 'other|Other';
      }
      $extra['items'] = $formatted_amounts;
      _fundraiser_webform_update_component($fundraiser->nid, 'amount', array('extra' => serialize($extra)));
    }
    // We had a textfield, we need to create a select field instead.
    else {
      _fundraiser_webform_delete_component($fundraiser->nid, 'amount');
      _fundraiser_webform_create_component($fundraiser, 'amount', $fields['donation']['amount'], $pid);
    }
  }
  $message = t('The @node_title donation form has been updated.', array('@node_title' => $fundraiser->title));

  // Then handle the changes for the other_amount component, we may or may not have one of those.
  if ($fundraiser->show_other_amount && $had_select) {
    $result = _fundraiser_webform_get_component_by_nid_key($fundraiser->nid, 'other_amount');
    // Pre-existing entry in the DB for this form component and it's still enabled so we update.
    if ($result) {
      $extra = $fields['donation']['other_amount']['#extra'];
      $extra['description'] = 'Minimum payment $' . $fundraiser->minimum_donation_amount . '.';
      _fundraiser_webform_update_component($fundraiser->nid, 'other_amount', array('extra' => serialize($extra)));
      $message .= t('Other donation amount options have been updated.');
    }
    // Other amount doesn't already exist.
    else {
      _fundraiser_webform_create_component($fundraiser, 'other_amount', $fields['donation']['other_amount'], $pid);
      $message .= t('Other amount options have been added to the form.');
    }
  }
  // Other amount is disabled or there are no select options so the component needs to be removed if it exists.
  else {
    _fundraiser_webform_delete_component($fundraiser->nid, 'other_amount');
    $message .= t('Other amount options have been disabled on the form.');
  }
  watchdog('fundraiser', $message, array(), WATCHDOG_NOTICE, 'node/'.$fundraiser->nid);
}


/**
 * DB function, given a nid and field key, get and *unserialize* the extra field from webform component.
 */
function _fundraiser_webform_get_extra_by_key($nid, $form_key) {
  $extra = _fundraiser_webform_get_component_by_nid_key($nid, $form_key);
  if ($extra) {
    return unserialize($extra->extra);
  }
  return FALSE;
}