<?php
/**
 * @file
 * Code for the Springboard peer to peer feature.
 */

include_once 'springboard_p2p.features.inc';

/**
 * Implements hook_permission().
 */
function springboard_p2p_permission() {
  return array(
    'administer springboard p2p' => array(
      'title' => t('Administer springboard peer to peer.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function springboard_p2p_menu() {
  $items = array();

  $items['admin/springboard/p2p'] = array(
    'title' => 'Springboard peer to peer',
    'page callback' => 'springboard_p2p_dashboard',
    'file' => 'springboard_p2p.admin.inc',
    'file path' => drupal_get_path('module', 'springboard_p2p') . '/includes',
    'access arguments' => array('administer springboard p2p'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/springboard/p2p/dashboard'] = array(
    'title' => 'Dashboard',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer springboard p2p'),
  );

  $items['admin/springboard/p2p/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer springboard p2p'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('springboard_p2p_admin_settings'),
    'file' => 'springboard_p2p.admin.inc',
    'file path' => drupal_get_path('module', 'springboard_p2p') . '/includes',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function springboard_p2p_theme() {
  return array(
    'springboard_p2p_admin_settings' => array(
      'render element' => 'form',
      'file' => 'springboard_p2p.admin.inc',
      'path' => drupal_get_path('module', 'springboard_p2p') . '/includes',
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function springboard_p2p_form_p2p_campaign_node_form_alter(&$form, &$form_state, $form_id) {

  $lang_code = $form['#node']->language;
  $form['field_p2p_category'][$lang_code]['#ajax'] = array(
    'callback' => 'springboard_p2p_category_ajax',
    'wrapper' => 'p2p-category-ajax-wrapper',
    'effect' => 'fade',
  );

  // Set ajax target div.
  $form['#prefix'] = '<div id="p2p-category-ajax-wrapper">';
  $form['#suffix'] = '</div>';

  if (isset($form_state['input']['field_p2p_category'][$lang_code]) && is_numeric($form_state['input']['field_p2p_category'][$lang_code])) {
    $nid = $form_state['input']['field_p2p_category'][$lang_code];
    $category = node_load($nid);
    $content = $category->field_p2p_content[$lang_code][0];

    // This has value, format, safe_value.
    dpm($category->field_p2p_content[$lang_code][0]);

    $form['field_p2p_content'][$lang_code][0]['#value'] = $content['value'];
    $form['field_p2p_content'][$lang_code][0]['#format'] = $content['format'];
  }

  // This has #default_value, #value, #format
  dpm($form['field_p2p_content'][$lang_code][0]);
}

/**
 * AJAX callback for prefilling content when a category is selected.
 */
function springboard_p2p_category_ajax($form, $form_state) {
  return $form;
}
