<?php

function sf_user_service_server_info() {
  return array(
		'#name' => 'Salesforce User Import Service',
  	'#path' => 'sf-user'
  );
}

/**
* Implementation of hook_server
* @return unknown_type
*/

function sf_user_service_server() {
	require_once 'contact.inc';

  session_start();
  global $HTTP_RAW_POST_DATA;

  $server = new SoapServer( drupal_get_path('module', 'sf_user_service') .'/wsdl/sf_contact.wsdl');
  ini_set("soap.wsdl_cache_enabled", "0"); // disabling WSDL after the server is initiated
  $server->setClass('SalesforceContact'); 
  $server->handle($HTTP_RAW_POST_DATA);
}